### ISSUE TITLE
.exe or .py not building/gets instadeleted and 0 errors

### ISSUE THREAD

**Issue by gwnquintenman** [Smug246/Luna-Grabber#122]
my .py or .exe didnt build i had 0 errors my cmd just didnt open. I reinstalled it but now i dont get the extract all files notifications when i click on setup. On other builders its the same: either doesnt build or either builds and gets instadeleted. Please help

**Comment by Smug246** [comment]
turn ur av off

**Comment by Smug246** [comment]
also run `python -V` and tell me what version you have

**Comment by gwnquintenman** [comment]
av is off

**Comment by gwnquintenman** [comment]
![image](https://user-images.githubusercontent.com/124522278/216837410-daeba0bb-e665-4c75-baee-51d77e990620.png)

**Comment by gwnquintenman** [comment]
i have 3.9.5

**Comment by Smug246** [comment]
bro no wonder why ur shit doesnt work

**Comment by Smug246** [comment]
![image](https://user-images.githubusercontent.com/99215486/216837501-ffc961e1-f84d-451f-8156-9a161d83c72a.png)
ever used ur eyes before?

**Comment by gwnquintenman** [comment]
yeah but other builders dont work aswel

**Comment by gwnquintenman** [comment]
even tho i was on the right python v for that builder

**Comment by gwnquintenman** [comment]
plus it used to work back then

**Comment by gwnquintenman** [comment]
im rn on 3.11 and still doesn't work

**Comment by gwnquintenman** [comment]
it creates one but its  a .py file but i need .exe and the .py file doesnt work when i try it

**Comment by Smug246** [comment]
how do yk ur using 3.11. other version could intefere

**Comment by gwnquintenman** [comment]
i just uninstalled 3.9 and installed 3.11

**Comment by Smug246** [comment]
what happened now

**Comment by gwnquintenman** [comment]
so it does create one but this time it doesnt grab and always goes on .py even tho i chose .exe

**Comment by Smug246** [comment]
that may mean there's an error while compiling

**Comment by gwnquintenman** [comment]
it doesnt grab, and yes i dont get errors

**Comment by Smug246** [comment]
skill issue tbh

**Comment by oahx** [comment]
I got the same thing

**Comment by Smug246** [comment]
> I got the same thing

make sure you got the latest version of python. you can check this by running 'python -V' in cmd

**Comment by oahx** [comment]
I got 3.11

That's the latest right?

**Comment by HazardV6** [comment]
make sure, y'all uninstall the old version..

**Comment by Smug246** [comment]
no response so closing
