### ISSUE TITLE
La Problem of script

### ISSUE THREAD

**Issue by frjuss** [Smug246/Luna-Grabber#123]
This happened when opened
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by frjuss** [comment]
it doesnt work

**Comment by Smug246** [comment]
i cant see those images it just says there uploading

**Comment by frjuss** [comment]
![bug](https://user-images.githubusercontent.com/124
![bug2](https://user-images.githubusercontent.com/124586783/217338880-a55bcf59-6c87-40d1-80f6-ba57cdb0a5d7.jpg)
586783/217338708-ed1419de-32fb-4e93-82ff-3bf7474ec93b.jpg)

**Comment by frjuss** [comment]
@Smug246 can you see now?

**Comment by Smug246** [comment]
ye i can see. it just means theres no webhook. make sure you press check webhook when you add it in when ur building and do that before you tick any options. so just try build it again with webhook first

**Comment by frjuss** [comment]
okay i'll try then

**Comment by frjuss** [comment]
tysm now it works
