### ISSUE TITLE
master_key error

### ISSUE THREAD

**Issue by DropNod** [Smug246/Luna-Grabber#126]
master_key = CryptUnprotectData(master_key, None, None, None, 0)[1]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pywintypes.error: (-2146893813, 'CryptUnprotectData', 'Key not valid for use in the specified state.')

I have this error

**Comment by Smug246** [comment]
what os do you use?

**Comment by Smug246** [comment]
no response so closing
