### ISSUE TITLE
Unhandled exception in script

### ISSUE THREAD

**Issue by ludden8** [Smug246/Luna-Grabber#129]
Hi i get an error and it says: "failed to execute script "the . exe name" due to unhandled exception: Invalid whitespace, reserved character(s), or returncharacter(s) in header value: 'my roblox cookie'.
It also doesn't create a roblox folder in the Luna-logged.zip. everything else works as it should just not the roblox logger.

**Comment by Smug246** [comment]
ye roblox cookie grabbing is bugged rn just don't use it for now. you can still find it in the cookies.txt
