### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by PaZapdc** [Smug246/Luna-Grabber#131]
Traceback (most recent call last):
  File "klmr.py", line 1, in <module>
  File "<string>", line 4, in <module>
  File "<string>", line 1, in <module>
ValueError: bad marshal data (unknown type code)
![resim_2023-02-18_053715295](https://user-images.githubusercontent.com/121311588/219827384-f466647d-376e-4805-bd78-dc5d96e008c4.png)

when will it be fixed ?
my english can be bad

**Comment by Blank-c** [comment]
Try to comment out [these two](https://github.com/Smug246/Luna-Grabber/blob/main/tools/obfuscation.py#L26-L27) lines and rebuild

**Comment by ItsDoom** [comment]
this logger is dogwater lmfao

**Comment by Blank-c** [comment]
> this logger is dogwater lmfao

Not sure what you mean...

**Comment by Smug246** [comment]
> > this logger is dogwater lmfao
> 
> Not sure what you mean...

hes tryna say its bad.
