### ISSUE TITLE
The Program wasn't building.

### ISSUE THREAD

**Issue by HazardV6** [Smug246/Luna-Grabber#133]
The program can't build.

**Comment by BridgeKeeper1** [comment]
Same

**Comment by HazardV6** [comment]
@Smug246 Can you release the old version were it was using the command promt or batch? because this fancy UI are not building..

**Comment by BridgeKeeper1** [comment]
ikr the old version was better

**Comment by Smug246** [comment]
i've just got back from holiday but i will release the old version too but without the added options and then another release with the current gui

**Comment by HazardV6** [comment]
@Smug246 Thank you, smug I really a big fan of your program.

**Comment by BridgeKeeper1** [comment]
ty

**Comment by Smug246** [comment]
you can check the releases tab and the old version is there
