### ISSUE TITLE
Please Add BTC Clipper

### ISSUE THREAD

**Issue by Skymoney1** [Smug246/Luna-Grabber#134]
Please kindly add Crypto Clipper and send me your Btc address for a appreciation. Kindly make this feature possible please thanks in advance

**Comment by Smug246** [comment]
this is on the list. in the future yes i will add this.

**Comment by Blank-c** [comment]
Okay, so many people are asking for this feature. I am not "much" familiar with crypto and from all the information I got now, all the crypto "stealer" (not miners) just wait for the user to copy a wallet address, verify it through regex and change it. 

Is...is it all? That is not something you can call crypto stealing. Also, if we make the main grabber to keep running forever waiting for the user to copy data, it would just crash at some point.

Saying again, I don't have much info about how cryptocurrency works. I may be saying something wrong, please correct me if so. And if you have some other idea in your mind about crypto stealers, then you can send it below.

**Comment by Smug246** [comment]
ye i agree its kinda useless

**Comment by Smug246** [comment]
probs not gonna add this so closing issue
