### ISSUE TITLE
Fud exe

### ISSUE THREAD

**Issue by KDot227** [Smug246/Luna-Grabber#135]
dm for info lil mf

**Comment by Smug246** [comment]
dm me back then

**Comment by KDot227** [comment]
> dm me back then

im in school cuh

**Comment by KDot227** [comment]
I remember part of it though you need to bundle the embeddable python. Timmy made a full thing for allat in cpp but I bet I can do it all in c# if u want

**Comment by Smug246** [comment]
timmy ain't telling me shi cos he's salty i called him fat😂
