### ISSUE TITLE
Read this please :)

### ISSUE THREAD

**Issue by AdamxzV3** [Smug246/Luna-Grabber#136]
Im currently making an Luna grabber remove from pc + Emyprean, the main thing that im asking is that wont you have problem with it, since many people seems like have 'issue' removing it.

**Comment by Smug246** [comment]
ye sure. ill help if you want. this repository is educational so im happy with that

**Comment by AdamxzV3** [comment]
check my profile, its called Disinfector its made in batch cuz idk python like basic syntax etc ik, but its hell for me Csharp is way easier to understand than python please dm me on discord ahoj#8537

**Comment by Smug246** [comment]
c# easier than python😂 but sure ill take a look

**Comment by AdamxzV3** [comment]
for me it is, C# is more logic for me than python

**Comment by AdamxzV3** [comment]
Hello, can i ask if you have any spare time on the Disinfector?

**Comment by dikheee** [comment]
![image](https://user-images.githubusercontent.com/83204045/221369832-1852979d-8391-4908-83ec-2801de8b1ad4.png)
hi so i have this problem can anyone help me?

**Comment by Smug246** [comment]
> Hello, can i ask if you have any spare time on the Disinfector?
> 
> 

what do u want help with

**Comment by Smug246** [comment]
startup works fine for me so you may need to debug on ur end to see if the file gets copied. in terms of hidden files they are created in a temp folder so thats probs why u cant find them

**Comment by AdamxzV3** [comment]
ig its my problem, since i cant find it cuz normally i can find everythin not on Luna
