### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by jacoballen2005** [Smug246/Luna-Grabber#138]
now i wouldn't call this a bug, but when i create the file and have a buddie of mine try and download it, it's marked as a virus both by discord and chrome, what can i do to fix this?

**Comment by AdamxzV3** [comment]
if im reading correctly, your buddy wants to download the .exe but discord is marking it as an virus. if is that so upload it on gofile.io

**Comment by jacoballen2005** [comment]
okay cool, now when he opens it on his computer, the computer marks it as a virus and says "don't run" or "run anyway" how do you fix that?

**Comment by Smug246** [comment]
cant do anything about that
