### ISSUE TITLE
cant open the setup.bat

### ISSUE THREAD

**Issue by II-funkix-II** [Smug246/Luna-Grabber#140]
hello i need help for the setup.bat every time I open it there is this page that appears (sorry for my bad english)
![Capture d’écran 2023-03-01 163742](https://user-images.githubusercontent.com/126696620/222189188-e2466174-381a-4800-ab7c-a19c7710d993.png)

**Comment by Smug246** [comment]
can you translate to english

**Comment by II-funkix-II** [comment]
Windows cannot find 'C:\Users\(name of the computer)\OneDrive\Bureau\Luna-Grabber-main\setup.bat'. Check that you entered the correct name, then try again.

**Comment by AdamxzV3** [comment]
have you disabled anti virus, have you extracted it if you need help you can dm me on discord if you want to ahoj#8537

**Comment by II-funkix-II** [comment]
yeah i did this and i send you a friend request on discord 
![image](https://user-images.githubusercontent.com/126696620/222799346-30d4be73-21c8-493a-b426-cbb3f9f32252.png)
its me ;)
