### ISSUE TITLE
Hey When I Press Build file a black box opens quickly then closes and nothing downloads - only with an .exe file

### ISSUE THREAD

**Issue by Gitzxiou** [Smug246/Luna-Grabber#141]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by AdamxzV3** [comment]
yeah drop some screenshots, cuz im not really sure and i think you dont understand or do i :D

**Comment by TheBuilderMan** [comment]
Igu give me a day
