### ISSUE TITLE
can you hide the console window?

### ISSUE THREAD

**Issue by Nostorian** [Smug246/Luna-Grabber#142]
whenever the exe is run a cmd opens up for a split second it looks really suspicious and would be great if you removed that or atleast put an option to remove it

**Comment by Smug246** [comment]
![image](https://user-images.githubusercontent.com/99215486/223522079-48943eaf-bfc4-4475-b622-8510bef7efb9.png)
that option is enabled. but there isnt anything else i can do to make it quicker

**Comment by Blank-c** [comment]
I don't think anything pops up when using `-noconsole` flag.

**Comment by Nostorian** [comment]
> ![image](https://user-images.githubusercontent.com/99215486/223522079-48943eaf-bfc4-4475-b622-8510bef7efb9.png) that option is enabled. but there isnt anything else i can do to make it quicker

i am aware of that but when you run the exe a console in the middle of the process quickly opens and closes up within a split sec long enough for the user to notice

**Comment by Smug246** [comment]
sorry but i cant control that

**Comment by Blank-c** [comment]
> > ![image](https://user-images.githubusercontent.com/99215486/223522079-48943eaf-bfc4-4475-b622-8510bef7efb9.png) that option is enabled. but there isnt anything else i can do to make it quicker
> 
> i am aware of that but when you run the exe a console in the middle of the process quickly opens and closes up within a split sec long enough for the user to notice

Mind sending a short video?

**Comment by AWeirDKiD** [comment]
> whenever the exe is run a cmd opens up for a split second it looks really suspicious and would be great if you removed that or atleast put an option to remove it

You could also use change the python file to .pyw and modify the "builder" accordingly.

**Comment by Smug246** [comment]
> > whenever the exe is run a cmd opens up for a split second it looks really suspicious and would be great if you removed that or atleast put an option to remove it
> 
> You could also use change the python file to .pyw and modify the "builder" accordingly.

hes not talking about that

**Comment by AWeirDKiD** [comment]
> > > whenever the exe is run a cmd opens up for a split second it looks really suspicious and would be great if you removed that or atleast put an option to remove it
> > 
> > 
> > You could also use change the python file to .pyw and modify the "builder" accordingly.
> 
> hes not talking about that

Well if he changes the file type to .pyw the console will stop popping up even on the executable. It's an easy fix.

**Comment by Smug246** [comment]
> > > > whenever the exe is run a cmd opens up for a split second it looks really suspicious and would be great if you removed that or atleast put an option to remove it
> > > 
> > > 
> > > You could also use change the python file to .pyw and modify the "builder" accordingly.
> > 
> > 
> > hes not talking about that
> 
> Well if he changes the file type to .pyw the console will stop popping up even on the executable. It's an easy fix.

oh mb i thought you were talking about changing the file extension on the builder. but that might work

**Comment by AWeirDKiD** [comment]
Yea, I meant change the logger to .pyw and then modify the builder so that it actually recognizes the logger file (which should be 1 line).

**Comment by Nostorian** [comment]
> Yea, I meant change the logger to .pyw and then modify the builder so that it actually recognizes the logger file (which should be 1 line).

alright i will give that a try

**Comment by AWeirDKiD** [comment]
> > Yea, I meant change the logger to .pyw and then modify the builder so that it actually recognizes the logger file (which should be 1 line).
> 
> alright i will give that a try

Should work, correct me if I'm wrong.
