### ISSUE TITLE
My pc got infected

### ISSUE THREAD

**Issue by LeRatme** [Smug246/Luna-Grabber#143]
So when i start luna Grabber , all work correctly i create the file then ill run it to test.Now my applications doesnt want to open anymore ?

**Comment by AdamxzV3** [comment]
alr man, win+r >> shell:startup / shell:common startup in there should be your application if you do not see it go on youtube and search how to see a hidden files on your OS (11,10,), delete that application then you can use my tool to reinstall discord its called discord disinfector
