### ISSUE TITLE
Roblox information isnt being grabbed

### ISSUE THREAD

**Issue by imm4n3** [Smug246/Luna-Grabber#145]
I cant grab the roblox info
![image_2023-03-11_204850375](https://user-images.githubusercontent.com/127629723/224510995-4b51c99a-e3d1-4f5a-98b8-f141baef0596.png)
 and tested on multiple devices and it gives this to the victims pc if it helps

**Comment by Smug246** [comment]
lmao that is a roblox cookie right there. ill debug to see why thats a problem
