### ISSUE TITLE
help

### ISSUE THREAD

**Issue by NyxKazuya** [Smug246/Luna-Grabber#147]
does not capture password browsers google chrome

**Comment by Smug246** [comment]
does it grab anything from chrome aka history/cookies

**Comment by NyxKazuya** [comment]
> 



> 


You don't get the password, I just tried it.
chrome
edge
mozilla

**Comment by Smug246** [comment]
im asking if it grabs anything else

**Comment by TheOnlyHawkin** [comment]
CANT RUN THE SETUP DID THE PYTHON 3.11 AND MADE IT AS MY PATH

**Comment by mitaka699** [comment]
Why the  build button don't work please somenone help me

**Comment by Smug246** [comment]
closing because of no response
