### ISSUE TITLE
Build button doesnt work

### ISSUE THREAD

**Issue by Nsmsal** [Smug246/Luna-Grabber#150]
Hi smug, if i click on the build button he doesnt do anything.

**Comment by Smug246** [comment]
what version of python are you using?

**Comment by diplasoma** [comment]
my version is 3.9.7 will it work ?

**Comment by Smug246** [comment]
no it wont you need to use 3.11+ like it says in the instructions

![image](https://user-images.githubusercontent.com/99215486/225104423-7609e32f-b49a-43a1-9131-7a48bee45ad4.png)

**Comment by diplasoma** [comment]
![image](https://user-images.githubusercontent.com/127888076/225116450-171a1904-6162-4254-ab13-8938dece1f50.png)


python 3.11.0

**Comment by diplasoma** [comment]
@Smug246

**Comment by Smug246** [comment]
u didnt add a webhook. make sure you paste the webhook and press check webhook before you do anything

**Comment by diplasoma** [comment]
i added a  webhook and also viewed it  im on a  sandbox ist a reason ? or no

**Comment by Smug246** [comment]
sometimes it bugs out and it messes up on vm's sometimes

**Comment by Smug246** [comment]
it is possible but pretty hard for the average coder
