### ISSUE TITLE
Build button

### ISSUE THREAD

**Issue by hirrific** [Smug246/Luna-Grabber#152]
I am on python 3.11 the webhook is valid but when i press build nothing happens

**Comment by Smug246** [comment]
can you send me a screen recording of your exact steps to build it

**Comment by hirrific** [comment]
[](https://cdn.discordapp.com/attachments/1084647828720193606/1086825179243610112/IMG_1278.MOV)

**Comment by hirrific** [comment]
> can you send me a screen recording of your exact steps to build it

https://user-images.githubusercontent.com/128191915/226149003-ab7aeed8-120b-4da0-b0b4-68a08cac8706.MOV

**Comment by Smug246** [comment]
i'm gonna add a try except to the build function to see the error

**Comment by Siimuke5** [comment]
> i'm gonna add a try except to the build function to see the error

I'm having the same issue

**Comment by Smug246** [comment]
are either of u using 3.11.1?

**Comment by Smug246** [comment]
pretty sure this is fixed now
