### ISSUE TITLE
help me please

### ISSUE THREAD

**Issue by veroneke** [Smug246/Luna-Grabber#157]
when i try to build the exe grabbing file it says: [Errno 2] No such file or directory: 'C:\\Users\\(my name)\\Downloads\\Luna-Grabber-main\\Luna-Grabber-main\\luna.py'

i got python 3.11 installed ive downoaded requirements ive opened setup file but it wont work.

ive been with this issue for several months but i just cant figure this out, please help me.

**Comment by Glsck** [comment]
when i build a exe file it keeps making a py file instead

**Comment by Smug246** [comment]
what's the error

**Comment by veroneke** [comment]
> what's the error

It says this in cmd:

[Errno 2] No such file or directory: 'C:\Users\(my name)\Downloads\Luna-Grabber-main\Luna-Grabber-main\luna.py'

**Comment by Smug246** [comment]
u probs deleted the luna.py file. just download latest version

**Comment by veroneke** [comment]
> d

i downloaded the latest version but when i extract the file  the luna.py file dissapears..
can u please help me?

**Comment by Smug246** [comment]
thats a you problem. it shouldnt be dissapearing
