### ISSUE TITLE
Build button

### ISSUE THREAD

**Issue by AnisXneyZ** [Smug246/Luna-Grabber#158]
when i press build nothing [happens

**Comment by Smug246** [comment]
what version of py do u have

**Comment by AnisXneyZ** [comment]
when I open it with python version 11 nothing happens when I open it with python version 10 its working but not the build button

**Comment by Smug246** [comment]
did u add version 11 to the path?

**Comment by AnisXneyZ** [comment]
yes

**Comment by Smug246** [comment]
try use 3.11.1 , ive been dming someone who also cant build and i told them to use that exact version then it worked.

**Comment by AnisXneyZ** [comment]
not worked

**Comment by AnisXneyZ** [comment]
?

**Comment by AnisXneyZ** [comment]
plz

**Comment by Smug246** [comment]
latest version
