### ISSUE TITLE
Minecraft session stuff dont work

### ISSUE THREAD

**Issue by DavidjSpu** [Smug246/Luna-Grabber#159]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Smug246** [comment]
just means it couldn't grab it

**Comment by DavidjSpu** [comment]
I tried to grab myself

**Comment by Smug246** [comment]
go to the path and see if its there

**Comment by DavidjSpu** [comment]
I tried to grab myself

**Comment by Smug246** [comment]
no try and go to this exact path and see if you have it.  C:\Users\yourname\AppData\Roaming\.minecraft 
replace yourname with ur actual name.

**Comment by DavidjSpu** [comment]
I have Minecraft

**Comment by Smug246** [comment]
bro do you have that path yes or no. i understand you have minecraft but the path may be incorrect

**Comment by Smug246** [comment]
no answer so closing
