### ISSUE TITLE
it does not add the icons

### ISSUE THREAD

**Issue by DiabloX27** [Smug246/Luna-Grabber#161]
whenever i try to add an icon (converted to .ico) it says no icon found

**Comment by Smug246** [comment]
can you record how you add it and the error

**Comment by DiabloX27** [comment]
it happens when I insert an .ico file from the desktop
![Immagine 2023-03-25 002750](https://user-images.githubusercontent.com/122049624/227661266-b2d739fd-bf8e-4a95-b141-971b572c4cb4.png)

**Comment by Smug246** [comment]
is the location right?

**Comment by DiabloX27** [comment]
what do you mean?, I put the icons on the desktop

**Comment by Smug246** [comment]
put the icon in the same folder as the the other files

**Comment by DiabloX27** [comment]
i just tried it and it doesn't work

**Comment by Smug246** [comment]
it works fine for me
