### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Passsword1234** [Smug246/Luna-Grabber#163]
when I open setup.bat, purple text then Exiting... then nothing shows ? I tried to open builder.pyw and luna.py but no one of them opened

**Comment by Smug246** [comment]
do you have python installed and added to path??

**Comment by Passsword1234** [comment]
i fixed it dw

**Comment by Passsword1234** [comment]
Python 3.11.2

**Comment by Passsword1234** [comment]
why you dont have chat in your discord server ?

**Comment by Passsword1234** [comment]
yeah but i was having 3 version of python

**Comment by Smug246** [comment]
i dont want to get termed from people asking for help there
