### ISSUE TITLE
there is no build

### ISSUE THREAD

**Issue by jamiekarvans** [Smug246/Luna-Grabber#166]
hi downloaded the latest that you've just fixed the build button
the cmd screen pops up and it looks like it's building but there is no build and no exe file
also latest python is installed

**Comment by Smug246** [comment]
could you screen record so i can see the error your getting?

**Comment by jamiekarvans** [comment]
Hi, it was using python3.9 instead of latest version, even tho command line
py --version was giving me 3.11 but python --version was giving me 3.9 and
I think that was causing the problem
I've just brought up python3.11 on top in the environment variables PATH
list and it fixed the problem.
Thanx anyway for replying.

**Comment by jamiekarvans** [comment]
Except now, I see it doesn't grab the passwords,
It just sends the cookies and there in the history and password files is empty, while I manually checked and there is passwords saved on the computer
The anti virus is off aswell

**Comment by Smug246** [comment]
what browser do you use?

**Comment by jamiekarvans** [comment]
i'm using firefox, chrome, edge and in all of them passwords and cookies are saved
it sends the cookies correctly but the passwords file is not complete it just sends a few of the passwords and i don't know from which browser it grabbed it but it's not even complete
i've tested it on afew other computers and it's the same thing
cookies are ok but the passwords are not, sometimes there is no passwords file at all while i manually checked and sure there is passwords saved even checked the directory of logins and it exists

**Comment by Smug246** [comment]
not completley sure to be honest with you. i can try to do some deeper debugging

**Comment by jamiekarvans** [comment]
I don't know where was the problem but I fixed it by adding the code to manually get Login Data file from %LocalAppData%\Google\Chrome\User Data\Default\Login Data
And decrypt using encrypted_key in Local State file in directory %LocalAppData%\Google\Chrome\User Data\Local State
And it fixed the problem and sent all the passwords correctly
I'm assuming you can do the same thing for Firefox but I haven't tried it since I'm just started programming and it's a bit complicated for Firefox for me but eventually here is the way, encrypted key and the logins file data for Firefox which you can use to decreypt data:
Firefox <32 (key3.db, signons.sqlite)
Firefox >=32 (key3.db, logins.json)
Firefox >=58.0.2 (key4.db, logins.json)
Firefox >=75.0 (sha1 pbkdf2 sha256 aes256 cbc used by key4.db, logins.json)
at least Thunderbird 68.7.0, likely other versions

I will create a pull request and will send the code I've added and changed you can use it if you want, but it's bad code I think it would be better if you code it yourself haha
Also would be really nice if you could add the Firefox too
And do you have any idea how to make the stub work on older windows versions like windows 7 ? Without getting the python error

**Comment by Smug246** [comment]
alr
