### ISSUE TITLE
I really need help

### ISSUE THREAD

**Issue by Chrizzy420** [Smug246/Luna-Grabber#168]
I'm trying to run this, firstly I extracted the zip to a new folder, ran the bat file, and then I tried running the builder, which doesn't even open, then I tried running luna, but that instantly closes. It doesn't really seem to work? Everything I open except for the bat file just closes

**Comment by Smug246** [comment]
have you read the instructions?

**Comment by Chrizzy420** [comment]
Yes, I've read them

**Comment by Chrizzy420** [comment]
It worked! Thank you
