### ISSUE TITLE
no screenshots

### ISSUE THREAD

**Issue by IDAsnifferxx11** [Smug246/Luna-Grabber#169]
Not much explanation is needed. It doesn't give screenshots.

**Comment by Smug246** [comment]
im aware. if you look in the code its commented out because it wasnt working. im fixing it now

**Comment by IDAsnifferxx11** [comment]
> im aware. if you look in the code its commented out because it wasnt working. im fixing it now

Nice hopefully its fixed soon. Any chance I can get your gram or discord?

**Comment by Smug246** [comment]
https://discord.gg/tNMdkpW7EU

**Comment by Smug246** [comment]
@IDAsnifferxx11 This is now fixed in the most recent update. im gonna close this now
