### ISSUE TITLE
I don't know how to download

### ISSUE THREAD

**Issue by PFES2** [Smug246/Luna-Grabber#170]
The rules aren't specific enough
Is luna grabber paid?

My friend said it was something called inder, I know he was lying because he showed me logging someone and the bot said luna.

**Comment by PFES2** [comment]
got the zip file, extracted and ran the setup then the builder and now nothing is happening

**Comment by Smug246** [comment]
did u download python and add it to path

**Comment by PFES2** [comment]
i already had python before downloading luna grabber, how do i add it to my path?

> did u download python and add it to path
