### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by MeatorJam** [Smug246/Luna-Grabber#171]
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\[myname]\\AppData\\Local\\pyinstaller\\bincache01_py310_64bit\\libffi-7.dll'

**Comment by Smug246** [comment]
might be a problem with your pyinstaller version

**Comment by MeatorJam** [comment]
> 

how do I fix it?

**Comment by Smug246** [comment]
try uninstalling pyinstaller and reinstall it. you can do this by opening the cmd and running these two commands. First one `pip uninstall pyinstaller` then second one `pip install pyinstaller`

**Comment by MeatorJam** [comment]
> try uninstalling pyinstaller and reinstall it. you can do this by opening the cmd and running these two commands. First one `pip uninstall pyinstaller` then second one `pip install pyinstaller`
it worked, but it didn't send the info to my webhook

**Comment by Smug246** [comment]
??
