### ISSUE TITLE
When I click to build nothing happens.

### ISSUE THREAD

**Issue by t1zzo** [Smug246/Luna-Grabber#172]

**Comment by PFES2** [comment]
its same with me too

**Comment by MeatorJam** [comment]
open console, and type: python builder.pyw

**Comment by wsgyobros** [comment]
whats console

**Comment by Smug246** [comment]
run the file with administrator and it'll work. its a permission denied error

**Comment by coliwoli** [comment]
> run the file with administrator and it'll work. its a permission denied error

i tried that and it still didnt work. since its a python file I opened it with admin privileges through task manager. any other solutions? when I click build (all the information is inputted: webhook, file type, checkboxes etc.) nothing happens at all.

**Comment by Smug246** [comment]
where is the folder located currently. try and put it in a directory that has write permissions

**Comment by 1snkeyes1** [comment]
when i click the builder nth happens can u help i tried almost anything not working

**Comment by 1snkeyes1** [comment]
wait nvm i uninstalled my python then installed it from setup and it worked + it doesnt work with any other python except for 3.11.0 when u install that u need to open setup 1 more to install the other stuff and then it will work. i guess that is what ur problem

**Comment by Smug246** [comment]
crazy its almost like thats exactly what i tell you to do in the instructions

![image](https://user-images.githubusercontent.com/99215486/232048855-49e33b2f-acde-4283-b596-26e03ebcea7c.png)

**Comment by Canonicallycanon** [comment]
> wait nvm i uninstalled my python then installed it from setup and it worked + it doesnt work with any other python except for 3.11.0 when u install that u need to open setup 1 more to install the other stuff and then it will work. i guess that is what ur problem

yo can i get some help with this man i still cant figure it out
