### ISSUE TITLE
Can you add some new features to the grabber. Vesper updated it, but  i want to use Luna.

### ISSUE THREAD

**Issue by watthefuck3** [Smug246/Luna-Grabber#174]
Can you add some new features to the grabber. Vesper updated it, but  i want to use Luna.

**Comment by furax124** [comment]
> tf is vesper and what do they have?

They have a better menu and better sending webhook is more beautiful and suggestion bro add steam stealer and add all of vesper menu

**Comment by furax124** [comment]
> stealing exodus telegram and metamask is useless. it just grabs the directories. nothing inside those folders are useful. auto spreading is a possibility and steam stealer is also kinda useless.

But the steam is good a features again

**Comment by Smug246** [comment]
can you actually do anything with it though?

**Comment by furax124** [comment]
> can you actually do anything with it though?

Yeah if you’re replace the folder you have accès at is account and Metamask and exodus and telegram too it’s bypass password and 2fa

**Comment by furax124** [comment]
> can you show me an image of their webhook sending

![Uploading FC91340B-1FD4-471A-9FA8-6C0989AEB387.jpeg…]()

**Comment by furax124** [comment]
> can you show me an image of their webhook sending

![Uploading A505E9AA-E132-4EF8-ADCF-36DC0F5CEC48.jpeg…]()

**Comment by furax124** [comment]
![Uploading D51D7995-FEC9-4286-A6BA-BB2226761E12.jpeg…]()

**Comment by furax124** [comment]
![Uploading E3145235-01E5-47A6-9ABD-AF28636450AA.jpeg…]()

**Comment by furax124** [comment]
![Uploading C296AB6F-193F-472D-A59C-7AD2D440259B.jpeg…]()

**Comment by furax124** [comment]
![C296AB6F-193F-472D-A59C-7AD2D440259B](https://user-images.githubusercontent.com/84036582/229200442-e142cdee-81f2-4a5f-a9fe-96669f0c8b8c.jpeg)

**Comment by furax124** [comment]
![Uploading 5B0DEBD7-0421-4FC5-86CC-2EA858E7AEDE.jpeg…]()

**Comment by Smug246** [comment]
thats ugly af

**Comment by furax124** [comment]
> thats ugly af

Nah do you see another picture ?

**Comment by furax124** [comment]
Its sending

**Comment by Smug246** [comment]
can only see one and it doesnt look great at all

**Comment by furax124** [comment]
![E7E1E48B-D64A-4853-BD8E-142419DD2855](https://user-images.githubusercontent.com/84036582/229200682-37679ca2-f166-4863-ad8e-27f517bbaad6.jpeg)

**Comment by furax124** [comment]
![08667CF9-99B3-4176-A0DE-9488592AF8AE](https://user-images.githubusercontent.com/84036582/229200945-02461cc6-fd2c-432a-b9e4-95e5310aed5d.jpeg)

**Comment by Smug246** [comment]
thats the goofiest embed emojis ive ever seen

**Comment by furax124** [comment]
![00847DC4-5ABF-43CF-B022-6B7CDC8BF5B3](https://user-images.githubusercontent.com/84036582/229201068-71eb7992-85ed-41d7-b1bc-221162da149e.jpeg)

**Comment by furax124** [comment]
> thats the goofiest embed emojis ive ever seen

Yeah but lot of people like this

**Comment by Smug246** [comment]
there more than welcome to download vesper then

**Comment by furax124** [comment]
> 

Yeah add it sry if I’m not speak good English I’m French this is difficult

**Comment by Smug246** [comment]
ill start working on luna again ig. i kinda left it for a bit because i was bored but i could add some more features. give me a list and ill work on the ones i think are worth it

**Comment by furax124** [comment]
> there more than welcome to download vesper then

He have file recovery too vesper he’s grabber it’s not good but you have a good one you just need to make it beautiful for final grabber

**Comment by furax124** [comment]
> ill start working on luna again ig. i kinda left it for a bit because i was bored but i could add some more features. give me a list and ill work on the ones i think are worth it

Ok bro i send you

**Comment by furax124** [comment]
> ill start working on luna again ig. i kinda left it for a bit because i was bored but i could add some more features. give me a list and ill work on the ones i think are worth it

Nuke pc
Files sniper for password bank folder and again upload it in anonfiles
Reboot pc
Telegram,steam,exodus,Metamask recovery 
Do a better sending webhook
Crypto cliper
Discord spreading in dm
Webhook anti delete ( webhook junk or encode in vesper )
A multi tool in Luna grabber such nuke account delete webhook webhook spammer and a lot 
Hide payload in python file
Make a better obfuscation if you can
Cookie checker ( but not important )
Keylogger send it in webhook 
Group finder in Roblox
Clothing stealer in Roblox
Webcam screenshot
Vpn stealer
And this all I think

**Comment by Smug246** [comment]
write i like some of those ideas so ill make a list of those that ill do. ill exclude the ones i dont like

steam session data
cleaner webhook
spread file in discord dms
better obfuscation
webcam screenshot

just these for now

**Comment by Smug246** [comment]
the reason i excluded things like nuke pc and keylogger because i dont want this logger to be a rat. its purely just for file recovery

**Comment by furax124** [comment]
> right i like some of those ideas so ill make a list of those that ill do. ill exclude the ones i dont like
> 
> steam session data cleaner webhook spread file in discord dms better obfuscation webcam screenshot
> 
> just these for now

Cleaner webhook as vesper picture ?

**Comment by furax124** [comment]
> the reason i excluded things like nuke pc and keylogger because i dont want this logger to be a rat. its purely just for file recovery

Ok bro its clean you’re are the best

**Comment by furax124** [comment]
> 

Okok cleaner as vesper ?

**Comment by SMDXGitHub** [comment]
> right i like some of those ideas so ill make a list of those that ill do. ill exclude the ones i dont like
> 
> steam session data cleaner webhook spread file in discord dms better obfuscation webcam screenshot
> 
> just these for now

yo man is steam session data any useful? steam guard and stuff are pretty much impossible to get trough without some kind of account manipulation in the steam folders

**Comment by watthefuck3** [comment]
https://github.com/vesperlol/Vespy-Grabber-v2.0 this is vespers grabber

**Comment by Smug246** [comment]
> > right i like some of those ideas so ill make a list of those that ill do. ill exclude the ones i dont like
> > steam session data cleaner webhook spread file in discord dms better obfuscation webcam screenshot
> > just these for now
> 
> yo man is steam session data any useful? steam guard and stuff are pretty much impossible to get trough without some kind of account manipulation in the steam folders

i agree tbh

**Comment by furax124** [comment]
> > right i like some of those ideas so ill make a list of those that ill do. ill exclude the ones i dont like
> > steam session data cleaner webhook spread file in discord dms better obfuscation webcam screenshot
> > just these for now
> 
> yo man is steam session data any useful? steam guard and stuff are pretty much impossible to get trough without some kind of account manipulation in the steam folders

No just copy the steam data and you have his account

**Comment by Smug246** [comment]
> https://github.com/vesperlol/Vespy-Grabber-v2.0 this is vespers grabber

vesper get banned?

**Comment by furax124** [comment]
> > https://github.com/vesperlol/Vespy-Grabber-v2.0 this is vespers grabber
> 
> vesper get banned?

Yeah

**Comment by MeatorJam** [comment]
> > > https://github.com/vesperlol/Vespy-Grabber-v2.0 this is vespers grabber
> > 
> > 
> > vesper get banned?
> 
> Yeah

lmaoxd

**Comment by KDot227** [comment]
> > tf is vesper and what do they have?
> 
> They have a better menu and better sending webhook is more beautiful and suggestion bro add steam stealer and add all of vesper menu hé gonna add keylogger and all of good tool add the discord tools too in your gui builder it’s not very difficult because you already do that telegram stealer exodus and Metamask stealer crypto clipper and screen of webcam auto spreading in dm discord nuke user of pc and reboot pc and the good a webhook enconding if you want and webhook junker and share text to

its also backdoored lmao

**Comment by furax124** [comment]
> > > tf is vesper and what do they have?
> > 
> > 
> > They have a better menu and better sending webhook is more beautiful and suggestion bro add steam stealer and add all of vesper menu hé gonna add keylogger and all of good tool add the discord tools too in your gui builder it’s not very difficult because you already do that telegram stealer exodus and Metamask stealer crypto clipper and screen of webcam auto spreading in dm discord nuke user of pc and reboot pc and the good a webhook enconding if you want and webhook junker and share text to
> 
> its also backdoored lmao

Proof ?

**Comment by KDot227** [comment]
> > > > tf is vesper and what do they have?
> > > 
> > > 
> > > They have a better menu and better sending webhook is more beautiful and suggestion bro add steam stealer and add all of vesper menu hé gonna add keylogger and all of good tool add the discord tools too in your gui builder it’s not very difficult because you already do that telegram stealer exodus and Metamask stealer crypto clipper and screen of webcam auto spreading in dm discord nuke user of pc and reboot pc and the good a webhook enconding if you want and webhook junker and share text to
> > 
> > 
> > its also backdoored lmao
> 
> Proof ?

bro all his repos get deleted after they get exposed 😭 he also admits to it lmao

**Comment by SMDXGitHub** [comment]
> > > > > tf is vesper and what do they have?
> > > > 
> > > > 
> > > > They have a better menu and better sending webhook is more beautiful and suggestion bro add steam stealer and add all of vesper menu hé gonna add keylogger and all of good tool add the discord tools too in your gui builder it’s not very difficult because you already do that telegram stealer exodus and Metamask stealer crypto clipper and screen of webcam auto spreading in dm discord nuke user of pc and reboot pc and the good a webhook enconding if you want and webhook junker and share text to
> > > 
> > > 
> > > its also backdoored lmao
> > 
> > 
> > Proof ?
> 
> bro all his repos get deleted after they get exposed 😭 he also admits to it lmao

yes, always use a vm. I did use it and it was pretty ass too many errors and crap.

**Comment by watthefuck3** [comment]
> > > > > tf is vesper and what do they have?
> > > > 
> > > > 
> > > > They have a better menu and better sending webhook is more beautiful and suggestion bro add steam stealer and add all of vesper menu hé gonna add keylogger and all of good tool add the discord tools too in your gui builder it’s not very difficult because you already do that telegram stealer exodus and Metamask stealer crypto clipper and screen of webcam auto spreading in dm discord nuke user of pc and reboot pc and the good a webhook enconding if you want and webhook junker and share text to
> > > 
> > > 
> > > its also backdoored lmao
> > 
> > 
> > Proof ?
> 
> bro all his repos get deleted after they get exposed 😭 he also admits to it lmao

Thats why i want to use luna lmao

**Comment by KDot227** [comment]
fr ( or use min + rep )

**Comment by Bossboa** [comment]
> > thats ugly af
> 
> Nah do you see another picture ?

Bro this is dualhooked man

**Comment by XdHarryCr7** [comment]
guys whats vespys discord send me it in dms or just reply it pls dm {Frost}#3793

**Comment by KDot227** [comment]
> guys whats vespys discord send me it in dms or just reply it pls dm {Frost}#3793

why do u want it 💀
