### ISSUE TITLE
When someone clicks on the builded file cmd opens and imidiantly closes

### ISSUE THREAD

**Issue by KKkryn** [Smug246/Luna-Grabber#181]
It makes the builded file not work
When the builed file is opened a black box apears and dissapears right after

It should send the data to the webhook

![Screenshot 2023-04-06 125322](https://user-images.githubusercontent.com/129985919/230356618-2a2b7c2b-44df-47a2-b2fd-8ed463ae78eb.png)
.

**Additional context**

**Comment by Smug246** [comment]
try opening it with cmd from the directory the built file is in.
