### ISSUE TITLE
luna.py closes immediatly after i laucnhed it

### ISSUE THREAD

**Issue by Swell123** [Smug246/Luna-Grabber#183]
I click on luna.py and it closes immediatly while i ran setup.bat correctly

**Comment by Smug246** [comment]
you have to click builder.py not luna.py

**Comment by aljawary** [comment]
Skill issue

**Comment by Swell123** [comment]
> you have to click builder.py not luna.py

Yes but why my builder.py is a builder.pyw

**Comment by Smug246** [comment]
ye thats fine. run it in cmd to see what error ur getting

**Comment by Cryptic1526** [comment]
Heya! My build.pyw is not opening at all. I tried opening it with python 3.11. luna.py isnt working either, but it closes immediatly after i launched it. All dependencies are installed. Help pls?

**Comment by Cryptic1526** [comment]
> Heya! My build.pyw is not opening at all. I tried opening it with python 3.11. luna.py isnt working either, but it closes immediatly after i launched it. All dependencies are installed. Help pls?

Just realised I needed to run it in a cmd with `python build.pyw`.

Cheers for the great product!

**Comment by Kinan-Ma** [comment]
it says ModuleNotFoundError: No module named 'psutil'
