### ISSUE TITLE
No scheme supplied

### ISSUE THREAD

**Issue by RubyDevil** [Smug246/Luna-Grabber#185]
![image](https://user-images.githubusercontent.com/74435331/230802851-7a53267e-4960-4532-ada4-d99bc922bafe.png)

**Comment by RubyDevil** [comment]
happens when i try to run the .exe after build

**Comment by RubyDevil** [comment]
I just built another and it works fine now, but that very one is still not working, just wanted to let you know. You can close this issue once you've seen it!

**Comment by Smug246** [comment]
it basically just means the webhook didnt get added. this happens if u dont press check webhook or tick an option before adding a webhook
