### ISSUE TITLE
EXE not working after build

### ISSUE THREAD

**Issue by Mrbinkyboo** [Smug246/Luna-Grabber#187]
![Screenshot 2023-04-10 122828](https://user-images.githubusercontent.com/124556935/230813469-4f7f85df-2b63-45d5-9b07-ba1f822060b5.png)

i tried multiple times not working and yes antivirus is disabled

**Comment by watthefuck3** [comment]
if you had add to start up on, it wont work. GLitch

**Comment by Smug246** [comment]
no thats not the reason. it just means you didnt add a webhook

**Comment by DriftMilk** [comment]
> no thats not the reason. it just means you didnt add a webhook

Had the same issue even though I added a webhook,

**Comment by watthefuck3** [comment]
> no thats not the reason. it just means you didnt add a webhook
The same came for me and i turned off add to start up and it worked.

**Comment by EzDrippy** [comment]
same problem and i already add the webhook

**Comment by 666neocortex** [comment]
> same problem and i already add the webhook

yall have to keep updating it
