### ISSUE TITLE
bug while openning file

### ISSUE THREAD

**Issue by jabacaja** [Smug246/Luna-Grabber#193]
when i open file it says this
![Screenshot 2023-04-11 132701](https://user-images.githubusercontent.com/130457665/231148616-e8757cbc-cb6c-4b04-af94-a0e3475abc7b.png)

Please help,thanks.

**Comment by XeinTDM** [comment]
Write that in cmd

**Comment by jabacaja** [comment]
it still shows same problem,i wrote that on cmd and still showing same

**Comment by Smug246** [comment]
everytime u build it does it say that?

**Comment by 1snkeyes1** [comment]
disable real time protection

**Comment by Smug246** [comment]
lmao
