### ISSUE TITLE
exe file not working properly

### ISSUE THREAD

**Issue by noam466sdrthfdht** [Smug246/Luna-Grabber#194]
**Describe the bug**
When a user opens the rat file it sends the owner not all the information needed and it displays the ratted user an error (the fake error is not enabled and the discord info, minecraft info and all are enabled)

**To Reproduce**
Create a regular exe rat file without the fake error, then when the ratted user runs it, it displays an error for him and doesnt send you all of the information.

**Expected behavior**
for it to send the whole information to the webhook

**Screenshots**
![image](https://user-images.githubusercontent.com/83455940/231286158-eeeb372b-837d-4fca-a15c-f88c07238230.png)

**Comment by Smug246** [comment]
i have no idea where that even comes from

**Comment by noam466sdrthfdht** [comment]
so what do i supposed to do?

**Comment by Smug246** [comment]
copy and paste the full error so i can see it from the start

**Comment by 666neocortex** [comment]
> copy and paste the full error so i can see it from the start

i have the same error in different lines, the main text is the same

**Comment by Smug246** [comment]
if you could send the full error that would be appreciated

**Comment by ianbloc** [comment]
Try to check if all the correct packages are installed and that they are installed to python 3.11.0 after that try toggling features for me disabling minecraft logger made it work
