### ISSUE TITLE
Injection isn't working and doesn't send passwords

### ISSUE THREAD

**Issue by MeatorJam** [Smug246/Luna-Grabber#197]
I grabbed like 8 ppl, but it didn't send their passwords, and when they changed their discord token, the injection didn't work. I also grabbed myself, but I couldn't find my Minecraft data. (The directory C:\Users\emyname\AppData\Roaming\.minecraft exists, but there is no token.)

**Comment by Smug246** [comment]
wdym doesnt send passwords and i think injection is broke rn

**Comment by MeatorJam** [comment]
> wdym doesnt send passwords and i think injection is broke rn

It doesn't send the passwords saved on the computer

**Comment by Smug246** [comment]
at all?

**Comment by MeatorJam** [comment]
> at all? what browser do you use

[https://cdn.discordapp.com/attachments/1075627849693798440/1095389441570377858/Luna-Logged-musko.zip](url)
This is who I logged

**Comment by Smug246** [comment]
latest version i fixed all this
