### ISSUE TITLE
Webhook hacked/found.

### ISSUE THREAD

**Issue by MeatorJam** [Smug246/Luna-Grabber#199]
**Describe the bug**
I don't know how somebody got to my webhook, but my webhook is getting spammed.

**Expected behavior**
Maybe not be able to find/debug the webhook, because the user keeps on finding it.

**Screenshots**
![image](https://user-images.githubusercontent.com/104646534/231599852-0c91ab9e-8e56-4cb4-9ade-9a781db37a87.png)

**Comment by Smug246** [comment]
lmao do you enable obfuscation?

**Comment by MeatorJam** [comment]
> lmao do you enable obfuscation?

xd yes

**Comment by Smug246** [comment]
not a lot you can do about that. just means someone knows how to deobfuscate it

**Comment by Smug246** [comment]
not an error so closing
