### ISSUE TITLE
when i click build, nothing happens. I waited for hours and tried multiple times but still didnt work

### ISSUE THREAD

**Issue by 5216ff** [Smug246/Luna-Grabber#201]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Smug246** [comment]
what version of python do you have. quick fix is to just run it as administrator

**Comment by JuicePlum6** [comment]
> what version of python do you have. quick fix is to just run it as administrator

also having same problem and i have 3.11 installed
