### ISSUE TITLE
stop trying to make this grabber

### ISSUE THREAD

**Issue by 8FrMc** [Smug246/Luna-Grabber#203]
this grabber breaks after a pc start like bro

**Comment by Smug246** [comment]
bro what

**Comment by Smug246** [comment]
lmao

just means theres not a webhook in it

**Comment by 8FrMc** [comment]
there is

**Comment by Smug246** [comment]
well that error says there isnt. so there isnt. build it again but make sure you input the webhook first and press check webhook.

**Comment by 8FrMc** [comment]
do i need to click check webhook every time???
and can you also add so it would send error log

**Comment by Smug246** [comment]
yes everytime you build it. error log for what?

**Comment by Smug246** [comment]
show me

**Comment by 8FrMc** [comment]
![image](https://user-images.githubusercontent.com/117525461/232048719-96b2387b-226b-4e71-a25c-ec30646ccf30.png)
something like this in luna-grabbed

**Comment by 8FrMc** [comment]
![image](https://user-images.githubusercontent.com/117525461/232048923-c0cedda6-b1cf-4ae7-ab8e-4db597f40bc4.png)
when i need to click check webhook?

**Comment by Smug246** [comment]
so you press check webhook before you do tick any options

**Comment by Smug246** [comment]
latest version i fixed it.

**Comment by Smug246** [comment]
> is this dual hooked?

no lol its all open source so you can check it urself

**Comment by Bossboa** [comment]
> with error message enabled this dont happen smh

bro you need latest python
