### ISSUE TITLE
when i open builder after setup it does nothing i have python installed and opened setup.bat and no work

### ISSUE THREAD

**Issue by ceexzz4** [Smug246/Luna-Grabber#204]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by JuicePlum6** [comment]
I am also getting the error of having requirements installed and clicking builder does nothing

**Comment by BobbityBoo** [comment]
maybe run this command line in the same directory `python build.pyw`

**Comment by Smug246** [comment]
probably means you dont have it added to path

**Comment by Smug246** [comment]
run `python builder.pyw` in that directory and it will tell you

**Comment by JuicePlum6** [comment]
> run `python builder.pyw` in that directory and it will tell you

that worked
