### ISSUE TITLE
Discord injection not working

### ISSUE THREAD

**Issue by BumbiSkyRender** [Smug246/Luna-Grabber#205]
So, I grabbed someone, but then they changed their discord password and luna grabber doesn't send me the new pass and token, pls fix this, take your time as I really appreciate this.

this issue happens every time.One time it barely worked and sent this:
![image](https://user-images.githubusercontent.com/113386189/232159873-c4d4edc9-9c5e-4d05-bec2-3286c6c5be4a.png)

Regards, BumbiSkyRender.

**Comment by Smug246** [comment]
ye ive noticed its broken probs gonna have to use a new one as i dont know javascript so i couldnt make it myself

**Comment by BumbiSkyRender** [comment]
Oh it worked now ty:
![image](https://user-images.githubusercontent.com/113386189/232230678-c545e88a-6295-45e2-b5dc-502983900352.png)

**Comment by BumbiSkyRender** [comment]
imma close it after confirming that it works

**Comment by Smug246** [comment]
ok
