### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Castroojg** [Smug246/Luna-Grabber#207]
It's not working like it used to, do you have any explanation for this? since it was recently updated

**Comment by Smug246** [comment]
if you don't give me an error to fix i can't help you

**Comment by Castroojg** [comment]
From what I understand I click on BUILDER and it doesn't open, I've run the setup before and still nothing happens.

**Comment by Castroojg** [comment]
From what I understand I click on BUILDER and it doesn't open, I've run the setup before and still nothing happens.

**Comment by Castroojg** [comment]
> se você não me der um erro para corrigir eu não posso te ajudar
my builder does not open, I already ran the setup and still nothing

**Comment by Smug246** [comment]
u probs need to add it to path

**Comment by Castroojg** [comment]
> você provavelmente precisa adicioná-lo ao caminho
how do I do that?Do you have a video teaching step by step? maybe this can help me

**Comment by Smug246** [comment]
google is free https://youtu.be/AMAE0S_NzxE

**Comment by STATUS2121** [comment]
smug im sorry bro. ppl rly dont use their brain in 202023

**Comment by Smug246** [comment]
fr man
