### ISSUE TITLE
Pressing build doesnt work

### ISSUE THREAD

**Issue by Naahhmate** [Smug246/Luna-Grabber#208]
ye, nothing happens when i press it

**Comment by Smug246** [comment]
can you run python -V and tell me what it says

**Comment by Naahhmate** [comment]
Python 3.10.11

**Comment by Castroojg** [comment]
me too, i need help

**Comment by Smug246** [comment]
you need 3.11+ read the instructions

**Comment by Naahhmate** [comment]
"python 3.11.x and up are not supported by empyrean. Please downgrade to python 3.10.x.
Press any key to continue . . ."

**Comment by Smug246** [comment]
mate does this look like empyrean. please use your eyes

**Comment by Smug246** [comment]
💀
