### ISSUE TITLE
Add other compilation options

### ISSUE THREAD

**Issue by ianbloc** [Smug246/Luna-Grabber#211]
Can you please add different compilation methods? pyinstaller gets flagged and quarantines as soon as its compiled and i dont want to turn windows defender off.
please add cx_freeze with bdist and build_exe

im always open to helping -ianbloc#8652

**Comment by Smug246** [comment]
ik what cxfreeze is but whats bdist and build_exe

**Comment by Smug246** [comment]
i've added cxfreeze you can check out the code if you want and reopen this issue if you think something should be changed
