### ISSUE TITLE
error on other computer 

### ISSUE THREAD

**Issue by oxy1999x** [Smug246/Luna-Grabber#216]
whenever i launch it is say this error 

![thing](https://user-images.githubusercontent.com/130522971/232287171-ac948d37-ac41-4e14-814d-aa6a9f31af9e.jpg)

i know almost nothing about coding so idk what to do

btw this is for the virus thing idk what to call it

**Comment by XeinTDM** [comment]
try pip install requests

**Comment by Smug246** [comment]
what are u using to compile?
