### ISSUE TITLE
not opening 

### ISSUE THREAD

**Issue by MaxicsSoft** [Smug246/Luna-Grabber#218]
**Describe the bug**
When running, it doesn't open.

I tried to run it using cmd and I get this error:

SyntaxError: future feature annotations is not defined

or 
![image](https://user-images.githubusercontent.com/90089112/232307685-645f66ff-c3ec-4fa1-a52f-d5a4379afa80.png)

**Comment by XeinTDM** [comment]
maybe pip install customtkinter==0.3?

**Comment by Smug246** [comment]
you need to download the latest version of python

**Comment by MaxicsSoft** [comment]
It is downloaded

**Comment by MaxicsSoft** [comment]
the latest

**Comment by XeinTDM** [comment]
Try downloading a older version of customtkinter it worked for me

**Comment by Smug246** [comment]
bro not that old. the latest is 5.0.3

**Comment by Smug246** [comment]
![image](https://user-images.githubusercontent.com/99215486/232313266-ef994060-dff9-41dd-9b9c-ed745192ab03.png)
 even on the official customtkinter github they say this
