### ISSUE TITLE
There is no EXE

### ISSUE THREAD

**Issue by MohanadD393** [Smug246/Luna-Grabber#219]
![image](https://user-images.githubusercontent.com/70370989/232314205-7313a126-e067-45ac-bee9-d4784ad5df6c.png)
there is no exe

**Comment by Smug246** [comment]
cxfreeze and pyinstaller are different compilers. they both create .exe but one pyinstaller is a standalone .exe and cxfreeze is basically a full folder

**Comment by MohanadD393** [comment]
Which one should i use?

**Comment by Smug246** [comment]
pyinstaller
