### ISSUE TITLE
run.bat doesnt work

### ISSUE THREAD

**Issue by e5x1** [Smug246/Luna-Grabber#220]
**Describe the bug**
run.bat crashes after i try opening it

**Expected behavior**
i expekted for run.bat to open luna !11

**Screenshots**
https://user-images.githubusercontent.com/130917129/232323976-eaa8a4db-044c-473a-a175-6687c5c05152.mp4

**Comment by Smug246** [comment]
tf does that stuff say i cant read that

**Comment by e5x1** [comment]
im polish so of course you cant understand it

**Comment by Smug246** [comment]
right so would you like to translate it so i can help you

**Comment by vinscripts** [comment]
e5x1 why are you making this harder on smug? disable your antivirus
