### ISSUE TITLE
file corrupted so the info can't be set

### ISSUE THREAD

**Issue by VesperLmao** [Smug246/Luna-Grabber#221]
![image](https://user-images.githubusercontent.com/129661481/232331918-a9ef82e1-1908-4596-8543-d6df9578924c.png)

**Comment by VesperLmao** [comment]
sent*

**Comment by Smug246** [comment]
where did that come from

**Comment by VesperLmao** [comment]
when the person opened the exe file

**Comment by VesperLmao** [comment]
and ran it

**Comment by Smug246** [comment]
what did u compile with

**Comment by VesperLmao** [comment]
pyinstaller

**Comment by Smug246** [comment]
there pc is fucked

**Comment by VesperLmao** [comment]
rip

**Comment by VesperLmao** [comment]
fucked by what?

**Comment by VesperLmao** [comment]
the virus?

**Comment by VesperLmao** [comment]
i tried it in a virtual machine same thing happened

**Comment by Smug246** [comment]
not too sure tbh with you. ill try look into it more

**Comment by Smug246** [comment]
https://stackoverflow.com/questions/61642603/the-file-or-directory-is-corrupted-and-unreadable-on-exe-files-created-from-vs

i read a few articles on stack and reddit and it basically means your disk isnt right. try re build it and put the .exe somewhere else potentially on a different hard drive

**Comment by VesperLmao** [comment]
alr

**Comment by VesperLmao** [comment]
tried doing it aswell same thing happened. imma try other grabbers to see if they work

**Comment by vinscripts** [comment]
vesper idk if your vesperlol but you own vespy if im correct just use it then

**Comment by VesperLmao** [comment]
@vinscripts nah im not the real vesper lmao
@Smug246 other grabbers were shitty 
so ig it's just me

**Comment by vinscripts** [comment]
make one in python its quite simple unless its one a token grabber GUI were you can select them if not use empyrean. Smug246 and Addi00000 both know each other and help each other if not use a basic python one I made.

**Comment by kyan0045** [comment]
i got the same issue
same for the victim i sent it to
