### ISSUE TITLE
When opening it you get a Unhandled Exceptions Error

### ISSUE THREAD

**Issue by thegamerchris444** [Smug246/Luna-Grabber#224]
**Describe the bug**

**To Reproduce**
1. Go to 'make the exe.'
2. Click on 'on the exe'
3. Wait'

**Expected behavior**
Youll get an error saying that modules or smth wasnt found AFTER it already did everything it needed to

**Screenshots**
![image](https://user-images.githubusercontent.com/46802030/232362637-db5cd269-cdec-40c2-9fde-6cd24a58636f.png)
**Additional context**

**Comment by Smug246** [comment]
download latest version. the error means no webhook was added. you must press check webhook after adding one
