### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by FoxxyPancakes** [Smug246/Luna-Grabber#226]
when someone opens it it says:

"the file or directory is corrupted and unreadable"

How Do I Fix this Issue / Bug?

**Comment by Smug246** [comment]
how do you compile it?

**Comment by FoxxyPancakes** [comment]
do you mind if we handle this on discord? it would be easier to explain.

**Comment by FoxxyPancakes** [comment]
Foxxy#2521

**Comment by Smug246** [comment]
say it here or add me smug#6945. im not chasing people down to help them
