### ISSUE TITLE
It wont let me open  builder.pyw

### ISSUE THREAD

**Issue by polol110** [Smug246/Luna-Grabber#230]
It wont let me open python builder.pyw 
![Untitled](https://user-images.githubusercontent.com/119083530/232855176-89bd210c-6b60-47cd-8290-efbc1af2300a.png)

**Comment by ReZOnGithub** [comment]
you ever try pip install customtkinter

**Comment by polol110** [comment]
i already did that

**Comment by Smug246** [comment]
you must have an old version or something

**Comment by polol110** [comment]
how can i get the older version ?

**Comment by Smug246** [comment]
well make sure you have the latest python first then once you've done that delete the old one then reinstall the modules
