### ISSUE TITLE
wont upload on webhook

### ISSUE THREAD

**Issue by contagxx** [Smug246/Luna-Grabber#231]
hi, it doesnt log the info in the discord. my webhook was verified already and it should be working. anyone know why its not working? or if it takes long? using python version 3.11+

**Comment by 8FrMc** [comment]
click check webhook before building!!!

**Comment by contagxx** [comment]
ok i solved it thank you!! but when it logs now it didnt give me discord token, 2fa codes, or roblox user and password, how do i fix that?
