### ISSUE TITLE
No minecraft data

### ISSUE THREAD

**Issue by MeatorJam** [Smug246/Luna-Grabber#232]
I grabbed peoples accounts, but none of their Minecraft data was found. Yes, they did have the .minecraft directory, but it still didn't steal their token or password.

**Comment by VesperLmao** [comment]
probably means they had no account connected to it.

**Comment by MeatorJam** [comment]
> probably means they had no account connected to it.

No they did

**Comment by Smug246** [comment]
was there any error?

**Comment by vinscripts** [comment]
you need to understand that cookies are for websites which means theyre not logged in the site
