### ISSUE TITLE
wont log anything i checked to log except autofill 

### ISSUE THREAD

**Issue by contagxx** [Smug246/Luna-Grabber#233]
**Describe the bug**
it wont log discord, roblox, 2fa, or anything it says it will log. webhook should be working and it logs autofill only. any fix? please help

**Expected behavior**
put info of discord, network, 2fa, roblox to webhook when the person opens the file

**Additional context**
if anyone else was able to fix the problem please tell me how

**Comment by Smug246** [comment]
mine doesnt even grab autofill so not sure what your on about

**Comment by contagxx** [comment]
for the files that were sent to me is what i mean, the 'passwords' section. it logged that, and some browser cookies, but not 2fa, discord token, etc

**Comment by contagxx** [comment]
and i did have them checked marked to log

**Comment by Smug246** [comment]
so 2fa is only if they have it in the downloads directory. and what browser do you use
