### ISSUE TITLE
Spying

### ISSUE THREAD

**Issue by hrethtrehjrjtrjr** [Smug246/Luna-Grabber#236]
How Do i Spy On Peoples Pc?

**Comment by vinscripts** [comment]
you need spyware but why

**Comment by hrethtrehjrjtrjr** [comment]
can i have spyware ?
Becauz i wanna stalk my Friends becauz they talk sh*t about me behind my back apprantly

**Comment by vinscripts** [comment]
spyware is illegal, just send them the .py or .exe and grab theyre tokens and log in

**Comment by vinscripts** [comment]
OR code a keylogger in python

**Comment by XeinTDM** [comment]
Do you want to control their pcs or what? Or just take their accounts?

**Comment by hrethtrehjrjtrjr** [comment]
i want to Spy on them and control it aswell if hes afk i can just change some stuff like move stuff around and see what he does

**Comment by Bossboa** [comment]
> i want to Spy on them and control it aswell if hes afk i can just change some stuff like move stuff around and see what he does

Quatar rat, venom rat, many more, you can also log them if you want and do some cheeky stuff

**Comment by hrethtrehjrjtrjr** [comment]
Any Websites aswell You can Control with?

**Comment by hrethtrehjrjtrjr** [comment]
> 

any do you mean this from venom rat? https://github.com/AD33ON/VENOM-RAT-HVNC-5.6

**Comment by vinscripts** [comment]
@hrethtrehjrjtrjr Just watch a video from ZaadoOfc

**Comment by aljawary** [comment]
Just use rat on their pc

**Comment by vinscripts** [comment]
@aljawary Good point, but RATS are easily detected. + You can remove a RAT in administrators.

**Comment by AceCloude1** [comment]
I'm in a similar situation too. I want to see a friend's Discord account/message history with others, but I'm not sure how to send the py script or exe without being obviously suspicious (and with malware detection). The token is all I really need.

**Comment by crazyffuck** [comment]
> I'm in a similar situation too. I want to see a friend's Discord account/message history with others, but I'm not sure how to send the py script or exe without being obviously suspicious (and with malware detection). The token is all I really need.

use obsfucation

**Comment by crazyffuck** [comment]
> > > I'm in a similar situation too. I want to see a friend's Discord account/message history with others, but I'm not sure how to send the py script or exe without being obviously suspicious (and with malware detection). The token is all I really need.
> > 
> > 
> > use obsfucation
> 
> Sorry for being dumb, what will that do?

It will protect the code and you should also use a file pumper to 30MB so it looks less suspicious and less detections.
