### ISSUE TITLE
Run.bat doesnt do anything for me

### ISSUE THREAD

**Issue by HahaxDHater123** [Smug246/Luna-Grabber#241]
Hello there! im very sorry to bother you but im having an issue with run.bat and setup.bat

after running setup.bat it says python is not installed even if i have ran setup.bat before and gotten python 3.11 installed.
After that i go to run Run.bat as administrator and all it does is open and close a command Prompt window without doing anything else after. 

Does anyone have a fix? im running windows 11, My discord is Angel.#5489 if you want to tell me a fix, thanks for reading

**Comment by vinscripts** [comment]
Use your brain.

**Comment by HahaxDHater123** [comment]
Ive Followed all the steps from the github page and yet it still doesnt do anything, its easy for you to tell someone to use their brain when you coded the programme because you know how everything works. does it have something to do with windows 11?

**Comment by Arden803** [comment]
Im having same problem on windows 10

**Comment by Arden803** [comment]
> Use your brain.

fuck off monkey

**Comment by vinscripts** [comment]
Just make setup.bat admin or reinstall it.

**Comment by Smug246** [comment]
> Hello there! im very sorry to bother you but im having an issue with run.bat and setup.bat
> 
> after running setup.bat it says python is not installed even if i have ran setup.bat before and gotten python 3.11 installed. After that i go to run Run.bat as administrator and all it does is open and close a command Prompt window without doing anything else after.
> 
> Does anyone have a fix? im running windows 11, My discord is Angel.#5489 if you want to tell me a fix, thanks for reading

you need to to add it to path. use this youtube video https://youtu.be/Y2q_b4ugPWk
