### ISSUE TITLE
where do i find the .exe file

### ISSUE THREAD

**Issue by ManxKing123** [Smug246/Luna-Grabber#242]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by vinscripts** [comment]
Bro, Watch a Tutorial from other youtubers like ZaadoOfc or something.

**Comment by Eromero121212** [comment]
dude just read its in the same folder as the builder and stuff

**Comment by Smug246** [comment]
if you compiled with pyinstaller it will just be in the directory with the name you gave it and if you compiled with cxfreeze it will be in the build directory
