### ISSUE TITLE
does anyone else get the data or is it just you

### ISSUE THREAD

**Issue by txrtan** [Smug246/Luna-Grabber#243]
does luna itself take my data because i accidentally ran the exe file

**Comment by vinscripts** [comment]
Luna is OPS (OPEN-SOURCE) so only the owner of the webhook you used gets the Info. Tip: Many C#, C++ Or C grabbers are dual hooked or obfuscated. Most Python Grabbers like Luna or Empyrean are safe.

**Comment by Smug246** [comment]
just you mate
