### ISSUE TITLE
How does injection work

### ISSUE THREAD

**Issue by MeatorJam** [Smug246/Luna-Grabber#247]
Hi, I'm wondering how the injection works? Is it if they still have the file on their computer?

**Comment by vinscripts** [comment]
it leaves a .py file in discord app data OR it injects the generated malware in the discord.

**Comment by Smug246** [comment]
@MeatorJam @vinscripts it works by injecting a js script into the discord files which basically allows it so when the person who recieves the injection. whenever they change their password it will take what they changed the password to and send it to you

**Comment by MeatorJam** [comment]
> @MeatorJam @vinscripts it works by injecting a js script into the discord files which basically allows it so when the person who recieves the injection. whenever they change their password it will take what they changed the password to and send it to you

What's the directory?

**Comment by crazyffuck** [comment]
> > @MeatorJam @vinscripts it works by injecting a js script into the discord files which basically allows it so when the person who recieves the injection. whenever they change their password it will take what they changed the password to and send it to you
> 
> What's the directory?

https://github.com/Smug246/luna-injection
