### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by V-erg** [Smug246/Luna-Grabber#250]
When I click build, I get this error in the command prompt:
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by crazyffuck** [comment]
use the builder with no cmd not runbat

**Comment by V-erg** [comment]
sorry i didnt specify more. the GUI opened successfully, and i slected cxfreeze file type and just 'system info' and 'discord info' as option.
i got the error 'FileNotFoundError: [WinError 2] The system cannot find the file specified' after clicking Build.

**Comment by V-erg** [comment]
Fixed it. Thanks smug!!
