### ISSUE TITLE
I have a issue

### ISSUE THREAD

**Issue by 12345Radu12345** [Smug246/Luna-Grabber#252]
**Describe the bug**

**To Reproduce**
1. Go to `the zip file, extract the files.'
2. Click on 'setup.bat & then run as administrator the run.bat file. '
3. The GUI does not appears.
4. See error - I do not get any errors

**Expected behavior**

**Screenshots**

**Additional context**
When I installed the file, my anti-virus (avast) detected it as a Trojan.

**Comment by Smug246** [comment]
try to open builder.pyw in the cmd

**Comment by Smug246** [comment]
np
