### ISSUE TITLE
startup issue

### ISSUE THREAD

**Issue by prestine-jemar** [Smug246/Luna-Grabber#253]
**Describe the bug**
an error that pops up when opening the built file (doesnt log anything btw)

**To Reproduce**
1. make a .exe
2. open it
3. error occurs

**Expected behavior**
its expected to open, close, then log all of the info

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://cdn.discordapp.com/attachments/1099943746017169501/1100030156292227194/image.png)

**Additional context**

**Comment by Smug246** [comment]
well what is the error. i cant help if you dont give me it

**Comment by prestine-jemar** [comment]
i sent a screenshot, but ill type it out rq

C:\users\fokus\downloads\Luna-Grabber-main (1)\Luna-Grabber-main\fokustest2.exe

The file or directory is currupted and unreadable


or sometimes, it says "failed to load module"  (this is only with .py files)

**Comment by Smug246** [comment]
did you compile with cxfreeze. if you don't know how to use it i recommend pyinstaller
