### ISSUE TITLE
is can not make the file

### ISSUE THREAD

**Issue by MrFlexiBoi** [Smug246/Luna-Grabber#254]
it say's  "C:\Users\Toben\Downloads\Luna-Grabber-main\Luna-Grabber-main\builder.pyw", line 400, in get_config
    raise Exception("Could not find config in luna.py")
Exception: Could not find config in luna.py what shuld i do

**Comment by Smug246** [comment]
show me the folder. you should have a luna.py file in there. if not download everything again

**Comment by MrFlexiBoi** [comment]
ok thanks
