### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Capo1337** [Smug246/Luna-Grabber#256]
https://prnt.sc/zx1Jc06tiNf0
The file or directory is corrupted and unreadable

**Comment by Smug246** [comment]
ive seen this but i dont actually know what this error means. have a look on stackoverflow and see

**Comment by Smug246** [comment]
what option do you choose to build the file?

**Comment by vahrervert** [comment]
same for me i tried pyinstaller and cxfreeze
