### ISSUE TITLE
setup doesnt setup

### ISSUE THREAD

**Issue by MikkiNikki** [Smug246/Luna-Grabber#259]
Going thru setup installs python and deletes it right after. when i try to do run after that it doesnt have no effect + i cant seem to figure out what the problem with setup is. do u have any ideas what could have caused this and what i can do to fix it?

**Comment by Bl0bzter** [comment]
I have the same issue it just says i dont have python i defently do have it tho and it dont stop saying i need to download python

**Comment by MikkiNikki** [comment]
I found out  how to fix this actually 1 hour ago. so basically what i did was.
1. uninstall python.
2. instead of installing the google version, i then went on to install the microsoft store version (3.11)
3. run setup again and it does what it needs to do (it installs all the reqs)

**Comment by Smug246** [comment]
right ill tell you how to actually fix it. you should not use the microsoft store version. uninstall your current python. then reinstall it from google but make sure you tick a little checkbox that says add to path. then do the setup and it should be all fixed
