### ISSUE TITLE
Error after running .exe

### ISSUE THREAD

**Issue by karim999-wq** [Smug246/Luna-Grabber#260]
![Screenshot (697)](https://user-images.githubusercontent.com/131820693/234415746-b82a1a98-0131-485a-bbf2-2607d8e67d99.png)

after i did all the steps i build my grabber file after it was done i tried to opened it but than this error comes

**Comment by theprospence** [comment]
update the grabber

**Comment by karim999-wq** [comment]
![Screenshot (699)](https://user-images.githubusercontent.com/131820693/234584763-d28bafb8-b64d-4821-a6f6-9068ec43a449.png)

everytime i press "y" to update it it tells me update was succesfully but when i open it again it tells me the same that im not updated to the newest version

**Comment by theprospence** [comment]
then delete the file and reinstall the latest version

**Comment by Smug246** [comment]
factual
