### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by 20LeoiX** [Smug246/Luna-Grabber#264]
How to do .exe because i only have the option .py .pyinstaller and .cfxfrezze

**Comment by Smug246** [comment]
they are both .exe options

**Comment by 20LeoiX** [comment]
> 

When i tried in .py and others it dosent work

**Comment by NOBULLETS** [comment]
its fake you just got your information tooken

**Comment by NOBULLETS** [comment]
i think

**Comment by Smug246** [comment]
> i think

ur so dumb
