### ISSUE TITLE
grabber is broke

### ISSUE THREAD

**Issue by Tixmachine** [Smug246/Luna-Grabber#274]
Basically when they run the grabber it comes up with this sort of thing  
![image](https://user-images.githubusercontent.com/132199636/235621312-57a1c772-797f-43e3-b724-eb3d5b9d7516.png)
i dont know why this is happening but it should be fixed very soon.

**Comment by Smug246** [comment]
paste the full error.

**Comment by Smug246** [comment]
oh wait you didn't add a webhook. when you paste in a webhook you must press check webhook

**Comment by Tixmachine** [comment]
i did and it did not work

**Comment by Smug246** [comment]
that error specifically means that you haven't

**Comment by Smug246** [comment]
A lot of people are getting this error: ```Invalid URL "None`: No scheme supplied. Perhaps you meant https://...```

This error will appear when a webhook is not added. To ensure you add your webhook to a file you must press check webhook after pasting your webhook otherwise it will not work.
