### ISSUE TITLE
grabber dont grab

### ISSUE THREAD

**Issue by zavv0001** [Smug246/Luna-Grabber#275]
i tested the grabber on my pc first, when i open the file it gives an error when i dont have error on. And then it sends nothing to the webhook. And if i do it in .py it gives a error opens fast then closes fast

**Comment by Smug246** [comment]
if you dont give me an error i cant help

**Comment by NOBULLETS** [comment]
its fake lol

**Comment by zavv0001** [comment]
It is, Does it steal my tokens?

**Comment by Smug246** [comment]
mf what's ur error
