### ISSUE TITLE
cxfreeze not working

### ISSUE THREAD

**Issue by lolmannb** [Smug246/Luna-Grabber#279]
When i try to use cxfreeze on my victins then it wont work. I also tried it on my own Computer but it doesnt work. Its really a sgane because the only way to send a file that isnt detected isnt working. When i try to open it up it doesnt work and IT Shows a error which says it cant be opened.

**Comment by Smug246** [comment]
if you dont send an error i cant help you

**Comment by lolmannb** [comment]
There isnt any error message i can create send IT and open i just dont get
the information even when i create a webhook

Smug ***@***.***> schrieb am Mi., 3. Mai 2023, 22:15:
