### ISSUE TITLE
stupid accusation

### ISSUE THREAD

**Issue by NOBULLETS** [Smug246/Luna-Grabber#280]
LMFAOOOO YOU DELETED MY COMMENTS BECAUSE YOU DIDN"T WANT THEM TO KNOW IT IS FAKE LOL PEOPLE DON'T DOWNLOAD THIS STUFF ITS FAKE LOLLLLLLLLLLLLLL

**Comment by Smug246** [comment]
how is this fake? give me any reasons. just because your dumb af and cant read code

**Comment by NOBULLETS** [comment]
Nah this is fake dumbass because you kept closing my fucking issues and i been telling people that this is fake that how ik this thing is fucking fake dumbass

**Comment by Smug246** [comment]
i'm not sure why ur so angry or why u think this is fake but i'm blocking you now
