### ISSUE TITLE
Setup isnt working ig

### ISSUE THREAD

**Issue by Agent47esa** [Smug246/Luna-Grabber#289]
When im opening setup it crashes without reason I got python so idk why

![Adnotacja 2023-05-07 180422](https://user-images.githubusercontent.com/132837250/236688909-c18d8872-5b15-424b-8464-5c81d3a390e3.png)

**Comment by Smug246** [comment]
what does that say in english

**Comment by Agent47esa** [comment]
> what does that say in english

"System can't find right path" or smth like that

**Comment by Smug246** [comment]
download python manually and add it to path
