### ISSUE TITLE
setup bug again

### ISSUE THREAD

**Issue by Agent47esa** [Smug246/Luna-Grabber#294]
**Describe the bug**
When im opening setup its downloading python after few seconds it adds python and deletes it instantly

![Adnotacja 2023-05-08 124912](https://user-images.githubusercontent.com/132837250/236805375-ff8c2fe7-1956-4531-b815-985a7880ee81.png)

**Comment by Smug246** [comment]
that's not a bug. just open the run.bat

**Comment by Agent47esa** [comment]
> that's not a bug. just open the run.bat

yeah and when im doing it nothing happens run just crashes and luna doesnt open

**Comment by Agent47esa** [comment]
> that's not a bug. just open the run.bat
i fixed it tysm but i have question is there exe

**Comment by Smug246** [comment]
what option did u choose to build?
