### ISSUE TITLE
Does not grab discord token and info on windows 11

### ISSUE THREAD

**Issue by maskgaming** [Smug246/Luna-Grabber#296]
it give this error to victim of windows 
<img width="254" alt="Screenshot 2023-05-08 165931" src="https://user-images.githubusercontent.com/104291988/236829155-dcdfe2a9-cf89-484b-b689-645de797fddb.png">
11

**Comment by maskgaming** [comment]
why not reply on my one

**Comment by Smug246** [comment]
im fixing this error

**Comment by Smug246** [comment]
latest version
