### ISSUE TITLE
Uhh so Ye YOu might think I'm stupid but I don't get it

### ISSUE THREAD

**Issue by VitoOnCrack** [Smug246/Luna-Grabber#303]
basically i dont sit on github issues all day like a sad person and do things with my life so thats why. if you want to see the error your getting you will need to run the file in the cmd of the directory.

you do this by first pressing to the right of the folder path as shown below
![image](https://github.com/Smug246/Luna-Grabber/assets/99215486/0cac8fe7-5541-4a0e-a621-f624bf6e0673)

then when it highlights blue
![image](https://github.com/Smug246/Luna-Grabber/assets/99215486/71e0686f-c488-4c1d-8ee5-8a804763c6f8)

you need to type cmd and press enter and a terminal will pop up
![image](https://github.com/Smug246/Luna-Grabber/assets/99215486/7c13e2aa-7f55-40b9-94ea-2dec2612ba0c)

then to run the .bat file of your choice type start <filename.bat> then press enter
![image](https://github.com/Smug246/Luna-Grabber/assets/99215486/acf7c053-6623-4981-ab00-f50817982cf7)

and the error will not disappear and you can send it here

_Originally posted by @Smug246 in https://github.com/Smug246/Luna-Grabber/issues/299#issuecomment-1542452589_

**Comment by VitoOnCrack** [comment]
Also srry for being unpatient + srry for being stupid

**Comment by Smug246** [comment]
look it up
