### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ollaj\\OneDrive\\Desktop\\Luna-Grabber-main\\luna.py

### ISSUE THREAD

**Issue by Olla44** [Smug246/Luna-Grabber#304]
when i press build i get this FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ollaj\\OneDrive\\Desktop\\Luna-Grabber-main\\luna.py

**Comment by Smug246** [comment]
is there no luna.py in ur directory?
