### ISSUE TITLE
make luna grabber logout the discord to get discord pass

### ISSUE THREAD

**Issue by maskgaming** [Smug246/Luna-Grabber#305]
If person run that file then his discord will get logout automatically so that when he login again then we will able to get the password

**Comment by Smug246** [comment]
so close discord?

**Comment by maskgaming** [comment]
i mean
if the script makes the victim discord logout from his device when he runs the .exe file then the victim will try to login into his account which will help to get his discord password

**Comment by Smug246** [comment]
ill look into it but possibly could do
