### ISSUE TITLE
Fake login or loadind screan

### ISSUE THREAD

**Issue by CyBerFeNix-dev** [Smug246/Luna-Grabber#307]
i say we need fake login or loading screen when victim clicks on exe file  to make a bit more real and let some how bypass Windows defender  or antivirus 

like if we got a login screen 
Username =
Password = 
Login key = 

for username and  password just bypass  nothing 
but when  entering a login key like  54586894 
console shows ``connected successful `` or ``logged in  ``
exe is activated and running as selected in builder  

if we got loading screen 
when victim click exe it shows a loading bar  and after loaded to 100% 
console shows successful loaded  

and maybe let builder make a better exe file like something game install exe files or something like that

**Comment by Smug246** [comment]
maybe

**Comment by LocalSmail** [comment]
Just make it your self using tkinter. Not hard 😂

**Comment by CyBerFeNix-dev** [comment]
Yo do you accept costume request?

2023-06-19, pr 00:49, Smug ***@***.***> rašė:

**Comment by Smug246** [comment]
ye join my server n add me n we can talk

**Comment by CyBerFeNix-dev** [comment]
Can you send me a link. And btw its same person where we talked before on
discord CyBerFeNix

2023-06-21, tr 01:10, Smug ***@***.***> rašė:

**Comment by Smug246** [comment]
https://discord.gg/utmcmgHX
