### ISSUE TITLE
COOKIES

### ISSUE THREAD

**Issue by Jamesnocapper** [Smug246/Luna-Grabber#309]
I have no idea what to do with the cookies.txt I got, it's a bunch of true false code, how do you even use that info

**Comment by Smug246** [comment]
edit cookies. use google

**Comment by Jamesnocapper** [comment]
not those, I dont understand, it's a bunch of random code

**Comment by Smug246** [comment]
its just a netscape format so you can import it into a browser such as firefox

**Comment by Jamesnocapper** [comment]
can you give me some step idk how after searching

**Comment by theprospence** [comment]
autistic kid just go to inspect element and look up the Roblox cookie and replace it with the one that u have
