### ISSUE TITLE
the system cannot execute the specified program

### ISSUE THREAD

**Issue by DaZoZElMoz** [Smug246/Luna-Grabber#311]
**Describe the bug**
clear and simple the system cannot execute the specified program
**To Reproduce**
1. Go to 'the folder '
2. Click on '...run bat and start bat both same error'

**Expected behavior**
work
**Screenshots**
![image](https://github.com/Smug246/Luna-Grabber/assets/124311096/052b48e7-a8c7-4b25-b88a-bae01c480b48)

**Additional context**

**Comment by Smug246** [comment]
try run it as admin
