### ISSUE TITLE
There is no .exe

### ISSUE THREAD

**Issue by Frz00** [Smug246/Luna-Grabber#314]
When i run the .bat file and choose the options everything is okay. but i only can choose: .py  cxfreeze  pyinstaller and there is no .exe 
when i choose pyintaller and cxfreeze and .py and select build this the error: 

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\IHC\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\IHC\AppData\Local\Programs\Python\Python310\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 553, in _clicked
    self._command()
  File "C:\Users\IHC\Desktop\Luna-Grabber-main\builder.pyw", line 520, in buildfile
    self.write_and_obfuscate(filename)
  File "C:\Users\IHC\Desktop\Luna-Grabber-main\builder.pyw", line 500, in write_and_obfuscate
    f.write(self.get_config())
  File "C:\Users\IHC\Desktop\Luna-Grabber-main\builder.pyw", line 405, in get_config
    with open(self.basefilepath + "\\luna.py", 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\IHC\\Desktop\\Luna-Grabber-main\\luna.py'

and there is a .py file in folder and when i click on it it doesnt work.

**Comment by Smug246** [comment]
so is the luna.py file there? if it is can you send me the directory your currently in so i can compare it to this `C:\Users\IHC\Desktop\Luna-Grabber-main\luna.py`

**Comment by Smug246** [comment]
that was a question what I said before. in the folder is there a luna.py file?

**Comment by LocalSmail** [comment]
If you look at the bottom it says the error. Aka: Invalid Argument
> Same for me. `.exe` is not showing up (idk if u removed `.exe` or...) and I'm getting the same error:
> 
> 
> 
> ```C:\Users\crypt\OneDrive\Desktop\Stuff\Code\Discord\Hck\Luna-Grabber>python builder.pyw
> 
> Exception in Tkinter callback
> 
> Traceback (most recent call last):
> 
>   File "C:\Users\crypt\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1885, in __call__
> 
>     return self.func(*args)
> 
>   File "C:\Users\crypt\AppData\Local\Programs\Python\Python39\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 553, in _clicked
> 
>     self._command()
> 
>   File "C:\Users\crypt\OneDrive\Desktop\Stuff\Code\Discord\Hck\Luna-Grabber\builder.pyw", line 518, in buildfile
> 
>     self.write_and_obfuscate(filename)
> 
>   File "C:\Users\crypt\OneDrive\Desktop\Stuff\Code\Discord\Hck\Luna-Grabber\builder.pyw", line 498, in write_and_obfuscate
> 
>     f.write(self.get_config())
> 
>   File "C:\Users\crypt\OneDrive\Desktop\Stuff\Code\Discord\Hck\Luna-Grabber\builder.pyw", line 405, in get_config
> 
>     with open(self.basefilepath + "\\luna.py", 'r', encoding="utf-8") as f:
> 
> OSError: [Errno 22] Invalid argument: 'C:\\Users\\nemit\\OneDrive\\Desktop\\Stuff\\Code\\Discord\\Hck\\Luna-Grabber\\luna.py'
> 
> ```
> 
> 
> 
> pls help, and love ur work smug!

**Comment by Cryptic1526** [comment]
Okay, so I did it again, and it works, but .exe is still not visible in the drop-down. Other than that, it works fine. Do you I have to install something extra to make it a .exe file?
Cheers

**Comment by Smug246** [comment]
pyinstaller is a compiler, the .exe should just be in the directory somewhere. if ur using cxfreeze the .exe will be in the build file
