### ISSUE TITLE
Add To Startup doesnt works

### ISSUE THREAD

**Issue by xatss** [Smug246/Luna-Grabber#322]
my victim installed the exe  but if he turns his pc again on   i dont get a new webhook.

**Comment by theprospence** [comment]
you have to put on injection on

**Comment by xatss** [comment]
> you have to put on injection on

ik    i did it too       where can I get the new information? in the zip file?

**Comment by theprospence** [comment]
huh

**Comment by theprospence** [comment]
u click on the exe file
