### ISSUE TITLE
i dont get a webhook

### ISSUE THREAD

**Issue by xatss** [Smug246/Luna-Grabber#324]
when the victims press my exe they get a fake error but i don't get a webhook.   if i grab myself i dont get a webhook  info 

a guy destroyed  my webhook  and he knows my ascii.   since he did something, the webhook doesn't work, neither does a new webhook.   please help   my discord is  Yassin#5947  
![image](https://github.com/Smug246/Luna-Grabber/assets/131300763/5b3fb20c-1de2-474f-8a39-5b51ded66369)

**Comment by xatss** [comment]
and luna doesnt works too

**Comment by theprospence** [comment]
Did you update luna if not redownload it. Also, make sure you have latest version of pyinstaller and try latest update

**Comment by xatss** [comment]
> Did you update luna if not redownload it. Also, make sure you have latest version of pyinstaller and try latest
