### ISSUE TITLE
STOP USING PASTE SERVICE

### ISSUE THREAD

**Issue by Blank-c** [Smug246/Luna-Grabber#326]
Stop using https://paste-pgpj.onrender.com.
I know the site is open source. But who knows if it really is.
I'd recommend you to remove the copy option.
Besides I don't think there is any need for that.

**Comment by Smug246** [comment]
lmao okay

**Comment by Blank-c** [comment]
Didn't mean to use the caps but Ig its ok...

**Comment by Smug246** [comment]
ye ill remove it
