### ISSUE TITLE
for some reason when i try and log someone i dont get a message from the webhook

### ISSUE THREAD

**Issue by aaxxdf3** [Smug246/Luna-Grabber#333]
for some reason when i try and log someone the webhook doesnt send a message

**Comment by Smug246** [comment]
is there any sort of error and are u sure there av isnt blocking it

**Comment by Cryptic1526** [comment]
Same issue here, the only error is this
```
Traceback (most recent call last):
  File "plswork.py", line 1, in <module>
  File "<string>", line 4, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 17, in <module>
ModuleNotFoundError: No module named 'Crypto'
```
But that's the fake error I think.
My Windows Security isn't picking anything up, even if I directly scan the file, and Defender didn't block it.
The webhook is valid

Pls help

**Comment by Smug246** [comment]
run these commands then rebuild it. 

`
pip uninstall crypto 
pip uninstall pycrypto 
pip install pycryptodome`
