### ISSUE TITLE
unhandled exeption in script

### ISSUE THREAD

**Issue by Logan222nnn** [Smug246/Luna-Grabber#334]
Traceback (most recent call last):
  File "squishi.py", line 1, in <module>
  File "<string>", line 4, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 17, in <module>
ModuleNotFoundError: No module named 'Crypto'

**Comment by lordcrazyoflife2** [comment]
> Traceback (most recent call last):
> 
>   File "squishi.py", line 1, in <module>
> 
>   File "<string>", line 4, in <module>
> 
>   File "<string>", line 1, in <module>
> 
>   File "<string>", line 17, in <module>
> 
> ModuleNotFoundError: No module named 'Crypto'
> 
> 
> 
> 

I'm also getting the same issue lol

**Comment by Chrizzy420** [comment]
Im getting the same issue, "No module named 'Crypto'"

**Comment by MICHELE-001x** [comment]
I'm also getting the same issue :D

**Comment by Smug246** [comment]
download latest version
