### ISSUE TITLE
it is blocked by microsoft defender

### ISSUE THREAD

**Issue by fuggx** [Smug246/Luna-Grabber#338]
it is blocked by microsoft defender, despite having checked "disable defender", how to solve it?

**Comment by Smug246** [comment]
ye im aware. it used to not get detected but does now cause so many use it

**Comment by Blank-c** [comment]
> it is blocked by microsoft defender, despite having checked "disable defender", how to solve it?

Windows defender comes with tamper protection setting. If it is enabled on the target PC, the disable defender cmd won't work.
