### ISSUE TITLE
No module named 'crypto'

### ISSUE THREAD

**Issue by Chrizzy420** [Smug246/Luna-Grabber#339]
**Describe the bug**
When I build the grabber (this error persists with both pyinstaller, and cxfreeze) I get an error saying this:

Traceback (most recent call last):
File "test.py", line 1, in
File "", line 4, in
File "", line 1, in
File "", line 17, in
ModuleNotFoundError: No module named 'Crypto'

**To Reproduce**
1. Go to the builder
2. Click on check on the options you want
3. Scroll down to build
4. Open the rat, and then error, doesn't matter if your av is turned on or off

**Expected behavior**
I expected the rat to open and close instantly without any errors, and then send info from the pc to my webhook

**Screenshots**
Dont got any rn

**Additional context**

**Comment by xatss** [comment]
for me too

**Comment by Smug246** [comment]
This is caused because there are different crypto packages that install under the same folder. run these commands try to build it after and let me know if it works or not.

`pip uninstall crypto`
`pip uninstall pycrypto`
`pip3 install pycryptodome`

**Comment by clapzqt** [comment]
im have the same issue, running the following commands is not helping

**Comment by jay171717** [comment]
yes he is right... the issue still hasnt fixed the problem
I recommend you to look in...

**Comment by Smug246** [comment]
do you guys have the latest version. it should've 1.5.3. go to the tools folder then open update.py so you can view it and it will say

**Comment by xatss** [comment]
> do you guys have the latest version. it should've 1.5.3. go to the tools folder then open update.py so you can view it and it will say

yes its 1.5.3.

**Comment by Smug246** [comment]
what do u compile with
