### ISSUE TITLE
How to set the Python path to the thing...

### ISSUE THREAD

**Issue by jay171717** [Smug246/Luna-Grabber#342]
[UPDATE] My issue has been fixed. I searched on yt abt the path and now its fixed

I have installed the python 3.11.0 but idk how to add the path to the thing
I opened the "setup.bat" it says that python is not installed... Installing.... 
after few time it just closes and when i open the "run.bat" it just opens and instantly closes....

I think that the python path is the problem here
i just dont know how to access it and where to put the path to
(btw it also shows the python logo in the "luna.py" and "builder.pyw")

**Comment by jay171717** [comment]
i am sorry for the "label" as its not a bug and idk how to change it to "question"

**Comment by KDot227** [comment]
> [UPDATE] My issue has been fixed. I searched on yt abt the path and now its fixed
> 
> I have installed the python 3.11.0 but idk how to add the path to the thing I opened the "setup.bat" it says that python is not installed... Installing.... after few time it just closes and when i open the "run.bat" it just opens and instantly closes....
> 
> I think that the python path is the problem here i just dont know how to access it and where to put the path to (btw it also shows the python logo in the "luna.py" and "builder.pyw")

google how to add python to path

**Comment by KDot227** [comment]
![python_path](https://github.com/Smug246/Luna-Grabber/assets/110929758/169a0dd9-e70b-43ba-bdf5-6753dcee22c2)

**Comment by Smug246** [comment]
what he said
