### ISSUE TITLE
screen shot cmds

### ISSUE THREAD

**Issue by zaloid** [Smug246/Luna-Grabber#346]
could you add like a cmd for taking screenshots for a specific user i logged ? like .ss {target user} or something ? it would really be very useful, thank you for reading this request. i hope u add it !

**Comment by KDot227** [comment]
> could you add like a cmd for taking screenshots for a specific user i logged ? like .ss {target user} or something ? it would really be very useful, thank you for reading this request. i hope u add it !

this aint a rat lol

**Comment by Smug246** [comment]
ye as kdot said this isnt a rat so no
