### ISSUE TITLE
Stop using a girls language

### ISSUE THREAD

**Issue by Kyxnite** [Smug246/Luna-Grabber#350]
Use a mans language like C# or maybe even C++. Tired of these shitty ass python stealers and javascript stealers LOL

**Comment by Kyxnite** [comment]
btw copying your friends entire source and adding a ui doesnt make you a pro python coder LOL

**Comment by Smug246** [comment]
you code in ruby grow up

**Comment by Kyxnite** [comment]
I dont use github ☠️
