### ISSUE TITLE
Problem after building up

### ISSUE THREAD

**Issue by lovetoseeit** [Smug246/Luna-Grabber#352]
Hello,

After following all instructions, i end up with an error when cliking the .exe

Traceback (most recent call last):
  File "TankUI.py", line 1, in <module>
  File "<string>", line 4, in <module>
  File "<string>", line 1, in <module>
ValueError: bad marshal data (unknown type code)

Just wanted to let you know, if it can help

**Comment by Smug246** [comment]
what options do you choose?

**Comment by Blank-c** [comment]
> Hello,
> 
> After following all instructions, i end up with an error when cliking the .exe
> 
> Traceback (most recent call last): File "TankUI.py", line 1, in File "", line 4, in File "", line 1, in ValueError: bad marshal data (unknown type code)
> 
> Just wanted to let you know, if it can help

It looks like you are using py mode with obfuscation. The obfuscation makes the program version dependent. So it means if you made the program in py mode with obfuscation in Python 3.11. Then the victim must have the same python version to run it.

If you do not want that, then generate the .py file without obfuscation and use your own obfuscation.
