### ISSUE TITLE
No module named Crypto

### ISSUE THREAD

**Issue by Venity40** [Smug246/Luna-Grabber#355]
**Describe the bug**
I didnt see anyone fix this bug? is it an operating system problem?

**To Reproduce**
1.Build an exe
2. execute it

**Expected behavior**
The webhook should send a message

**Screenshots**
![image](https://github.com/Smug246/Luna-Grabber/assets/125585288/ceff5c16-afa9-4524-9cea-e2adad9b9f58)

**Additional context**
The pip install pycryptodome doesnt work

**Comment by Smug246** [comment]
ye so currently if you add obfuscation to pyinstaller it wont recognise the pycryptodome module. im trying to work on this

**Comment by sakurama3960** [comment]
> ye so currently if you add obfuscation to pyinstaller it wont recognise the pycryptodome module. im trying to work on this

Thanks smug for facing this issue.
We, the users, are looking forward to your success and supporting you at the same time!

**Comment by Smug246** [comment]
> > ye so currently if you add obfuscation to pyinstaller it wont recognise the pycryptodome module. im trying to work on this
> 
> Thanks smug for facing this issue. We, the users, are looking forward to your success and supporting you at the same time!

np ive found the bug and have fixed but its also lead to other little bugs which im in the process of cleaning up

**Comment by Smug246** [comment]
download latest version it has everything fixed im pretty sure. let me know if anything buggy
