### ISSUE TITLE
smug im sorry but when i did the thing it has been loading for a hour

### ISSUE THREAD

**Issue by V8LTT** [Smug246/Luna-Grabber#360]
### 

@ #1. > [_**Describe_](url) the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Smug246** [comment]
what u on about

**Comment by V8LTT** [comment]
so when i open it from comand prompt it didnt download anything foe an hour then i closed it my pc is not even slow 
![Capture](https://github.com/Smug246/Luna-Grabber/assets/136298210/4bbfd245-c0c0-4838-9ed2-e4e532844f3b)

**Comment by Smug246** [comment]
you need to download python and add it to path

**Comment by V8LTT** [comment]
i did bro its in my path i watched 3 tutorials and confirmed its python 3.11

**Comment by Smug246** [comment]
did u download it of the official website. not the microsoft store

**Comment by V8LTT** [comment]
yes python.org
