### ISSUE TITLE
Add file-related controlling stuff.

### ISSUE THREAD

**Issue by MeatorJam** [Smug246/Luna-Grabber#361]
I don't know if this is asking too much, (or if you want to because this is a grabber) but can you make it create 3 new channels in your discord server? The first one is info, which you already have, the second one could be recordings, which record what is happening on the PC in 2-minute intervals. The third channel should be the file-related channel, where you can type stuff like .grab passwords, and the webhook would grab their passwords. One of the commands should be .ss, which takes a screenshot of what they are doing right now. The second command should be .show processes, and it shows all the files running on their computer, with numbers next to them showing which one is which (1. Discord.exe, 2. Google.exe, etc.), and it will ask which process you want to kill. Then you will type the number of the process into the channel, then it will end that task. The third command should be .ls, which should list all your directories, and you should be able to type .download [file_name], and it will download that file. The fourth command should be .upload single, and it will ask which file you want to upload. Then you should drag the file into the chat and it will upload it into the [this_pc] directory. That's all, and I really hope you want to add this.

**Comment by Smug246** [comment]
sorry but no thats a rat. i am thinking of creating a rat soon though

**Comment by MeatorJam** [comment]
> sorry but no thats a rat. i am thinking of creating a rat soon though

Ok sure, but please let me know when you do it. (If you do it)
