### ISSUE TITLE
need help running builder

### ISSUE THREAD

**Issue by Ashton5920** [Smug246/Luna-Grabber#370]
whenever i try to run the builder it is selected to run as notepad and i do not know what to do 

![Screenshot 2023-06-19 205519](https://github.com/Smug246/Luna-Grabber/assets/137127128/4cb81fc4-be66-41b7-a86d-9d217950267e)

**Comment by Opensitoo** [comment]
try to running this with cmd 
command: python3 builder.pyw

**Comment by Ashton5920** [comment]
> try to running this with cmd command: python3 builder.pyw

![image](https://github.com/Smug246/Luna-Grabber/assets/137127128/a64deaf9-08d2-4619-aae7-f20bcf5bd263)

**Comment by Ashton5920** [comment]
> try to running this with cmd command: python3 builder.pyw

please help

**Comment by Smug246** [comment]
quite simple, download the latest version of python from [here](https://www.python.org/downloads/) and make sure you tick the box that says add to path 
![image](https://github.com/Smug246/Luna-Grabber/assets/99215486/ef880a80-2a06-4a30-8883-0afa2f4f184d)

**Comment by Ashton5920** [comment]
> python3 builder.pyw

it still says that same thing when i go in cmd also it still opens with notepad

**Comment by Ashton5920** [comment]
> quite simple, download the latest version of python from [here](https://www.python.org/downloads/) and make sure you tick the box that says add to path ![image](https://user-images.githubusercontent.com/99215486/247244736-ef880a80-2a06-4a30-8883-0afa2f4f184d.png)

it still says that same thing when i go in cmd also it still opens with notepad

**Comment by Ashton5920** [comment]
> quite simple, download the latest version of python from [here](https://www.python.org/downloads/) and make sure you tick the box that says add to path ![image](https://user-images.githubusercontent.com/99215486/247244736-ef880a80-2a06-4a30-8883-0afa2f4f184d.png)

help
pls

**Comment by Ashton5920** [comment]
it still says that same thing when i go in cmd also it still opens with
notepad

**Comment by Smug246** [comment]
why dont u right click it and open with python??

**Comment by Ashton5920** [comment]
> why dont u right click it and open with python launcher??

it just closes

**Comment by Ivo911-blip** [comment]
same man i cant get it to run

**Comment by Smug246** [comment]
ashton add me on discord and ill help you. smug1234
