### ISSUE TITLE
error in inicialization

### ISSUE THREAD

**Issue by Opensitoo** [Smug246/Luna-Grabber#371]
to start the program It sends me an error which does not allow me to run 100%
![image](https://github.com/Smug246/Luna-Grabber/assets/91356804/a80b76d1-928e-4e07-9e0b-27b8bf2c5cb0)

**Comment by xoxoa** [comment]
I'm having the same error

**Comment by Smug246** [comment]
what options are u enabling

**Comment by Opensitoo** [comment]
i have this options
![image](https://github.com/Smug246/Luna-Grabber/assets/91356804/8ddcf52b-6b10-45b2-a135-a0ca35bbda01)

**Comment by Smug246** [comment]
what about compiler

**Comment by Opensitoo** [comment]
With the compiler nothing, with the exe of the grabber (outout file), to start de grabber this send me a error ando don't send me a information to webhook

**Comment by Smug246** [comment]
the compiler is the .exe. i mean are you using cxfreeze or pyinstaller

**Comment by Opensitoo** [comment]
sorry for the time, pyinstaller

**Comment by Opensitoo** [comment]
i compile the stealer and now tell me this 
![image](https://github.com/Smug246/Luna-Grabber/assets/91356804/6d5c911d-9701-42fb-a3ba-17b9d3cb75aa)
