### ISSUE TITLE
Access denied? 

### ISSUE THREAD

**Issue by xoxoa** [Smug246/Luna-Grabber#372]
![image](https://github.com/Smug246/Luna-Grabber/assets/126020779/1f60512c-b5ca-4ae5-9c5c-ccca10955076)

It says access denied whenever I try to create any file with obfuscation.

**Comment by Smug246** [comment]
can you show me the luna.log in your luna folder

**Comment by Ashton5920** [comment]
> can you show me the luna.log in your luna folder

do you have discord? can i add you because i need help
