### ISSUE TITLE
Doesnt send the informations

### ISSUE THREAD

**Issue by 12345Radu12345** [Smug246/Luna-Grabber#373]
**To Reproduce**
1. Open the builder
2. Build the grabber
3. Run the grabber
4. Doesnt get the information

 I created the grabber using the builder and then I wanted To test the grabber to see if it will work so I runned the file and nothing happend and I didnt got my informations. Then I wanted to test the grabber on another pc that I had and Met the same problem (I didnt got the informations on the discord server).

**Comment by ToxinNozaki** [comment]
Yo, so did you make sure to click the button beside where you input your webhook? If not, retry it while doing that and it should work.

**Comment by Smug246** [comment]
turn your antivirus off

**Comment by Ashton5920** [comment]
> turn your antivirus off

do you have discord i need help with my builder not working

**Comment by Smug246** [comment]
yes look at my readme profile
