### ISSUE TITLE
cant open builder

### ISSUE THREAD

**Issue by Ashton5920** [Smug246/Luna-Grabber#374]
![image](https://github.com/Smug246/Luna-Grabber/assets/137127128/e06f053c-4e5a-40db-a4e6-13ae5ddee17f)
  

builder opens as notepad and i have python installed in path and i dont know what to open it as and it doesnt work

**Comment by 9pings** [comment]
i cannot even find that file

**Comment by 9pings** [comment]
nvm i found the file but ive never used a .pyw file bro

**Comment by 9pings** [comment]
nvm

**Comment by 9pings** [comment]
goto cmd and type "python builder.pyw"

**Comment by Ashton5920** [comment]
> 

![image](https://github.com/Smug246/Luna-Grabber/assets/137127128/ac1244bb-7ea3-4d1f-9741-5d5476d60514)

**Comment by Smug246** [comment]
get some braincells

**Comment by Ashton5920** [comment]
> 
i moved it into there it still doesnt work just tell me what to do

**Comment by Smug246** [comment]
right click it and press open with python launcher
