### ISSUE TITLE
setup crashing

### ISSUE THREAD

**Issue by JrazAZ2** [Smug246/Luna-Grabber#375]
when i open set up it crashes
i made sure to have python 3.11.4 but whenever i open setup it crashes and builder just does nothing

**Comment by JrazAZ2** [comment]
also builder wont open

**Comment by ajdezz** [comment]
bro same

**Comment by ajdezz** [comment]
ok i  found a way
1. ddownload python 3.11.2 version than downlod it in lunas grabber folder and than click set up

**Comment by Smug246** [comment]
read the debugging pinned issue and it'll show you how to see the error ur getting
