### ISSUE TITLE
i cant open the builder or the bat file

### ISSUE THREAD

**Issue by Ivo911-blip** [Smug246/Luna-Grabber#378]
i cant open the builder and bat file i have tried everything but still nothing opens even though I've done everything right

**Comment by PoldusPhalanx** [comment]
i think its a rat

**Comment by Ivo911-blip** [comment]
y do u say that

**Comment by Ashton5920** [comment]
> ye y, there is a video on yt about this and i have been using this for the past 3 mths.

how did you get it to run

**Comment by Smug246** [comment]
read the debugging pinned issue and it'll show you how to see the error ur getting
