### ISSUE TITLE
not grabbing all stuff

### ISSUE THREAD

**Issue by Luukas101010** [Smug246/Luna-Grabber#379]
when i install it and make a file it will not send the minecraft or the roblox cookies to me im logged in all places but not working all other comes to the webhook i have them selected i have python 3.11 and have installed it already 2 times help

**Comment by 9pings** [comment]
Freeze#9120 In discord lemme try help u

**Comment by Ashton5920** [comment]
> 

add me i need help

**Comment by Smug246** [comment]
read the debugging pinned issue and it'll show you how to see the error ur getting
