### ISSUE TITLE
setup.bat not working

### ISSUE THREAD

**Issue by m-citus** [Smug246/Luna-Grabber#384]
idk whats happening i downloaded all the requirements with pip install -r requirements.txt and then ran the setup.bat but still nothing it just opens and closes instantly

**Comment by Smug246** [comment]
have u downloaded python and added it to path

**Comment by ZerksXDD** [comment]
> have u downloaded python and added it to path

What do you mean "add to path" can you explain in idiot terms

**Comment by Smug246** [comment]
go on youtube and look up how to add python to path i cba to explain it on every issue
