### ISSUE TITLE
not opening

### ISSUE THREAD

**Issue by Helden1pro** [Smug246/Luna-Grabber#393]
When I built it I tried opening it  and nothing happened but when it does open it gives a error code but i dont get anything in my discord

**Comment by Smug246** [comment]
what's the error

**Comment by Helden1pro** [comment]
ok so i got a new error when ever i open the stub i  made it works but when
other people use it it dont work i tried using it on another pc same thing
happened

**Comment by Helden1pro** [comment]
and when i put it on a download website and i download it it say unable
too  load python dll 3

**Comment by Helden1pro** [comment]
got the same error but he aint sayin nun
