### ISSUE TITLE
its amazing but could u add so i can controll their screen and do stuff

### ISSUE THREAD

**Issue by LocalReload** [Smug246/Luna-Grabber#407]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by LocalReload** [comment]
it wont show up discord info or discord password logger nothing about discord or roblox

**Comment by minecraft92a** [comment]
There is no reason to add that to Luna Because Luna is an logger not an RAT

**Comment by Smug246** [comment]
well said
