### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by KIRB00** [Smug246/Luna-Grabber#411]
Hi, i know you dont sit here all day but it would be awesome to have an tutorial as i have been making lot of different files but none seem to work. When i download them windows defender blocks them no matter what i do and even tho i get to bypass the defender it just runs for a second and doesnt give me my own info.

It just doesnt seem to work no matter what you do, please someone help me if you can make it work

**Comment by Smug246** [comment]
^^^^^^^

**Comment by lunagrabdeeznuts** [comment]
yo smug setup.bat doesnt work run wont show up
