### ISSUE TITLE
i did everything it asked...

### ISSUE THREAD

**Issue by BraydinB** [Smug246/Luna-Grabber#414]
[builder.pyw:603] - 2023-07-12 03:38:43,788 - ERROR - File must be run with admin privileges im unsure of how to fix that, also when i downloaded the files i noticed there wasnt any zip to extract. pls help

**Comment by FakeAltF4** [comment]
> [builder.pyw:603] - 2023-07-12 03:38:43,788 - ERROR - File must be run with admin privileges im unsure of how to fix that, also when i downloaded the files i noticed there wasnt any zip to extract. pls help

Try to disable your antivirus and redownload the zip, once done extract it, if it asks for admin priviledges, right click > run as administrator.

**Comment by BraydinB** [comment]
> > [builder.pyw:603] - 2023-07-12 03:38:43,788 - ERROR - File must be run with admin privileges im unsure of how to fix that, also when i downloaded the files i noticed there wasnt any zip to extract. pls help
> 
> Try to disable your antivirus and redownload the zip, once done extract it, if it asks for admin priviledges, right click > run as administrator.
what zip, i downloaded all the files and theres no zip
