### ISSUE TITLE
Remote desktop

### ISSUE THREAD

**Issue by Nitrozena** [Smug246/Luna-Grabber#415]
How about adding an option that enebles remote desktop and the grabber grabs the name and pass for it?

**Comment by BadBadBoss** [comment]
@Smug246 waht is your discord/tele

**Comment by Smug246** [comment]
> How about adding an option that enebles remote desktop and the grabber grabs the name and pass for it?

not adding any rat options

**Comment by Smug246** [comment]
> @Smug246 waht is your discord/tele

smug#7213

**Comment by Nitrozena** [comment]
> > How about adding an option that enebles remote desktop and the grabber grabs the name and pass for it?
> 
> not adding any rat options

aight
