### ISSUE TITLE
Cannot run builder.pyw

### ISSUE THREAD

**Issue by ManagKagi** [Smug246/Luna-Grabber#417]
**Describe the bug**
I open start.bat, it tells me to run run.bat (builder.pyw) but when I open, nothing happens; no error- nothing. I tried before and it worked I dont know why it isnt working now 

**Expected behavior**
The UI to open when I opened builder.pyw

**Additional context**
I have python 3.11 in my path and I think I have all the requirements to run it.

**Comment by ManagKagi** [comment]
For any people expericencing t

**Comment by Smug246** [comment]
#299

**Comment by Trap6666** [comment]
Same to me. Smug can you help?

**Comment by sharkfan824** [comment]
@Smug246 i need help this issue is happening to me to
