### ISSUE TITLE
whenever i open the dangerous file to test it nothing happens (no message on the discord) and the webhook is valid

### ISSUE THREAD

**Issue by Go-bed** [Smug246/Luna-Grabber#420]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Trap6666** [comment]
Same to me.

**Comment by Smug246** [comment]
is ur av off

**Comment by REALLEGIT12** [comment]
> is ur av off

whats a AV? because i have the same problem

**Comment by Smug246** [comment]
anti virus. you should turn it off

**Comment by l3qso** [comment]
same bruh
