### ISSUE TITLE
GUYS DONT DOWNLOAD LOOK

### ISSUE THREAD

**Issue by Bloopy365** [Smug246/Luna-Grabber#421]
![image](https://github.com/Smug246/Luna-Grabber/assets/135502033/c5d67b84-6056-4502-815f-18d7825966b7)

HE GOT MY INFO

**Comment by furax124** [comment]
> ![image](https://user-images.githubusercontent.com/135502033/253768087-c5d67b84-6056-4502-815f-18d7825966b7.png)
> 
> HE GOT MY INFO

how you know that ?

when you open builder or execute the grabber ?

**Comment by Bloopy365** [comment]
> > ![image](https://user-images.githubusercontent.com/135502033/253768087-c5d67b84-6056-4502-815f-18d7825966b7.png)
> > HE GOT MY INFO
> 
> how you know that ?
> 
> when you open builder or execute the grabber ?

builder

**Comment by Smug246** [comment]
jesus u guys are dumb

**Comment by Bloopy365** [comment]
> jesus u guys are dumb

why?

**Comment by Smug246** [comment]
so let me guess u built a file. opened it and then that happened. that's you logging yourself. the code is completely open source so you can check all of it for a dualhook

**Comment by Bloopy365** [comment]
> so let me guess u built a file. opened it and then that happened. that's you logging yourself. the code is completely open source so you can check all of it for a dualhook

i dindt got any file

**Comment by Smug246** [comment]
mate that was 2 months ago u obviously did

**Comment by Smug246** [comment]
or u got logged by luna due to someone else ages ago
