### ISSUE TITLE
im opening setup file and it says everything was setup and to run run.bat but i dont see run.bat i redownload it and extracted and everything and stilld oesnt show run.bat so it wqont let me open builder so how can i fix this

### ISSUE THREAD

**Issue by manuelr22** [Smug246/Luna-Grabber#423]
im opening setup file and it says everything was setup and to run run.bat but i dont see run.bat i redownload it and extracted and everything and stilld oesnt show run.bat so it wqont let me open builder so how can i fix this

**Comment by Trap6666** [comment]
You need to open builder. Not run.bat

**Comment by lunagrabdeeznuts** [comment]
wheres that

**Comment by lunagrabdeeznuts** [comment]
when i open nothing happends
