### ISSUE TITLE
stopped working

### ISSUE THREAD

**Issue by yopiyepi** [Smug246/Luna-Grabber#426]
a couple of weeks ago I created a stiller, and it worked, the data came to discord, but after checking now nothing comes, and I did not change the webhook, the discord channel is the same. Now, when I run the executable, the browser and discord are disabled (which probably means everything is working), but the data is not coming to the discord itself

**Comment by Smug246** [comment]
did the webhook get deleted?

**Comment by Psychenginehelper** [comment]
try reinstalling luna grabber from the setup.bat file and then click run again
