### ISSUE TITLE
ez detected by virus total just change Win.32.Torjan-Stealer.LunaGrabber or anything else to something else

### ISSUE THREAD

**Issue by vincyxiroff** [Smug246/Luna-Grabber#427]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Smug246** [comment]
what

**Comment by Psychenginehelper** [comment]
false positive, Luna Grabber isn't a virus, using it right now.
