### ISSUE TITLE
Yeah so when i try to ddownload the link it shows that a trojan is in it, is my anti-virus just faulty or what?

### ISSUE THREAD

**Issue by Gawron678** [Smug246/Luna-Grabber#428]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Gawron678** [comment]
When i open the anti-virus that blocked the link it shows Trojan:Python/Multiverze, should i just allow it in or what?

**Comment by Gawron678** [comment]
I checked the files, i have no run command.i hope i didn't get fucking trojan on my laptop

**Comment by Smug246** [comment]
because the luna.py file is malware it will be detected but it is no use without a webhook being in it or any options being enabled

**Comment by Smug246** [comment]
just turn ur av off if you want to download it and build ur own
