### ISSUE TITLE
Please help me 

### ISSUE THREAD

**Issue by JustLmr** [Smug246/Luna-Grabber#429]
please help me how to fix it

![Ekran görüntüsü 2023-07-22 173721](https://github.com/Smug246/Luna-Grabber/assets/88000765/74ec37ba-f375-4428-8454-f21d332d3667)

![Ekran görüntüsü 2023-07-22 173715](https://github.com/Smug246/Luna-Grabber/assets/88000765/3f488fc5-9f3c-4a8c-a577-2c9d3577c896)

**Comment by Smug246** [comment]
ngl im not sure on this one
