### ISSUE TITLE
Run file nowhere to be seen. (ss included)

### ISSUE THREAD

**Issue by olive38947** [Smug246/Luna-Grabber#430]
**Run folder nowhere to be seen.** 
not sure if im missing a braincell 
![image](https://github.com/Smug246/Luna-Grabber/assets/129156472/18a66ab2-184b-440a-91d4-f888e7bce624)
@Smug246 Anyways, love your work.

**Comment by Smug246** [comment]
why are you looking for a run folder? if youve ran setup just run builder

**Comment by olive38947** [comment]
> why are you looking for a run folder? if you've ran setup just run builder

I have been trying to run builder but it just doesn't do anything. Im kind of new to github. sorry

**Comment by Frxst-Dev** [comment]
disable the windows anti-virus, it deleted it

**Comment by Smug246** [comment]
> > why are you looking for a run folder? if you've ran setup just run builder
> 
> 
> 
> I have been trying to run builder but it just doesn't do anything. Im kind of new to github. sorry

this means ur getting an error try and run builder.pyw via the directory ur in using cmd and it should show u the error
