### ISSUE TITLE
Run.bat and setup.bat doesnt work

### ISSUE THREAD

**Issue by PooSmacker** [Smug246/Luna-Grabber#434]
**Cant start run.bat or setup.bat **
Basically it instantly closes when I open run and Ill paste the error I get when I run setup, I also have python 3.11.4 and it says I dont have it installed and its added to path

"Python 3.11 is not installed. Downloading...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 23.9M  100 23.9M    0     0  89.9M      0 --:--:-- --:--:-- --:--:-- 90.5M
Installing Python 3.11...
Python 3.11 has been installed
Installing Requirements...
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'python'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = 'C:\\Users\\jeb\\AppData\\Local\\Programs\\Python\\Python310\\python.exe'
  sys.base_prefix = ''
  sys.base_exec_prefix = ''
  sys.platlibdir = 'lib'
  sys.executable = 'C:\\Users\\jeb\\AppData\\Local\\Programs\\Python\\Python310\\python.exe'
  sys.prefix = ''
  sys.exec_prefix = ''
  sys.path = [
    'C:\\Users\\jeb\\AppData\\Local\\Programs\\Python\\Python310\\python310.zip',
    'C:\\Users\\jeb\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\',
    'C:\\Users\\jeb\\AppData\\Local\\Programs\\Python\\Python310\\DLLs\\',
    'C:\\Users\\jeb\\AppData\\Local\\Programs\\Python\\Python310',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00004c34 (most recent call first):
  <no Python frame>
Checking for updates...
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'python'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = 'C:\\Users\\jeb\\AppData\\Local\\Programs\\Python\\Python310\\python.exe'
  sys.base_prefix = ''
  sys.base_exec_prefix = ''
  sys.platlibdir = 'lib'
  sys.executable = 'C:\\Users\\jeb\\AppData\\Local\\Programs\\Python\\Python310\\python.exe'
  sys.prefix = ''
  sys.exec_prefix = ''
  sys.path = [
    'C:\\Users\\jeb\\AppData\\Local\\Programs\\Python\\Python310\\python310.zip',
    'C:\\Users\\jeb\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\',
    'C:\\Users\\jeb\\AppData\\Local\\Programs\\Python\\Python310\\DLLs\\',
    'C:\\Users\\jeb\\AppData\\Local\\Programs\\Python\\Python310',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00002194 (most recent call first):
  <no Python frame>
Press any key to continue . . ."

**Screenshots**

![image](https://github.com/Smug246/Luna-Grabber/assets/103903987/72c01a22-830f-49be-8231-0251b68fc2f8)

**Comment by Smug246** [comment]
so you need to add python to path manually. plenty of videos on youtube of how to do this
