### ISSUE TITLE
Cookie grabber issue

### ISSUE THREAD

**Issue by Frxst-Dev** [Smug246/Luna-Grabber#439]
Hii smug, I have had an issue with luna, everything works fine except for the cookie grabber, that for some reason isn't working, yes I made sure its enabled and the cookies file does appear it's just empty or look like this: https://ibb.co/MBFwDsX ,
and yes I know the person has cookies, because they have a huge search history and in the image they are logged in to discord but I don't see a discord cookie. (oh and they where using chrome)

**Steps to reproduce the behavior:**
1. Go to 'lunar grabber'
2. Click on 'generate'
3. execute on pc  and see 'no cookies ' 😭

**Expected behavior**
I expect to see cookies

**Comment by Smug246** [comment]
that's very weird. i'm not too sure at the moment. is cookies the only thing not working

**Comment by Frxst-Dev** [comment]
For some reason a lot of the info when someone resets a password on discord isn't showing up when someone reset their password (https://ibb.co/d5q9S4t)
