### ISSUE TITLE
Pip not working

### ISSUE THREAD

**Issue by Roobster08** [Smug246/Luna-Grabber#444]
Says to update pip 
![image](https://github.com/Smug246/Luna-Grabber/assets/133581449/06eb7dd2-9d6f-4a50-b921-0dbe253815df)
then i do this on python and it says this 
![image](https://github.com/Smug246/Luna-Grabber/assets/133581449/5bc3e24d-aff3-43f7-b7b1-887f68733bca)

**Comment by Smug246** [comment]
you don't actually have to update it but you've got into the python interpreter by accident so u just need to exit(). and the correct command is 'python -m pip install --upgrade pip'
