### ISSUE TITLE
run.bat doesn't work

### ISSUE THREAD

**Issue by Joeytjuhh** [Smug246/Luna-Grabber#446]
When I open run.bat as administrator it doesn't open.
My antivirus is turned off and I downloaded python with the setup.bat file.

**Comment by Smug246** [comment]
there is no run.bat file

**Comment by Joeytjuhh** [comment]
There is
![image](https://github.com/Smug246/Luna-Grabber/assets/79990012/6a16e84f-38de-4516-b054-8f40a44465b2)

**Comment by Joeytjuhh** [comment]
How do I need to open it the right way?
(Opening the builder file doesn't work either)
