### ISSUE TITLE
All of my pyinstaller files have .exe.notanexecutable and wont get the victim. At the end of the code is says access denied.

### ISSUE THREAD

**Issue by Coolthan** [Smug246/Luna-Grabber#449]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Coolthan** [comment]
Also roblox cookie logging doesnt work

**Comment by Smug246** [comment]
that means there was an error building. check luna.log file and the error will be at the bottom
