### ISSUE TITLE
Discord info ain't working and I can't paste webhook 

### ISSUE THREAD

**Issue by Theyassin9182** [Smug246/Luna-Grabber#451]
So I'm using the latest version and it's still ain't working, it only sends a screenshot and system info without the discord info even though I'm sure I have the discord info option on + when I try to paste my webhook it doesn't paste and I have to write it all.

**Comment by Smug246** [comment]
what are you testing this on. windows or mac. how are you pasting. should just be a simple ctrl + v

**Comment by Theyassin9182** [comment]
> what are you testing this on. windows or mac. how are you pasting. should just be a simple ctrl + v

I'm testing this on windows + I paste using Ctrl + v but still it ain't pasting

**Comment by Smug246** [comment]
check ur clipboard to see if you have anything actually copied. do windows button + v

**Comment by Theyassin9182** [comment]
> check ur clipboard to see if you have anything actually copied. do windows button + v

I did check and it works fine but not when I try pasting the webhook, also how can I fix that it doesn't send the discord info?

**Comment by Smug246** [comment]
> > check ur clipboard to see if you have anything actually copied. do windows button + v
> 
> I did check and it works fine but not when I try pasting the webhook, also how can I fix that it doesn't send the discord info?

the pasting issue is ur end. but the discord tokens could be because of your browser. what do you use? do any errors pop up

**Comment by Theyassin9182** [comment]
> > > check ur clipboard to see if you have anything actually copied. do windows button + v
> > 
> > I did check and it works fine but not when I try pasting the webhook, also how can I fix that it doesn't send the discord info?
> 
> the pasting issue is ur end. but the discord tokens could be because of your browser. what do you use? do any errors pop up

I use chrome, do any errors pop up ? No.
Is there any way I can contact u using discord?

**Comment by Smug246** [comment]
you can dm on tele smug246

**Comment by Theyassin9182** [comment]
> you can dm on tele smug246

Kk check ur dms

**Comment by MrOne559** [comment]
ihave this problem discord info not send .
please ineed dm you to fix problem.
