### ISSUE TITLE
info

### ISSUE THREAD

**Issue by lazpap11** [Smug246/Luna-Grabber#454]
**Describe the bug**
the file created when its run it doesnt give me any info
**To Reproduce**

**Expected behavior**
to give me info in my webhook

**Comment by Smug246** [comment]
turn ur antivirus off when running

**Comment by lazpap11** [comment]
> turn ur antivirus off when running

Sounds schechy but all code is ok.btw can you add me on discord?you are the best coder i know and i need tips.you are the best guy to help me with coding.thank you

**Comment by Smug246** [comment]
> > turn ur antivirus off when running
> 
> 
> 
> Sounds schechy but all code is ok.btw can you add me on discord?you are the best coder i know and i need tips.you are the best guy to help me with coding.thank you

respectfully no, i don't have time for that
