### ISSUE TITLE
builder has an error and doesn't compile

### ISSUE THREAD

**Issue by Jery7s** [Smug246/Luna-Grabber#458]
builder doesn't open and has this error messege:
Python 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

= RESTART: C:\Users\Admin\Downloads\Luna-Grabber-1.5.5-alpha\Luna-Grabber-1.5.5-alpha\builder.pyw
Traceback (most recent call last):
  File "C:\Users\Admin\Downloads\Luna-Grabber-1.5.5-alpha\Luna-Grabber-1.5.5-alpha\builder.pyw", line 11, in <module>
    import customtkinter
ModuleNotFoundError: No module named 'customtkinter'

**Comment by Smug246** [comment]
open cmd type pip install customtkinter then press enter
