### ISSUE TITLE
easy to delete

### ISSUE THREAD

**Issue by Azuuu1** [Smug246/Luna-Grabber#463]
so bassicaly when someone runs it it works but its very easy to delte u just delete the exe can u make it somehow harder to do?

**Comment by Smug246** [comment]
i cant block them from deleting the file so what do you mean

**Comment by Azuuu1** [comment]
i mean its just easy to get of the machine maybe try to make so the grabber is copying itself and putting the copied one to startup and the other one not sr for bad grammar

**Comment by Smug246** [comment]
ye thats what it does. it copies itself into startup if that option is enabled if thats what u mean
