### ISSUE TITLE
setup dont work

### ISSUE THREAD

**Issue by ermani70** [Smug246/Luna-Grabber#469]
it close himself i dont have time  to do the screenshot
![immagine_2023-08-07_192010949](https://github.com/Smug246/Luna-Grabber/assets/130074518/408f7922-f1c9-44eb-93ce-fe251a3b176b)

**Comment by ermani70** [comment]
just update pip and the red errors are still there

**Comment by Fydren** [comment]
> just update pip and the red errors are still there

can you help me set it up
