### ISSUE TITLE
python: can't open file 'C:\\builder.pyw': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Beamerweinsr** [Smug246/Luna-Grabber#471]
pls somone help me it says python: can't open file 'C:\\builder.pyw': [Errno 2] No such file or directory

**Comment by Smug246** [comment]
thats not the absolute path thats just c drive plus builder.pyw. where has that come from

**Comment by Beamerweinsr** [comment]
and builder wont open

**Comment by Beamerweinsr** [comment]
but the run thing works perfectly
