### ISSUE TITLE
how to fix the 'not found' error for you guys ;)

### ISSUE THREAD

**Issue by 0xSharkyy** [Smug246/Luna-Grabber#472]
If the folder for the Luna Grabber is on your Desktop, follow the video [here](https://youtu.be/aEc3W6OxdAw)

If the folder for the Luna Grabber is in your 'Downloads' folder, follow the video [here](https://youtu.be/YfWHZ6X35Vc)

**Comment by Fydren** [comment]
can you help me get it setup

**Comment by Smug246** [comment]
> oh and btw @Smug246 what happened to compiling to exe?

you still can. the options are pyinstaller and cxfreeze. they both compile to exe

**Comment by Fydren** [comment]
dualhooked?

**Comment by 0xAnonymx0** [comment]
Can u help me bro?
i intalled python 3.11 and add to path.
Dosnt work

**Comment by Smug246** [comment]
> dualhooked?

no and its open source so u can check urself
