### ISSUE TITLE
Victims need Python installed?

### ISSUE THREAD

**Issue by Gman6567** [Smug246/Luna-Grabber#474]
So I have a CXfreeze exe done and labeled it how I wanted it. But when a victim runs it, it says they need python? I have the files do I need to compile or build that one last time?
 
![underground esp](https://github.com/Smug246/Luna-Grabber/assets/141984931/0b469a09-7599-4f7b-8f98-410ff17aad1e)

**Comment by Smug246** [comment]
you literally send them all of those files there
