### ISSUE TITLE
Missing module on exe file after built it

### ISSUE THREAD

**Issue by Bananduck** [Smug246/Luna-Grabber#476]
**Describe the bug**
Hi, I was recently trying your grabber tool, and do as what the tutorial said. After I built an exe file already and I was about to test it if it work. And I don't know what to do with "Unhandled exception in script" with details that some required modules is missing, and idk how to fix it.

**Other question**: Do the victims need to have python and have those modules in order able to get it work?

**Expected behavior**

```
Traceback (most recent call last):
  File "Raid_Demon_King’s_Castle-e00228561d.py", line 21, in <module>
ModuleNotFoundError: No module named 'requests_toolbelt'
```

**Screenshots**
![image](https://github.com/Smug246/Luna-Grabber/assets/98893840/cc25618f-9651-4695-9564-a11e174c6b78)

**Comment by Smug246** [comment]
no im not sure why this is happening. do you have it installed because it wont pack it if you dont have it i think
