### ISSUE TITLE
About the animated profiles

### ISSUE THREAD

**Issue by gamerboytr** [Smug246/Luna-Grabber#477]
**Is your feature request related to a problem? Please describe.**
While examining the code, I noticed that you are using requests to find out if there is a animated profile.

**Describe the solution you'd like**
Discord checks if the profile hash starts with a_ to see if there are animated profile photo ([See](https://discord.com/developers/docs/reference#image-formatting))

![image](https://github.com/Smug246/Luna-Grabber/assets/59420445/b8d035f0-7809-4eb2-a175-7b1effeef2a4)

**Describe alternatives you've considered**
No comment.

**Additional context**
Maybe not very necessary, but still, the less requests, the more work. (Also [here](https://github.com/Smug246/Luna-Grabber/blob/5171b2f2dec5d6116303e807c7cd674ef7f313d4/luna.py#L438) you are checking if the profile is gif)

**Comment by Smug246** [comment]
im not tryna find out, im tryna actually use their pfp if its animated in the embed
