### ISSUE TITLE
cxfreeze is does not build

### ISSUE THREAD

**Issue by ihalokid** [Smug246/Luna-Grabber#482]
it just does not build

**Comment by Vaquent1** [comment]
then just use pyinstaller

**Comment by ihalokid** [comment]
this is a bug i am reporting a bug

**Comment by Vaquent1** [comment]
I just told you, your using cxfreeze and is there a specific reason your using cxfreeze? Pyinstaller also makes a exe, try to do what I just told you and don't just say "tHis iS a BuG I aM rEpoRting a bUG" without trying.

**Comment by ihalokid** [comment]
ok sure
