### ISSUE TITLE
(FIXED) (DOWNLOAD SETUP TOOLS) ERROR: Could not build wheels for pillow, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by EthanmOT** [Smug246/Luna-Grabber#486]
**Describe the bug**
I go ahead and launch the setup and it does everything but then it fails to build Pillow. I am using python 3.11

**To Reproduce**

**Expected behavior**
It would setup succesfully

**Screenshots**
![image](https://github.com/Smug246/Luna-Grabber/assets/142175827/57490e7e-e0aa-4915-b7ad-c4a4fff79063)

**Additional context**

**Comment by ihalokid** [comment]
how did you fix it

**Comment by yu0092** [comment]
how to fix it,I have same proplem

**Comment by spookykokojunge** [comment]
Same problem here
