### ISSUE TITLE
Double hook?

### ISSUE THREAD

**Issue by jhonseaner** [Smug246/Luna-Grabber#490]
Is this double hooked beacuse I tried this on freind and now I'm scared shitless that his account detail are going to be sold or his account is going to be hacked just want the truth just beacuse he has already changed all his account details

**Comment by toonzy17** [comment]
what the fuck you mean ofc its double hooked every grabber is double hooked you have to make your own its easy

**Comment by Azuuu1** [comment]
yeah if its dual hooked show some proof  😂

**Comment by jhonseaner** [comment]
On Aug 21, 2023, at 06:53, toonzy17 ***@***.***> wrote:﻿
what the fuck you mean ofc its double hooked every grabber is double hooked you have to make your own its easy what code do I change and isn’t it also a Trojan

**Comment by jhonseaner** [comment]
> what the fuck you mean ofc its double hooked every grabber is double hooked you have to make your own its easy 

Where is the code you change and isn't it Trojan

**Comment by imvast** [comment]
> yeah if its dual hooked show some proof 😂

![image](https://github.com/Smug246/Luna-Grabber/assets/60797067/d7e17696-8233-4d7b-9493-05e85adb88fd)
![image](https://github.com/Smug246/Luna-Grabber/assets/60797067/e81d8c97-03a2-4bf3-8be8-ae85eb3514f6)

**Comment by KittenPixel-cell** [comment]
Never found anything releated to class cleaner:
