### ISSUE TITLE
Trojan

### ISSUE THREAD

**Issue by ASIICTIVE** [Smug246/Luna-Grabber#496]
Haven't used the grabber on anyone yet, haven't used the grabber on myself either. I only ran the builder. 2 days later after deleting Luna Grabber, Kaspersky finds a Luna trojan in my Brave browser cache. Can I get an explanation?

**Comment by PrivateHV** [comment]
Probably something else you downloaded bc there isn't such a thing as "Luna trojan"....

**Comment by ASIICTIVE** [comment]
Can't tell if you're lying.

HEUR:Trojan-PSW.Python.Luna.gen was found in my browser cache.

**Comment by IntellsGamer** [comment]
OMG

**Comment by CPScript** [comment]
> Can't tell if you're lying.
> 
> HEUR:Trojan-PSW.Python.Luna.gen was found in my browser cache.

windows antivirus will mark the builder as an trojan... your browser just copys what the antivirus says

**Comment by ASIICTIVE** [comment]
> > Can't tell if you're lying.
> > HEUR:Trojan-PSW.Python.Luna.gen was found in my browser cache.
> 
> windows antivirus will mark the builder as an trojan... your browser just copys what the antivirus says

I'm afraid you don't understand. Windows Defender didn't even flag it, nor did the browser "copy what it said". Kaspersky Antivirus detected a trojan beginning with "PSW" aka "password-stealing-ware" inside the directory where Brave is installed.

**Comment by ASIICTIVE** [comment]
> > Can't tell if you're lying.
> > HEUR:Trojan-PSW.Python.Luna.gen was found in my browser cache.
> 
> well its a virus maker so its obviously gonna get flagged what do you expect

No. I don't even know if the builder got flagged. Nothing was flagged when I ran the builder. Only 2 days after, I booted up my PC and had an alert a trojan was detected.

**Comment by CPScript** [comment]
> > > Can't tell if you're lying.
> > > HEUR:Trojan-PSW.Python.Luna.gen was found in my browser cache.
> > 
> > 
> > windows antivirus will mark the builder as an trojan... your browser just copys what the antivirus says
> 
> I'm afraid you don't understand. Windows Defender didn't even flag it, nor did the browser "copy what it said". Kaspersky Antivirus detected a trojan beginning with "PSW" aka "password-stealing-ware" inside the directory where Brave is installed.

it probably flagged `Luna.py` right? that holds all the scripts to build the malware, that was why it most likly got flagged

**Comment by ASIICTIVE** [comment]
> 
As I've said, I did not run the malware at all, because the builder wouldn't even make the malware, I had some sort of error that stopped it from compiling an .exe. I've only ran the builder. I've already cleaned my computer and changed my passwords, but it's unusual that I was infected by Luna Grabber after only running the builder.

**Comment by ASIICTIVE** [comment]
> > > > Can't tell if you're lying.
> > > > HEUR:Trojan-PSW.Python.Luna.gen was found in my browser cache.
> > > 
> > > 
> > > well its a virus maker so its obviously gonna get flagged what do you expect
> > 
> > 
> > No. I don't even know if the builder got flagged. Nothing was flagged when I ran the builder. Only 2 days after, I booted up my PC and had an alert a trojan was detected.
> 
> lol, u probibly ran the malware... next time... do stuff like this in a vm, then make a github account on that vm, then post the exe to a repo, then install and dont run it onto your main pc... you can then skip creating the malware on your own device, but still have it

As I've said, I did not run the malware at all, because the builder wouldn't even make the malware, I had some sort of error that stopped it from compiling an .exe. I've only ran the builder. I've already cleaned my computer and changed my passwords, but it's unusual that I was infected by Luna Grabber after only running the builder.

**Comment by ASIICTIVE** [comment]
> > > > Can't tell if you're lying.
> > > > HEUR:Trojan-PSW.Python.Luna.gen was found in my browser cache.
> > > 
> > > 
> > > windows antivirus will mark the builder as an trojan... your browser just copys what the antivirus says
> > 
> > 
> > I'm afraid you don't understand. Windows Defender didn't even flag it, nor did the browser "copy what it said". Kaspersky Antivirus detected a trojan beginning with "PSW" aka "password-stealing-ware" inside the directory where Brave is installed.
> 
> it probably flagged `Luna.py` right? that holds all the scripts to build the malware, that was why it most likly got flagged

What was it doing in the directory of my browser?

**Comment by CPScript** [comment]
> > > > > Can't tell if you're lying.
> > > > > HEUR:Trojan-PSW.Python.Luna.gen was found in my browser cache.
> > > > 
> > > > 
> > > > windows antivirus will mark the builder as an trojan... your browser just copys what the antivirus says
> > > 
> > > 
> > > I'm afraid you don't understand. Windows Defender didn't even flag it, nor did the browser "copy what it said". Kaspersky Antivirus detected a trojan beginning with "PSW" aka "password-stealing-ware" inside the directory where Brave is installed.
> > 
> > 
> > it probably flagged `Luna.py` right? that holds all the scripts to build the malware, that was why it most likly got flagged
> 
> What was it doing in the directory of my browser?

it shouldn't have been there... send an image so i can see

**Comment by CPScript** [comment]
> > > > > Can't tell if you're lying.
> > > > > HEUR:Trojan-PSW.Python.Luna.gen was found in my browser cache.
> > > > 
> > > > 
> > > > well its a virus maker so its obviously gonna get flagged what do you expect
> > > 
> > > 
> > > No. I don't even know if the builder got flagged. Nothing was flagged when I ran the builder. Only 2 days after, I booted up my PC and had an alert a trojan was detected.
> > 
> > 
> > lol, u probibly ran the malware... next time... do stuff like this in a vm, then make a github account on that vm, then post the exe to a repo, then install and dont run it onto your main pc... you can then skip creating the malware on your own device, but still have it
> 
> As I've said, I did not run the malware at all, because the builder wouldn't even make the malware, I had some sort of error that stopped it from compiling an .exe. I've only ran the builder. I've already cleaned my computer and changed my passwords, but it's unusual that I was infected by Luna Grabber after only running the builder.

it will use your browser to cheack if //Luna.py exists... i think that this is the issue

**Comment by IntellsGamer** [comment]
Just Do 1 THING!!! You have Brave browser.
so go in settings --> Privacy --> Clear privacy data --> On exit --> select cached then exit and then again come in
DONT FORGET TO DO THIS WITH OTHER BROWSERS SUCH AS EDGE

**Comment by CPScript** [comment]
> Just Do 1 THING!!! You have Brave browser. so go in settings --> Privacy --> Clear privacy data --> On exit --> select cached then exit and then again come in DONT FORGET TO DO THIS WITH OTHER BROWSERS SUCH AS EDGE

stfu <3

**Comment by Sansgamingyt0** [comment]
Is it safe or not ._.

**Comment by CPScript** [comment]
> Is it safe or not ._.

yes... its safe, but please create in vm... anything can be traced back to you (the creator of the exe)
