### ISSUE TITLE
builder.pwy doesnt open

### ISSUE THREAD

**Issue by desownikk** [Smug246/Luna-Grabber#502]
[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip
Checking for updates...
This version is up to date!
You can now open builder.pyw to open the builder!

when i open builder.pyw, nothing happends.
Can somebody tell me how to fix it?
\Users\###\Downloads\Luna-Grabber-main\Luna-Grabber-main\builder.pyw", line 13, in <module>
    import customtkinter
ModuleNotFoundError: No module named 'customtkinter'

**Comment by haydengamer87** [comment]
I have had the same issue, when i run the setup it spits out a bunch of random stuff and then closes and i cant open builder.pyw even after running setup.

**Comment by Lilcapalotee** [comment]
same issue but in idle editor it says there isnt a module named pyuac

**Comment by PLBDEV** [comment]
same issue

**Comment by desownikk** [comment]
thx for support, now it quite works

**Comment by incomplacent** [comment]
desownikk what did you do to fix it?

**Comment by ebarbsrage** [comment]
press "edit with IDLE" and then run it

**Comment by dehnon** [comment]
i try opening builder.pyw and doing edit with idle dosent work and idk how to install pip or anything and setup just says "installing requirements and closes
![WIN_20220909_14_19_12_Pro](https://github.com/Smug246/Luna-Grabber/assets/154475906/67e38c93-392f-4b16-9330-70834fa78b41)

**Comment by dehnon** [comment]
i try opening builder.pyw and it dont work ive tried edit with idle and idk how to install pip and i tried the cmd 
![for luna](https://github.com/Smug246/Luna-Grabber/assets/154475906/fa85b11d-9e8e-4d7f-ac14-06f366380ff3)

**Comment by dehnon** [comment]
also this popped up so i need to know how to get the whole pip thing
![Luna man](https://github.com/Smug246/Luna-Grabber/assets/154475906/99102dc1-f0fc-4948-bf08-7f7381254663)
