### ISSUE TITLE
Virus :P

### ISSUE THREAD

**Issue by TubbyTheTubBoat** [Smug246/Luna-Grabber#509]
https://www.virustotal.com/gui/file/74bdec0a83536cbe6a47030bb06a8a223369028b4ba9608ae1beba0107b0381f

**Comment by Azuuu1** [comment]
i see u dont know shd about how it even works

**Comment by Semailol** [comment]
No shit it thinks its a virus it logs info and sends it to the webhook

**Comment by Vaquent1** [comment]
if you don't want a similar result then just use the file pumper and obfuscator

**Comment by Bazingers** [comment]
> https://www.virustotal.com/gui/file/74bdec0a83536cbe6a47030bb06a8a223369028b4ba9608ae1beba0107b0381f

doe you need to be retarded to think thats not getting flagged as a virus, ITS A FUCKING INFO STEALER
