### ISSUE TITLE
Webhook doesnt work and the bot doesnt show any info, also when i run the file it says its corrupted or something and states the address of where the thing is. 

### ISSUE THREAD

**Issue by ValkyrieGGZ** [Smug246/Luna-Grabber#517]
![image](https://github.com/Smug246/Luna-Grabber/assets/142152382/278dabb8-6fc4-4c20-ac40-d230fec6a0f9)

also its not working at all, before this update it was perfectly fine and working, also i tried every file type and theyre all broken too

**Comment by senoxc** [comment]
same here

**Comment by Vaquent1** [comment]
obfuscated?
