### ISSUE TITLE
.exe file not found in the build section

### ISSUE THREAD

**Issue by Seakza** [Smug246/Luna-Grabber#520]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Seakza** [comment]
there is no **.exe** file option in the build section [
![Luna Grabber Builder 29-08-2023 23_26_16](https://github.com/Smug246/Luna-Grabber/assets/143490969/19c3dc54-3cd7-46d0-a409-40790d78a67d)
](url)

**Comment by zeos432** [comment]
Cant see the .exe too

**Comment by Vaquent1** [comment]
its pyinstaller

**Comment by DylanStango** [comment]
same
