### ISSUE TITLE
‼Builder not opening‼

### ISSUE THREAD

**Issue by TypicalTv** [Smug246/Luna-Grabber#537]
I have followed all steps but on step 3 where it says to open the builder, it doesn't open at all.
I have tried reinstalling, turning off my anti-virus software, and deleting python and reinstalling but nothing works. 

https://github.com/Smug246/Luna-Grabber/assets/144561770/6c3717cf-477b-47fa-9f0a-a9c55e41decd

**Comment by Vaquent1** [comment]
run the run.bat ;-;

**Comment by m3donix** [comment]
same here

**Comment by flashbackboi** [comment]
same man
