### ISSUE TITLE
just doesnt work

### ISSUE THREAD

**Issue by 7xa5h** [Smug246/Luna-Grabber#541]
**Describe the bug**
it keeps on outputing random errors in the powershell and once i try to open the file it just openss but it doesnt send anything, yes ive verified my webhooks and tested 4 different ones

**To Reproduce**
just use the builder?

**Expected behavior**
it sends everything to my webhook

**Screenshots**
![image](https://github.com/Smug246/Luna-Grabber/assets/119355463/497e290a-5a7a-4cdf-80df-b9a31f760830)

**Additional context**
uh the setup also never exits

**Comment by Vaquent1** [comment]
try moving the folder to somewhere else then running again
