### ISSUE TITLE
!BUILDER WONT OPEN!

### ISSUE THREAD

**Issue by AydenOn** [Smug246/Luna-Grabber#545]
Builder won't open for me. It gives me a text saying I need to open as admin but there is no option for that. Any ideas on how to fix it?
Sc/What it says:
![image](https://github.com/Smug246/Luna-Grabber/assets/145630361/4057fcc2-db43-4158-b6e0-ed6f613f1ed0)

**Comment by Smug246** [comment]
it should prompt you with a yes or no when it opens. do you have pyuac installed?
