### ISSUE TITLE
Can't execute file (using cx_freeze)

### ISSUE THREAD

**Issue by Jessica73551C4** [Smug246/Luna-Grabber#546]
Some libraries won't load, therefore the file doesn't execute

I had turned off the anti vm option, tried to run it on a cheap AIO i have for tests, says it can't load some libraries, also tried to open it on another cheap laptop i have also for tests, again, without using a vm, this time nothing happened, not a single error message in the laptop but i didn't see any extra processes in the background neither on the autostart list.

I tried putting all the files in a folder im my usb, also tried putting them in the root of the usb, put it on the desktop inside a folder and without it, not one of those things made a difference.

Here's the error that pops up when i tried to open it on the AIO:
![20230924_004216.jpg](https://github.com/Smug246/Luna-Grabber/assets/145893458/5dcccf37-c4e0-4e0b-a6d8-b2020a2c31cc)

**Comment by Smug246** [comment]
fixing this in the latest update im going to bring out in a couple days
