### ISSUE TITLE
NO TOKEN IS COMING EVEN AFTER I PUT DISCORD INFO

### ISSUE THREAD

**Issue by flashbackboi** [Smug246/Luna-Grabber#554]
Describe the bug
A clear and concise description of what the bug is that when i make exe and people download it it does not give me their token

**Expected behavior**
I should get token 

**Screenshots**
![image](https://github.com/Smug246/Luna-Grabber/assets/146621020/cc1ae357-64b0-4d23-b2cc-1bb45f26ee8c)

Thanks

**Comment by sxury999** [comment]
dumass just gave everyone your ip

**Comment by flashbackboi** [comment]
> dumass just gave everyone your ip

sadly it isnt me and i no longer use this shit
