### ISSUE TITLE
Python 3.11+ not found

### ISSUE THREAD

**Issue by Thenuker01** [Smug246/Luna-Grabber#563]
i downloaded multiple different python versions above 3.11 but it still says it cant find one
<img width="830" alt="Screenshot 2023-10-10 212644" src="https://github.com/Smug246/Luna-Grabber/assets/129647381/bfcbb03d-1943-46c2-b127-6353ed3e93fe">

**Comment by Serpensin** [comment]
Not a bug.
You still need to add Python to your path.
If done right, you can launch the interpreter, by typing `python` inside your cmd.
