### ISSUE TITLE
I test the File info Grabbber on virtual machine but when i test it it showed me an error

### ISSUE THREAD

**Issue by nockemking123** [Smug246/Luna-Grabber#572]
Okay i just wanna test the file it the info grabber works but it shows me an error. can you please help!?

![BRO HELP ME](https://github.com/Smug246/Luna-Grabber/assets/148553539/c639570a-7f69-4ec1-9794-8d179937b787)

**Comment by nockemking123** [comment]
the other file keeps showing me error except The cxfreeze file thing you know

**Comment by Smug246** [comment]
fixing this in the latest update im going to bring out in a couple days
