### ISSUE TITLE
Can"t Find Update

### ISSUE THREAD

**Issue by N1TR0783** [Smug246/Luna-Grabber#573]
I have re-downloaded the zip file and doid all the steps and when I ran the setup.bat file it says there's a update and i say yes to it and it closes it self and i cant find the updated version please help.

**Comment by Serpensin** [comment]
https://github.com/Serpensin/Luna-Grabber

You can try it from me. I already opened a pr, but it seems, that he isn't really active.

**Comment by Smug246** [comment]
fixing this in the latest update im going to bring out in a couple days and @Serpensin ill check out ur pr later but it clashes very heavily with what im going to release
