### ISSUE TITLE
it wont let me open builder after i run set up

### ISSUE THREAD

**Issue by llama223** [Smug246/Luna-Grabber#579]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by llama223** [comment]
wont let me open builder after i run set up

**Comment by RichardLuuu** [comment]
yeah me neither

**Comment by Smug246** [comment]
have you got python installed and added to path

**Comment by RichardLuuu** [comment]
Installing Requirements...
C:\msys64\mingw64\bin\python.exe: No module named pip
Checking for updates...
Traceback (most recent call last):
  File "C:\Users\R2\Downloads\Luna-Grabber-main\Luna-Grabber-main\tools\update.py", line 6, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

This is what I get when I try to run setup

**Comment by Smug246** [comment]
go to your terminal and do pip install requests

**Comment by RichardLuuu** [comment]
It still says the same thing

**Comment by lofyi1** [comment]
I have the same issue not as richard but i finished the set up but it wont let me open the builder if you need more info to help me solve this issue ill provide more info

**Comment by WarFiN123** [comment]
Pip uninstall requests
Pip install requests

**Comment by Bazingers** [comment]
setup.bat wasnt working so i js did py -m pip install module on terminal
