### ISSUE TITLE
Is it save?

### ISSUE THREAD

**Issue by VicCodeDev** [Smug246/Luna-Grabber#580]
No hate to this project great that you can program but is the python file save?

**Comment by VicCodeDev** [comment]
To like youse so not if I customize i get hacked myself 😂

**Comment by Smug246** [comment]
it is safe

**Comment by VicCodeDev** [comment]
Ok wait can also someone else confirm that

**Comment by VicCodeDev** [comment]
Also does you victimn need python

**Comment by Smug246** [comment]
nope

**Comment by bastiro03** [comment]
You can just look at the code to check for any malware. But what part of this program being literally meant to steal people's discord accounts makes you think it could be safe at all?
