### ISSUE TITLE
.pyinstaller not working and cxfreeze not showing up

### ISSUE THREAD

**Issue by 1Aterius** [Smug246/Luna-Grabber#581]
The pyinstaller first of all is not working. I have tried 3 different files and keep getting the same error, with no date return, with said error being "The ordinal 380 could not be located in the dynamic link library".

And then the cxfreeze file option does not show up with only .py and pyinstaller showing up as options.

**Comment by Smug246** [comment]
i removed the cxfreeze option and am going to add nuitka. what version of python do you
have? is your pyinstaller corrupted
