### ISSUE TITLE
finished setup but when i click the builder nothing shows up

### ISSUE THREAD

**Issue by lofyi1** [Smug246/Luna-Grabber#582]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by lofyi1** [comment]
wont let me open the builder i got the setup done

**Comment by Mitsakos93** [comment]
> wont let me open the builder i got the setup done

i have the same problem , did you find what the problem?

**Comment by lofyi1** [comment]
yeah i fixed it when installing python theres an option to install to path
