### ISSUE TITLE
After i run Setup.bat and builder py gui does not pop up

### ISSUE THREAD

**Issue by LGamerzNockz** [Smug246/Luna-Grabber#586]
After i run setup then i run builder.py NOTHING pops up

**Comment by LGamerzNockz** [comment]
I would like a answer cause its strange

**Comment by LGamerzNockz** [comment]
just does not work

**Comment by Smug246** [comment]
means ur getting an error check the luna.log file

**Comment by WarFiN123** [comment]
Run it in command prompt

**Comment by venomthedeveloper** [comment]
How

**Comment by venomthedeveloper** [comment]
> Run it in command prompt

How though

**Comment by WarFiN123** [comment]
> > Run it in command prompt
> 
> How though

Use cd command in command prompt and locate your download location for the grabber folder. Then run python builder.pyw and it should work
