### ISSUE TITLE
Add more file pumping sizes

### ISSUE THREAD

**Issue by WarFiN123** [Smug246/Luna-Grabber#590]
Add more file pumping sizes so that virustotal and chrome cannot scan it for viruses

**Comment by Smug246** [comment]
ok i can do that but you can do it urself if u want

**Comment by WarFiN123** [comment]
> ok i can do that but you can do it urself if u want

How do I do it?

**Comment by WarFiN123** [comment]
> ok i can do that but you can do it urself if u want

um i havent recieved any reply yet
