### ISSUE TITLE
cant open builder

### ISSUE THREAD

**Issue by andrew7427** [Smug246/Luna-Grabber#591]
**Describe the bug**

**To Reproduce**
I did setup, and opened builder but nothing happened.

**Expected behavior**

builder gui opens

**Screenshots**

https://github.com/Smug246/Luna-Grabber/assets/149634781/d100cb37-36c8-46fb-aa42-9c471af585e3

**Additional context**

**Comment by andrew7427** [comment]
nothing opens at all

**Comment by Entity378** [comment]
you probably need to install the packages

**Comment by andrew7427** [comment]
is re ran it but it still wont open. ill try downloading them manually

**Comment by andrew7427** [comment]
idk man i manually installed all of the packages in cmd and still cant open builder

**Comment by Entity378** [comment]
if you have python installed and added to path it should work. Sorry if I can't help you further but I'm busy fixing the injection which isn't working at the moment

**Comment by Smug246** [comment]
u still having problems with this?

**Comment by deecoyz** [comment]
> u still having problems with this?

my friend on windows 11 says it wasn't opening, also tried every single reply

**Comment by Bad-man123** [comment]
I have the same issue nothing happens :(

**Comment by SpaceFlier100** [comment]
> > idk man i manually installed all of the packages in cmd and still cant open builder
> 
> run 'python builder.pyw' in your terminal window when you are in the directory of the builder

This worked for me, instead of double-clicking the file

**Comment by Bazingers** [comment]
> idk man i manually installed all of the packages in cmd and still cant open builder

u put python on path?
