### ISSUE TITLE
Cannot Import name Ctypes from wintypes

### ISSUE THREAD

**Issue by lxnelyyyy** [Smug246/Luna-Grabber#592]
When I run the .exe file I get this error

![image](https://github.com/Smug246/Luna-Grabber/assets/149540218/d471b31e-c456-4bd4-a943-b4ffffe5ee23)
**Additional context**

Any Fix?

**Comment by Smug246** [comment]
make sure you it's not corrupted for urself and reinstall it then build

**Comment by eeeer846** [comment]
I have the same bug issue, uninstalling and reinstalling does not make a difference
is there any fix?
