### ISSUE TITLE
Pillow.exe error

### ISSUE THREAD

**Issue by FazePas** [Smug246/Luna-Grabber#593]
**Describe the bug**
I setup.bat download everything but I saw that there was an error with the pillow

**Expected behavior**

![image](https://github.com/Smug246/Luna-Grabber/assets/116115971/a58aae34-ba8b-4d5b-b5ad-c3c60d0c1b04)

**Additional context**
I tried to do it again but nothing changed

**Comment by FazePas** [comment]
can someone help me with that?

**Comment by Smug246** [comment]
what version are u using

**Comment by FazePas** [comment]
actualy I reinstall pyton 3.11 and they work
