### ISSUE TITLE
how do i add python to the path?????   

### ISSUE THREAD

**Issue by mickdv** [Smug246/Luna-Grabber#598]
when i open setup.bat i see 
Python is not installed! (Go to https://www.python.org/downloads and install the latest version.)
Make sure it is added to PATH.

but i alredy installed python

**Comment by DaneX3089** [comment]
retard

**Comment by Bazingers** [comment]
> when i open setup.bat i see Python is not installed! (Go to https://www.python.org/downloads and install the latest version.) Make sure it is added to PATH.
> 
> but i alredy installed python

did you read the part that you need to make sure it is added to path?
