### ISSUE TITLE
Bug report 

### ISSUE THREAD

**Issue by GalaxyBuddy** [Smug246/Luna-Grabber#603]
**Describe the bug**
When using file pumper on whatever build you're using it makes it so when the victim launches it an error pops up saying "This directory is corrupted or unreadable"

**To Reproduce**
1. Go to the GUI
2. Enable file pumper
3. Build it in pyinstaller or cxfreeze
4. Launch the exe or whatever
5. See error

**Expected behavior**
It just to add an extra 5mb and so on

**Screenshots**
![image](https://github.com/Smug246/Luna-Grabber/assets/82051080/1c6cd187-76b2-4872-bae3-0a09cc565849)

**Additional context**
As long as you don't have file pumper enabled it works fine

**Comment by Smug246** [comment]
ah so thats what causes it. try using it without for now until its fixed

**Comment by WarFiN123** [comment]
> ah so thats what causes it. try using it without for now until its fixed

you have to run builder.pyw in command prompt and then use it.

**Comment by GalaxyBuddy** [comment]
> > ah so thats what causes it. try using it without for now until its fixed
> 
> you have to run builder.pyw in command prompt and then use it.
