### ISSUE TITLE
dont working Luna grabber

### ISSUE THREAD

**Issue by kokawd** [Smug246/Luna-Grabber#609]
help pls i wannted test the stealler and openned it but it doesnt give information about me just nothing idk but I attached a webhook it just dont working idk

**Comment by Bazingers** [comment]
like you builted it and it dosent send any info?

**Comment by kokawd** [comment]
> like you builted it and it dosent send any info?

yeah

**Comment by Bazingers** [comment]
that happend to me, but only when i used in opera gx's download feature ( when you download it and iit has a lil button to run ) but when i ran like without opera gx like on the downloads file it was all good
