### ISSUE TITLE
Cant open builder py or main py

### ISSUE THREAD

**Issue by Karo123123123** [Smug246/Luna-Grabber#611]
Yes py is added to path, im using py 3,11 only thing i saw was that pillow cant be installed

**Comment by WarFiN123** [comment]
run it in cmd?

**Comment by FrozenSalad** [comment]
Install the packages manually, whatever says not able to import, install those from cmd.

**Comment by Bazingers** [comment]
> Yes py is added to path, im using py 3,11 only thing i saw was that pillow cant be installed

do ''py -m pip install pillow'' on terminal
