### ISSUE TITLE
Grabber just dont work

### ISSUE THREAD

**Issue by inDail** [Smug246/Luna-Grabber#634]
Hello! When im trying to run my grabber, it giving me that error, and dont send grabbed info. So, what shoud i do?
![image](https://github.com/Smug246/Luna-Grabber/assets/130224909/4f8fb6f2-5ade-4bbd-980a-6e7836d7c9ec)

**Comment by floorseat** [comment]
How were you able to open the builder file?

**Comment by inDail** [comment]
> How were you able to open the builder file?

just open builder.pyw

**Comment by floorseat** [comment]
> > How were you able to open the builder file?
> 
> just open builder.pyw

wish that worked for me, it doesn't work

**Comment by inDail** [comment]
> > > How were you able to open the builder file?
> > 
> > 
> > just open builder.pyw
> 
> wish that worked for me, it doesn't work

try to open setup.bat first, i litterally idk whats the problem

**Comment by rozwaga** [comment]
did you fix it?

**Comment by ichigo77777** [comment]
it didnt worked because you are running on a vm right? i tried the same thing but apparently you cant

**Comment by inDail** [comment]
> did you fix it?

nah

**Comment by inDail** [comment]
> it didnt worked because you are running on a vm right? i tried the same thing but apparently you cant

But i didnt set anti vm in the build program tbh¯\_(ツ)_/¯

**Comment by floorseat** [comment]
i got it
