### ISSUE TITLE
No embeds when other people run it

### ISSUE THREAD

**Issue by tomaxtoro** [Smug246/Luna-Grabber#638]
Whenever i run the py or the exe file on my pc it shows all the embeds and tokens but when other people run it i only get theire zip file can anyone help

**Comment by Otakuardido** [comment]
hey, how did you did? i mean, im trying to make the builder options functional, but when i try to open it by myself (to see if it woeks), i didnt receive any webhook, what did you do? it will be better with screenshoots, thanks
