### ISSUE TITLE
File exe

### ISSUE THREAD

**Issue by Devillllll666** [Smug246/Luna-Grabber#643]
**Hello, I did all the steps and finally created an exe file and it was completely correct, but when I try to open the exe file, nothing happens without an error and nothing is sent to my discord, that is, the exe file does not work and when I click on it, nothing happens.**

**Comment by Devillllll666** [comment]
my python is 3.12.1

**Comment by cdworld0** [comment]
Same for me, but i think it is because the .exe build that crashes when you tick on the options that does not work together. But when i choose these options from this video it magically worked. https://www.youtube.com/watch?v=sQN0exFYo0w
