### ISSUE TITLE
testet by myself

### ISSUE THREAD

**Issue by lukas4g4** [Smug246/Luna-Grabber#644]
i tested it and it worked, but i dont know how to delete from my pc, i restart pc and it turns on always

**Comment by cdworld0** [comment]
To delete it you got to restart your pc so the program turns on, now when you get the "fake error" ( Dont close it ) you got to open taskmanager (CTRL + SHIFT + ESC). Now search/find the program (Make sure you dont close the "fake error" or else you wont find it). Then you need to right-click and choose "Open File Location". When you have found the program, you will need to end the program and then delete it from file explorer.
