### ISSUE TITLE
Nothing Sent To Webhook 

### ISSUE THREAD

**Issue by spooky69699** [Smug246/Luna-Grabber#655]
Whenever someone or my vm runs it nothing is sent to the webhook. I tried to rebuild and turn off some option but it still wont send anything to the webhook.

**Comment by Minerdoes** [comment]
same problem

**Comment by spooky69699** [comment]
Yeah im not sure why I had my friend run it to test for me then i ran it on a vm and nothing was still sent to the webhook or discord.

**Comment by RipAngelhacks** [comment]
It logs you

**Comment by Otakuardido** [comment]
did you fix it? its because i have the same problem
