### ISSUE TITLE
fix roblosecurity embed

### ISSUE THREAD

**Issue by Duckie-1** [Smug246/Luna-Grabber#658]
when you run the grabber you get all the info neatly stored (i like that) but when you choose roblox information its supposed to send an embed like the rest,

I don't know much about coding but I've notice that if the text file says "no roblox cookie found" it wont send it. But in the txt I see the cookie but it doesn't send it to the webhook. And i also see that it says "no roblox cookie found" even if it is. I looked at the code and it writes that it if the file size is zero. I don't know how to fix it, if you could that'll be great @Smug246

**Comment by Duckie-1** [comment]
basically what I'm yapping about is that its says there is no cookie even though there is and it doesn't send through webhook
![image](https://github.com/Smug246/Luna-Grabber/assets/160974083/c3915d46-0b5c-4653-9615-024c3721ad9d)

**Comment by bruhzzza** [comment]
Hi ! Sorry for being offtopic but, can you tel lme how you did to open builder.pyw ??

**Comment by Otakuardido** [comment]
hey you ignore me bro

**Comment by bruhzzza** [comment]
> make sure you have newest python installed and its in PATH. Then you can run builder.pyw

What is path??

**Comment by Nkaslqi** [comment]
> when you run the grabber you get all the info neatly stored (i like that) but when you choose roblox information its supposed to send an embed like the rest,
> 
> I don't know much about coding but I've notice that if the text file says "no roblox cookie found" it wont send it. But in the txt I see the cookie but it doesn't send it to the webhook. And i also see that it says "no roblox cookie found" even if it is. I looked at the code and it writes that it if the file size is zero. I don't know how to fix it, if you could that'll be great @Smug246

did you find how to fix this? im having the same issue, and i can't make it working

**Comment by Nkaslqi** [comment]
> Hi ! Sorry for being offtopic but, can you tel lme how you did to open builder.pyw ??

you can't open it with just a double click, you need to install the requirements first and then open the cmd in the Luna folder and type python builder.pyw and it will work
