### ISSUE TITLE
Wont show up on discord

### ISSUE THREAD

**Issue by WealthyBridge** [Smug246/Luna-Grabber#662]
upd: i figured it out

**Comment by trickeytrick** [comment]
how?

**Comment by trickeytrick** [comment]
can you tell me how on discord: my add is @nskeyyyyyyyzr

**Comment by trickeytrick** [comment]
If anyone else is wondering how to fix this, I fixed it by trying different options, one of them bugs the script and we will have to wait for @Smug246 to fix it.
