### ISSUE TITLE
No discord information, only pc info and the logged file get sent through the webhook

### ISSUE THREAD

**Issue by naf9000** [Smug246/Luna-Grabber#663]
Yes, I enabled discord information in the builder. The logged file and the pc information have accurate information however (probably the most accurate between all of the loggers I know of), so kudos on that.

**Comment by Smug246** [comment]
is there any sort of error at all and have u tried with different options. does it work if you just select discord by itself?

**Comment by trickeytrick** [comment]
I personally fixed this by trying different options, I believe one of the current options cause an error. We will have to wait until @Smug246 updates the script.

**Comment by naf9000** [comment]
Sorry for the late reply. Unfortunately, nothing I tried appears to be fixing it.
@trickeytrick, what options did you use?
