### ISSUE TITLE
How to use a token.

### ISSUE THREAD

**Issue by trickeytrick** [Smug246/Luna-Grabber#665]
Hey, does anyone know how to login to their Discord using the token. And also how to log into their Roblox Account using their cookies, if you could just explain or a helpful link I'd really appreciate it.

**Comment by ValoqLmao** [comment]
For cookies you go to your roblox profile. You then inspect element, and navigate to the application tab. From there, you find the "cookies" tab, then drop it down and there should be a box that says like "roblox.com" then click on that. Now you will see a bunch of cookies for the roblox website, find the .roblo security cookie, and to the right of the name where it says "value" right click on it then click edit value, now paste in their cookie and you have successfully replaced your cookie with theirs, and when you refresh the page you'll be in their account.
