### ISSUE TITLE
HI Webhbooks is showing invalid

### ISSUE THREAD

**Issue by PureHeartedGuy** [Smug246/Luna-Grabber#666]
I tried to make webook and pasted its urk in luna grabber but it shows invalid webook

**Screenshots**
![Screenshot 2024-03-03 222700](https://github.com/Smug246/Luna-Grabber/assets/160230511/4bf87d8b-7377-4214-89f8-4f27c1463fa0)

![Screenshot 2024-03-03 222747](https://github.com/Smug246/Luna-Grabber/assets/160230511/b9af0950-7c22-4c83-aeaf-48b9cf976dba)

please help!!

**Comment by PureHeartedGuy** [comment]
@Smug246

**Comment by trickeytrick** [comment]
Could you paste the webhook but delete some of the digits and letters after the https://discord.com/api/webhooks/ so I can try to support you. Thanks.

**Comment by PureHeartedGuy** [comment]
ok

**Comment by PureHeartedGuy** [comment]
https://discord.com/api/webhooks/1213888978038693958/-B0D7orTJa7z4XoLzXXdjcAhSscBnaXSgeXdjq
some numbaers are removed from this

**Comment by PureHeartedGuy** [comment]
@trickeytrick

**Comment by Smug246** [comment]
your internet might be making it timeout. i increased the timeout amount so you can try again or just remove it urself

**Comment by PureHeartedGuy** [comment]
my internet is so much strong.

**Comment by PureHeartedGuy** [comment]
idk but it is working now thanks
