### ISSUE TITLE
File corrupted

### ISSUE THREAD

**Issue by TheDudeRaj** [Smug246/Luna-Grabber#668]
I try and use the file myself but it says it is corrupted so I can't use it or send it to anyone because it won't work because it just becomes corrupted and unreadable

**Comment by TheDudeRaj** [comment]
@Smug246 u know how to fix?

**Comment by trickeytrick** [comment]
Reinstall python from https://python.org/downloads and reinstall the whole luna from this repo. If you are still facing issues just mention me and I'll try to help out.

**Comment by TheDudeRaj** [comment]
it says aaccess is denied when i try to build the file @trickeytrick

**Comment by trickeytrick** [comment]
Could you send a screenshot of the error?

**Comment by TheDudeRaj** [comment]
![image](https://github.com/Smug246/Luna-Grabber/assets/162055661/571bd382-7ecc-4fcd-b3b9-d559f632965b)

**Comment by TheDudeRaj** [comment]
![image](https://github.com/Smug246/Luna-Grabber/assets/162055661/a7ddaab7-5bef-4c86-9e26-961019e57378)

it doesnt build the files then when it does if it does it says its corrupt or unreadable

**Comment by TheDudeRaj** [comment]
![image](https://github.com/Smug246/Luna-Grabber/assets/162055661/da22d7d5-8acc-4599-8480-995e1ade8fca)
 
 it doesnt build and when it does its either corrupted or unreadable @trickeytrick

**Comment by Smug246** [comment]
you need to give it admin permissions

**Comment by TheDudeRaj** [comment]
how do i give it admin perms @Smug246

**Comment by TheDudeRaj** [comment]
it also doesnt open when i click builder i have to manually open with visuals studio then run it is that a problem and there isnt a option to run as admin anywhere and the file builds it is unreadable and corrupted
