### ISSUE TITLE
Bug when running victim .exe

### ISSUE THREAD

**Issue by ValoqLmao** [Smug246/Luna-Grabber#670]
When victims run the file they get error "Failed to execute script due to unhandled exception: cannot import name 'wintypes' from 'ctypes'.

Then below it shows what appears to be a log of the error, I'll attatch that below.

Traceback (most recent call last):
  File "Dev-Commands-Hotfix.py", line 5, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 13, in <module>
ImportError: cannot import name 'wintypes' from 'ctypes' (C:\Users\User\AppData\Local\Temp\_MEI88002\ctypes\__init__.pyc)

If I coudl have help I would appreciate it. Also I tried running it myself just to see if it worked for me with no luck, thanks!
![bug](https://github.com/Smug246/Luna-Grabber/assets/118303017/d87333ea-cda9-4dc7-8325-71b7de3c83c9)

**Comment by Smug246** [comment]
latest version
