### ISSUE TITLE
builder doesnt open but i have everything already

### ISSUE THREAD

**Issue by captizz** [Smug246/Luna-Grabber#673]
pretty much just the entire title, builder doesnt open even though i have latest version of py and already downloaded the stuff through setup.bat

**Comment by Smug246** [comment]
what error does it say

**Comment by captizz** [comment]
> what error does it say

it has no error msg just doesnt open

**Comment by bekreative6** [comment]
i reinstalled python and it worked

**Comment by captizz** [comment]
> i reinstalled python and it worked

just tried, didnt work sadly
