### ISSUE TITLE
is luna grabber broken rn?

### ISSUE THREAD

**Issue by Cicake1** [Smug246/Luna-Grabber#675]
**Describe the bug**
everytime i build the file and make it pyinstaller im greeted with an error message.

**To Reproduce**
1. create your own file
2. make it .pyinstaller
3. open it

**Expected behavior**
for fatal error to appear and info to go to webhook

![309943706-d87333ea-cda9-4dc7-8325-71b7de3c83c9](https://github.com/Smug246/Luna-Grabber/assets/145713440/ade97cc1-8190-4e6b-94c9-d6d9007f0738)

**Comment by Smug246** [comment]
try latest version
