### ISSUE TITLE
Cant open builder

### ISSUE THREAD

**Issue by JustJadeFr** [Smug246/Luna-Grabber#676]
when i try to open builder, the blue wheel appears for a second, then it dissappears and the builder doesn't open. I've tried restarting my laptop and everything

**Comment by Smug246** [comment]
what os are u on and have u tried opening from command prompt?

**Comment by JustJadeFr** [comment]
im on windows 11 and i already tried opening it from cmd prompt. it didnt
work

**Comment by unknownKillaXSnow** [comment]
same
