### ISSUE TITLE
NOT BUILT

### ISSUE THREAD

**Issue by luccas46** [Smug246/Luna-Grabber#677]
Hi there,

When I click on builder, the file is not generated anywhere, where is it generated, or is it already outdated?

Thanks

**Comment by C4-Luffy** [comment]
The file was generated in the same directory where you installed Luna Grabber.

**Comment by jaySnap1** [comment]
not there

**Comment by C4-Luffy** [comment]
Hit me on discord  i might  help you grandline_boosters
