### ISSUE TITLE
Cant add python to path please make tutorial video

### ISSUE THREAD

**Issue by yusgz89** [Smug246/Luna-Grabber#682]
![image](https://github.com/Smug246/Luna-Grabber/assets/165218599/a3da39c0-aaa8-4fb6-9e51-00140e5c2ea0)

**Comment by C4-Luffy** [comment]
To resolve the issue, please ensure that both Luna and Python are downloaded to the same directory path. This should rectify the problem.

**Comment by C4-Luffy** [comment]
Hey, add me on Discord so I can help you out with your problem, grandline_boosters
