### ISSUE TITLE
Having issues with the webhook

### ISSUE THREAD

**Issue by OuterEnd07** [Smug246/Luna-Grabber#685]
I'm trying to regain an account that was hacked, that is in the same server as me. And I made a webhook to get the token but whenever I'm building it's only showing me, my information and not of the person with me on the server. I would really appreciate some insight on what I might be doing wrong, I really need to regain that account.

**Comment by Smug246** [comment]
it will only get valid tokens so i'm guessing that token is locked or you don't have the saved data on that machine

**Comment by Serpensin** [comment]
This has probably to do with the fact, that discord slightly changed the format of tokens.
I fixed this in https://github.com/Smug246/Luna-Grabber/pull/688.
