### ISSUE TITLE
It built, but i got no message from webhoook.

### ISSUE THREAD

**Issue by SyntaxErrorY** [Smug246/Luna-Grabber#687]
**Describe the bug**
i was using the builder, i enabled everything, then next thing i knew, it built then i tried it on myself then nothing happpened

**To Reproduce**
1. make webhook
2. build enabling everything
3. use pyinstaller.
4.build then try it on yourself.

**Expected behavior**
![Screenshot 2024-04-12 145028](https://github.com/Smug246/Luna-Grabber/assets/166866815/0c6599f7-bee7-4433-a57d-c7429badaa46)

i expected to have the webhook tell me my own info, but it didnt

**Comment by yassodewyere** [comment]
"I am encountering comparable errors which require attention and resolution. Your assistance in resolving this issue would be greatly appreciated.
![image](https://github.com/Smug246/Luna-Grabber/assets/84945125/df1c5b73-e56f-4b1e-a7af-41e1bfacfc96)

**Comment by Smug246** [comment]
it looks like the icons arnt valid. are u trying to add .ico formatted images
