### ISSUE TITLE
Which files do I have to download?

### ISSUE THREAD

**Issue by 6Frauds** [Smug246/Luna-Grabber#693]
Which files do I have to download? And what do I have to turn into a zip and extract. Actually can you simplify the process cs I'm a little slow. Would appreciate it.

**Comment by Serpensin** [comment]
Download [this](https://github.com/Smug246/Luna-Grabber/archive/refs/heads/main.zip) and [this](https://www.python.org/ftp/python/3.11.9/python-3.11.9-amd64.exe). Extract the zip and run the bat.

**Comment by 6Frauds** [comment]
Stuck in terminal after doing this nothing is installing.

**Comment by Serpensin** [comment]
Bruh. More info (like a screenshot) would be nice. "It doesn't work" doesn't help devs, nor the consumer.

**Comment by C4-Luffy** [comment]
Hey, add me on Discord so I can help you out with your problem, grandline_boosters

**Comment by 6Frauds** [comment]
Its stuck in terminal saying its downloading an environment or smth of the sort and not installing the environment.
