### ISSUE TITLE
nuitka option

### ISSUE THREAD

**Issue by techbrainzx** [Smug246/Luna-Grabber#694]
when i select nuitka in the file options it appears that nuitka doesn't support pyton 3.12, but if i install 3.11 luna won't open.
![imagem_2024-04-20_153025135](https://github.com/Smug246/Luna-Grabber/assets/145053264/2de81bcc-5d19-42ac-ae78-80d535af608d)

**Comment by Smug246** [comment]
make sure you don't have both python versions installed. uninstall anything else that isn't 3.11 and test it

**Comment by Serpensin** [comment]
I'll try and add a option, where you can choose the version you want, if multiple are detected.

**Comment by techbrainzx** [comment]
ok thank you very much

**Comment by Serpensin** [comment]
PR opened.
https://github.com/Smug246/Luna-Grabber/pull/696

**Comment by Serpensin** [comment]
The pr got merged.
