### ISSUE TITLE
Python versions list bug

### ISSUE THREAD

**Issue by DBL-LEAM** [Smug246/Luna-Grabber#697]
---
name: Bug report
about: setup file
title: bug in the setup part
labels: bug
assignees: Dbl-Leam

---

**Describe the bug**
When i start the setup, it asks me to type the number of the python version i wanna use but the list doesn't appears. 

**To Reproduce**
1. Go to 'luna-grabber-main'
2. Click on 'setup'
3. See error

**Expected behavior**
I expected to see the list of the python version i wanna use, so i'd can start the builder after.

**Screenshots**
![Capture d'écran 2024-04-25 224510](https://github.com/Smug246/Luna-Grabber/assets/168137241/fd7d13fa-f1a7-4dff-916c-995afa17f422)

**Additional context**

**Comment by Smug246** [comment]
hm do you actually have python installed and if so can you tell me the path?

**Comment by DBL-LEAM** [comment]
Python is already installed, it’s the 3.12 version, where can I find the
path of it ?

**Comment by DBL-LEAM** [comment]
After the execution of the command, this is what it returns:
C:\Program Files\PowerShell\7
C:\Program Files (x86)\Common Files\Oracle\Java\javapath
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\WINDOWS\System32\OpenSSH\
C:\Users\Elève\Desktop\Luna-Grabber-main\.venv\Scripts\python.exe
C:\Program Files\PowerShell\7\
C:\Users\Elève\AppData\Local\Programs\Python\Launcher\
C:\Users\Elève\AppData\Local\Microsoft\WindowsApps
C:\Users\Elève\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Python 3.12\
C:\Users\Elève\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Python 3.12\Scripts\
C:\Users\Elève\Desktop\Luna-Grabber-main\.venv\Scripts\python.exe

**Comment by Serpensin** [comment]
Then it should be detected. But why is your .venv in there? That's not something you want in there at all.

**Comment by Serpensin** [comment]
Until the PR is merged, you can try [this](https://github.com/Smug246/Luna-Grabber/files/15129823/setup.zip) setup.bat.
Just replace the old one.

**Comment by Serpensin** [comment]
What? I have no idea, what you want. XD

**Comment by ToastedTortoise** [comment]
No Python installations found in PATH. Please install Python and try again.: https://www.python.org/downloads/

C:\Program Files (x86)\Common Files\Oracle\Java\javapath
C:\Program Files (x86)\Razer Chroma SDK\bin
C:\Program Files\Razer Chroma SDK\bin
C:\Program Files (x86)\Razer\ChromaBroadcast\bin
C:\Program Files\Razer\ChromaBroadcast\bin
C:\Windows\system32
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
C:\Windows\System32\OpenSSH\
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps
C:\Program Files\dotnet\
C:\Users\LEGION\AppData\Local\Microsoft\WindowsApps

PS C:\Users\LEGION>
What do i also do now? i tried using the other setup and it didnt work? this one sais i have to python even though i do?
was i meant to extract luna in my downloads? what's the problem??

**Comment by DBL-LEAM** [comment]
> What? I have no idea, what you want. XD


Basically, with the new setup file that you gave me it works, the builder opens, but when I click on the build button, unlike before, it is written directly file built and it is not created

**Comment by Serpensin** [comment]
`it is written directly file built and it is not created`
I still have no idea, what that sentence even supposed to mean.
You know, that it takes some time for a build to finish?

**Comment by DBL-LEAM** [comment]
I just installed the update that the setup offered me and I still have the same problem, everything works normally except when I press build and nothing happens on the command side, the file is not created not. thanks for your help
