### ISSUE TITLE
Nothing sending to webhook

### ISSUE THREAD

**Issue by Gigan123** [Smug246/Luna-Grabber#698]
The grabber gets built but whenever I test it or try it it doesn't send anything to the webhook and nothing else happens

1. Go to 'LunaGrabber'
2. Click on 'Grabber'
3. Scroll down to 'Discord'
4. See nothing in webhook

Expected behavior
I expected the webhook to have information in it

**Comment by Smug246** [comment]
could you record/show what settings you use and do you check that the webhook is valid beforehand?

**Comment by DryingChoros** [comment]
it's not working, it's building the file but nothing happens when someone opens it
the settings are: 
1- Fake Error
2- System Info
3- Roblox Info
4- Anti Spam
5- Disable Defender
6- Kill Protector
7- Anti Debug/VM
8- 2FA Codes
9- Obfuscation
10- Self Destruct
11- Clipboard
12- Discord Info
13- Wifi Info
14- Browser Info
15- Injection

pyinstaller

**Comment by Smug246** [comment]
try different combinations. there may be just one that's causing the others not to work

**Comment by 0xLuxx** [comment]
> it's not working, it's building the file but nothing happens when someone opens it the settings are: 1- Fake Error 2- System Info 3- Roblox Info 4- Anti Spam 5- Disable Defender 6- Kill Protector 7- Anti Debug/VM 8- 2FA Codes 9- Obfuscation 10- Self Destruct 11- Clipboard 12- Discord Info 13- Wifi Info 14- Browser Info 15- Injection
> 
> pyinstaller

Have you solved this problem yet?

**Comment by DryingChoros** [comment]
> > it's not working, it's building the file but nothing happens when someone opens it the settings are: 1- Fake Error 2- System Info 3- Roblox Info 4- Anti Spam 5- Disable Defender 6- Kill Protector 7- Anti Debug/VM 8- 2FA Codes 9- Obfuscation 10- Self Destruct 11- Clipboard 12- Discord Info 13- Wifi Info 14- Browser Info 15- Injection
> > pyinstaller
> 
> Have you solved this problem yet?

not yet

**Comment by Smug246** [comment]
please create a new issue
