### ISSUE TITLE
When I press build it builds for a sec and doesnt build

### ISSUE THREAD

**Issue by loneeps** [Smug246/Luna-Grabber#701]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Serpensin** [comment]
There is a reason, we have the console visible. It's that way, so you can tell us the output of it...

**Comment by loneeps** [comment]
I didnt get what u said

**Comment by Serpensin** [comment]
Me neither. Since you don't give us any info at all, we can't help.
there is a reason, we ask for info in the report. So please update it, to include at least some info.

**Comment by Smug246** [comment]
please open a new issue
