### ISSUE TITLE
Even though it's Python, it wants me to download it.

### ISSUE THREAD

**Issue by ruzgar42o** [Smug246/Luna-Grabber#702]
Even though it's Python, it wants me to download it.
![image1](https://github.com/Smug246/Luna-Grabber/assets/168284447/3f35070e-ba73-44f9-b185-8040d90e80ca)

**Comment by ruzgar42o** [comment]
.

**Comment by ruzgar42o** [comment]
.

**Comment by Serpensin** [comment]
It clearly says, that you either don't have Python installed, or didn't add it to PATH.

**Comment by ruzgar42o** [comment]
> Açıkça ya Python'un kurulu olmadığını ya da onu PATH'e eklemediğinizi söylüyor.

Python setup

**Comment by Smug246** [comment]
please open a new issue
