### ISSUE TITLE
Setup.bat returns an error

### ISSUE THREAD

**Issue by chertillo** [Smug246/Luna-Grabber#703]
can you tell me what to do in such a situation? I tried installing different versions of python, it didn't help. what to do?
![bandicam 2024-04-27 19-29-21-861](https://github.com/Smug246/Luna-Grabber/assets/168292755/490ad793-f6a3-4f58-a8c2-6a0079825bd8)

**Comment by Serpensin** [comment]
Tell me, what's printed in the terminal. Write it word for word here.

**Comment by chertillo** [comment]
after opening the installation file. it appears in the terminal-"1. Found Python version 3.11.2: "C:\Users\pahak\AppData\Local\Programs\Python\Python311\python.exe"

If you want to use Nuitka, you need to select a version 3.4.X - 3.11.X
Enter the number of the desired Python version from the list above:"

**Comment by Serpensin** [comment]
And what did you learn, by reading that text? I don't know, how I should make it more clear, on what to do.

**Comment by chertillo** [comment]
after I enter the installed python version into the terminal, this error appears-"Invalid selection Exiting..."

**Comment by Serpensin** [comment]
And what did you enter?

**Comment by chertillo** [comment]
3.11.2
and what should I have entered into the terminal if not this?

**Comment by Serpensin** [comment]
Ofc the number at the beginning...

**Comment by chertillo** [comment]
so can you tell me exactly what I need to enter into the terminal? I'm sorry, but I don't speak English, I use a translator, so sometimes it may not be clear what I'm trying to say.

**Comment by chertillo** [comment]
so what should I write to the terminal to make everything work?

**Comment by Serpensin** [comment]
You need to enter the left most number.

**Comment by chertillo** [comment]
Thanks

**Comment by stevengrtk** [comment]
hello i have the same problem for the Setup.bat I put the version: 3.11.0 but it tells me that it is invalid

**Comment by akanyxxx** [comment]
hello @Serpensin 
when you say the leftmost number that's which one
 tank you

**Comment by akanyxxx** [comment]
can you answer my problem

**Comment by akanyxxx** [comment]
@Serpensin help me pls

**Comment by Serpensin** [comment]
Stop it! This isn't discord! Pings have no use. And since you're not willing to read, I'm not willing to help!

**Comment by Noman17-tect** [comment]
Write 1 and press enter
