### ISSUE TITLE
Error Start file .py

### ISSUE THREAD

**Issue by DKJOHNN** [Smug246/Luna-Grabber#704]
https://github.com/Smug246/Luna-Grabber/assets/155661198/49710cea-87e7-49c7-a68b-72b9d0af49a2

help me, I've already tried with python version 3.11.9, 3.12, 3.8.0 and 3.4.0 none of them worked, nukita says it doesn't support python 3.12, bild pythoninstaller (ERROR - Error with compiling file: [WinError 2] system cannot find the specified file_
INFO - Successfully removed file: ./muskito.py

**Comment by DKJOHNN** [comment]
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
Checking for updates...
C:\Users\DK.fds\AppData\Local\Programs\Python\Python312\python.exe: can't open file 'C:\\Users\\DK.fds\\tools\\update.py': [Errno 2] No such file or directory

Running in CMD

**Comment by Serpensin** [comment]
Ofc that doesn't work, since you start the .py file with your local interpreter and not with your venv one.
Since you clearly don't know that much about Python, you should definitely stick to nuitka, or pyinstaller.

**Comment by DKJOHNN** [comment]
I tried nuitka, with 3.4.0 and it didn't work, pythonInstaller also didn't work in other versions, can you tell me how I solve the nuitka problem?

**Comment by DKJOHNN** [comment]
I managed to execute the code through venv, but how will the target have to do all this? or do I need to create a file that starts the virtual machine and opens the .py?

**Comment by Serpensin** [comment]
The .py file is only really useful, to include it in other Projects. I suggest, to use nuitka, to build an exe file.
Although nuitka works with 3.4, luna doesn't. For luna you need to have at least 3.6 installed, since older versions don't work, because of f-strings.

**Comment by DKJOHNN** [comment]
I start setup.bat choosing the python 3.4.0 option, and it opens the menu with python 3.9.10, when I create the file the logs say the following: [builder.pyw:390] - 2024-04-27 19:04:38,317 - INFO - Changed filetype: nuitka
[builder.pyw:390] - 2024-04-27 19:04:38,317 - INFO - Changed filetype: nuitka
[builder.pyw:390] - 2024-04-27 19:04:38,317 - INFO - Changed filetype: nuitka
[builder.pyw:441] - 2024-04-27 19:04:38,321 - INFO - Successfully changed config
[builder.pyw:527] - 2024-04-27 19:04:38,328 - ERROR - Error with compiling file: [WinError 2] The system cannot find the specified file
[builder.pyw:549] - 2024-04-27 19:04:39,300 - INFO - Successfully removed file: ./mm.py

When I run it with cmd this appears:

Microsoft Windows [version 10.0.19045.4291]
(c) Microsoft Corporation. All rights reserved.

C:\Users\DK.fds>C:\Users\DK.fds\Downloads\Luna-Grabber-main\Luna-Grabber-main\setup.bat
1. Found Python version 3.9.10: "C:\Users\DK.fds\AppData\Local\Programs\Python\Python39\python.exe"
2. Found Python version 3.6.0: "C:\Users\DK.fds\AppData\Local\Programs\Python\Python36\python.exe"
3. Found Python version 3.12.3: "C:\Users\DK.fds\AppData\Local\Programs\Python\Python312\python.exe"
4. Found Python version 3.4.0: "C:\Python34\python.exe"

If you want to use Nuitka, you need to select a version 3.4.X - 3.11.X
Enter the number of the desired Python version from the list above: 4

Creating Virtual Environment for Python version 3.4.0...
InstallingRequirements...
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
WARNING: You are using pip version 21.2.4; however, version 24.0 is available.
You should consider upgrading via the 'C:\Users\DK.fds\.venv_3.4.0\Scripts\python.exe -m pip install --upgrade pip' command.
Checking for updates...
C:\Users\DK.fds\AppData\Local\Programs\Python\Python39\python.exe: can't open file 'C:\Users\DK.fds\tools\update.py': [Errno 2] No such file or directory

**Comment by DKJOHNN** [comment]
Can you send me your discord so you can solve this for me?

**Comment by Serpensin** [comment]
No. And from that log, I see, that you didn't read my previous message anyway...

**Comment by DKJOHNN** [comment]
I've tried several times following your instructions and nothing, I can only generate a .py file, nuitka doesn't work and the log says it was not found and deletes the file in ALL versions of python, can you give me an idea of ​​how I Can I use .py to send it to the target as an exe that it opens and sends the information?

**Comment by Smug246** [comment]
please open a new issue
