### ISSUE TITLE
the exe file does not open

### ISSUE THREAD

**Issue by chertillo** [Smug246/Luna-Grabber#705]
after creating pyinstaller or Nuitka, an exe file appears (which is normal), but it does not open, an error appears-"The file or folder is corrupted. Reading is not possible" 
accordingly, nothing comes to the discord webhook either

**Comment by Smug246** [comment]
what options do you select

**Comment by chertillo** [comment]
everything except "add to startup" and "fake error"

**Comment by Smug246** [comment]
try turning off file pumper

**Comment by chertillo** [comment]
if I disable file pumper, the exe file will stop being created. it just won't appear in the folder.

**Comment by Smug246** [comment]
please open a new issue
