### ISSUE TITLE
What do I do in this situation?

### ISSUE THREAD

**Issue by 6Frauds** [Smug246/Luna-Grabber#706]
After running setup.bat this is what I see 
![Screenshot 2024-04-27 230418](https://github.com/Smug246/Luna-Grabber/assets/167580631/ec7e8c4d-bdd6-4786-86aa-10e41aaebb42)

**Comment by Spzxxaz** [comment]
i have same problem

**Comment by Spzxxaz** [comment]
u must type 1 or 2 and should work

**Comment by 6Frauds** [comment]
I'll try..

**Comment by 6Frauds** [comment]
Why is it taking so long to install all these packages, I've been here for 10 minutes

**Comment by 6Frauds** [comment]
nvm it worked

**Comment by 6Frauds** [comment]
How do I reopen it. After the initial opening simply pressing builder just doesn't work anymore
