### ISSUE TITLE
After clicking Build, the exe file does not build

### ISSUE THREAD

**Issue by Spzxxaz** [Smug246/Luna-Grabber#707]
Let's say when I select system info and browser info and click build, it says Building... and nothing is created, no file

**Comment by Smug246** [comment]
building... is when it's actually building the file. it will finish building when it says built file or you can just see ur file in the directory

**Comment by hydra33** [comment]
it does the same thing to me, I waited but nothing appears in my file

**Comment by Spzxxaz** [comment]
no, I mean, when I click Build... Building appears... and when it finishes after 2 seconds, it says Built file and when I check the luna grabber folder, there is nothing there

**Comment by Smug246** [comment]
please open a new issue

**Comment by Spzxxaz** [comment]
okay]
