### ISSUE TITLE
setup.bat problem

### ISSUE THREAD

**Issue by stevengrtk** [Smug246/Luna-Grabber#710]
bonjour j'ai le même problème pour le Setup.bat je mets la version : 3.11.0 mais il me dit qu'il est invalide

**Comment by Serpensin** [comment]
We don't speak french.

**Comment by stevengrtk** [comment]
sorry hello I have the same problem for the Setup.bat I put the version: 3.11.0 but it tells me that it is invalid

**Comment by stevengrtk** [comment]
it good in english?

**Comment by Serpensin** [comment]
https://github.com/Smug246/Luna-Grabber/issues/703#issuecomment-2081171369

**Comment by Smug246** [comment]
you need to type the list number. for example `1`
