### ISSUE TITLE
If I click Build, nothing is built

### ISSUE THREAD

**Issue by Spzxxaz** [Smug246/Luna-Grabber#715]
### What Did You Expect To Happen?

luna grabber bug i typed 

### What Happened?

if I click build, it says building... when it finishes after 2 seconds, nothing is created and when it is created, the exe file does not want to open

### Add Screenshots

i dont have

### Which Options Did You Select?

Add To Startup, Discord Info, Fake Error, Wifi Info, Ping, Minecraft Info, System Info, 2FA Codes, Browser Info, Roblox Info, Obfuscation, Injection, File Pumper

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Spzxxaz** [comment]
@Smug246

**Comment by Smug246** [comment]
please download the latest version i have since fixed this bug
