### ISSUE TITLE
i dont even know what bug this is

### ISSUE THREAD

**Issue by coolskbidicat** [Smug246/Luna-Grabber#716]
### What Did You Expect To Happen?

help me pls 

### What Happened?

its just a weird when sending it

### Add Screenshots

![ok pyhton](https://github.com/Smug246/Luna-Grabber/assets/168475406/2b678815-f630-44d5-bdae-b19c173a0e58)

### Which Options Did You Select?

Injection

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Smug246** [comment]
ye thats incredibly strange but please download the latest version and test that. it should be fixed.
