### ISSUE TITLE
Bug: Je n'arrive pas a metre ma version

### ISSUE THREAD

**Issue by vincyvaku** [Smug246/Luna-Grabber#719]
### What Did You Expect To Happen?

Bonjour lorsque j'ouvre le fichier setup.bat il me demande d'écrire la version de python sauf que quand j'écrit la version de python ca me dit invalid selection exitting j'aimerais savoir comment on fait pour regler le probleme. J'ai bien installer la version et configurer les Path

### What Happened?

Bonjour lorsque j'ouvre le fichier setup.bat il me demande d'écrire la version de python sauf que quand j'écrit la version de python ca me dit invalid selection exitting j'aimerais savoir comment on fait pour regler le probleme. J'ai bien installer la version et configurer les Path

### Add Screenshots

![token code erreur](https://github.com/Smug246/Luna-Grabber/assets/168601855/d7acd749-e1f6-44a6-bdb9-bdfcbdabdf43)

### Which Options Did You Select?

System Info

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Smug246** [comment]
il vous demande de saisir le numéro dans la liste ci-dessus. il ne demande pas la version python. tapez simplement 1 et appuyez sur entrée. to clarify i dont speak french i just got this from google translate. hope it helps

**Comment by vincyvaku** [comment]
ok merci ca a marché mais maintenant j'ai un autre probleme ca me dit ca et apres je sais pas quoi faire ?
![Capture d’écran 2024-05-01 014525](https://github.com/Smug246/Luna-Grabber/assets/168601855/58ca9702-062d-4989-995e-de7403728df3)

**Comment by Serpensin** [comment]
I guess you didn't quite extract the whole archive first.
