### ISSUE TITLE
Bug: its say valid hooks and i do a good one in 

### ISSUE THREAD

**Issue by Vinn404** [Smug246/Luna-Grabber#720]
### What Did You Expect To Happen?

Its not working

### What Happened?

Its say not good one

### Add Screenshots

![image](https://github.com/Smug246/Luna-Grabber/assets/85554068/4d344141-cc99-4882-9b50-89274a83a76a)

### Which Options Did You Select?

Discord Info

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Smug246** [comment]
i dont see the problem. the webhook is valid
