### ISSUE TITLE
feature: Adding me on discord or tele

### ISSUE THREAD

**Issue by KDot227** [Smug246/Luna-Grabber#721]
### What Feature?

The feature would be Smug pulling his pants up and adding me on tele or disc (I literally have everyone else from cheataway added quit being a bum they wanna see u again weirdo)

### Add Screenshots (If Applicable)

![image](https://github.com/Smug246/Luna-Grabber/assets/110929758/3576783c-e7a7-4492-ae66-6401b71ebc46)

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I want to work on this feature

**Comment by Smug246** [comment]
added you on cord
