### ISSUE TITLE
it doesnt send anything to the webhook (antivirus disabled) and btw my pc is very slow after getting ratted can someone help ?

### ISSUE THREAD

**Issue by coolskbidicat** [Smug246/Luna-Grabber#722]
### What Did You Expect To Happen?

pls help me lol

### What Happened?

after u click on it nothing gets send to ur webhook

### Add Screenshots

no screenshots to show

### Which Options Did You Select?

Disable Defender

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Serpensin** [comment]
What in the seven hells did you expect? Ofc it doesn't do shit, if you only select "Disable Defender".
