### ISSUE TITLE
Bug: Acces is denied

### ISSUE THREAD

**Issue by MohammedGeorge** [Smug246/Luna-Grabber#726]
### What Did You Expect To Happen?

When i try to build with full settings it say access is denied

### What Happened?

I cant build i dont know why

### Add Screenshots

![image](https://github.com/Smug246/Luna-Grabber/assets/160282892/07d6ea8b-65d7-4567-b017-fb733954bfd4)

### Which Options Did You Select?

Obfuscation

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by MohammedGeorge** [comment]
im sure its about with some setting in builder when i close all i can build ill find

**Comment by MohammedGeorge** [comment]
Yeah found the issu problem with obfuscation when i try to build with obfuscation settings it doesnt allow idk why

**Comment by Smug246** [comment]
download latest version and turn your antivirus off

**Comment by Smug246** [comment]
no reply so i will assume its fixed
