### ISSUE TITLE
got some but not everything

### ISSUE THREAD

**Issue by lcrn36** [Smug246/Luna-Grabber#727]
### What Did You Expect To Happen?

to get their roblox acc

### What Happened?

i sent it they installed somemof the stuff went to me but not all of it

### Add Screenshots

will if u want

### Which Options Did You Select?

Add To Startup, Discord Info, Wifi Info, Ping, 2FA Codes, Roblox Info, Injection, File Pumper

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Smug246** [comment]
roblox info needs some improving which i'm looking into

**Comment by lcrn36** [comment]
Ok dude thx for responding and can you add a webcam feature?

**Comment by Smug246** [comment]
ye that's also on my list

**Comment by lcrn36** [comment]
ok sweet

**Comment by Serpensin** [comment]
I just added that feature. But that adds ~40Mb to the size of the exe, since opencv is huge af. XD
