### ISSUE TITLE
Bug: venv folder

### ISSUE THREAD

**Issue by MercurialXVV** [Smug246/Luna-Grabber#734]
### What Did You Expect To Happen?

hello, my question may be stupid but, what am i supposed to do with the "venv" folder it appeared after I launched the "setup" file , i notice the folder luna and builder are missing (sorry my english is very bad)

### What Happened?

I only launched the setup file

### Add Screenshots

![Screenshot_226](https://github.com/Smug246/Luna-Grabber/assets/169184847/302cceb6-0f8f-4faa-bc67-8e86b486864a)

### Which Options Did You Select?

Disable Defender

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [x] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Smug246** [comment]
turn your antivirus off and redownload it all

**Comment by MercurialXVV** [comment]
it works thank you
