### ISSUE TITLE
my friends windows defender is blocking it

### ISSUE THREAD

**Issue by ankitaryathebest** [Smug246/Luna-Grabber#737]
### What Did You Expect To Happen?

i thought it was gonna work

### What Happened?

he tried to download it but windows defender blocked it

### Add Screenshots

uhh my friend wldnt send the screenshot so im putting the a pic of ronaldo
![ronaldo](https://github.com/Smug246/Luna-Grabber/assets/165265538/198fb13b-475b-443b-acd0-b19217f79bf1)

### Which Options Did You Select?

Disable Defender, Discord Info, Wifi Info, Minecraft Info, System Info, Browser Info, Roblox Info

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [ ] I have attempted to resolve my problem by myself

**Comment by ankitaryathebest** [comment]
pls tell me what to do asap pls i wanna hack them man

**Comment by Smug246** [comment]
you got to get them to turn windows defender off. currently the grabber isn't undetected

**Comment by TechyBuzzard** [comment]
is the grabber still detectable

**Comment by ankitaryathebest** [comment]
> is the grabber still detectable

Yea it’s still detectable bruh idk what to do he is also not agreeing to turn defender off
