### ISSUE TITLE
Bug: What should i do

### ISSUE THREAD

**Issue by Luna122342** [Smug246/Luna-Grabber#738]
### What Did You Expect To Happen?

It should open and when im  testing it on my self it should work 

### What Happened?

Its not working and i cant starta luna grabber without running setup.bat all the time before i open builder and  when im testing it it comes up this. And something with no module find customkinter

### Add Screenshots

![image](https://github.com/Smug246/Luna-Grabber/assets/169272938/c26f0b3b-765d-40a7-b849-2a451f0a92e7)
![image](https://github.com/Smug246/Luna-Grabber/assets/169272938/ac27a902-0230-4d12-91b7-e47c1c1ddd83)

### Which Options Did You Select?

Add To Startup, Discord Info, Fake Error, Kill Protector, Wifi Info, Ping, Anti Debug/VM, Minecraft Info, System Info, 2FA Codes, Browser Info, Roblox Info, Obfuscation, Injection

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Smug246** [comment]
what python version are you using?

**Comment by Luna122342** [comment]
> what python version are you using?

![image](https://github.com/Smug246/Luna-Grabber/assets/169272938/9800862c-6e89-4a97-8986-18ce7de39282)

**Comment by Smug246** [comment]
try downloading python version 3.11.6. thats what i currently use

**Comment by Luna122342** [comment]
![image](https://github.com/Smug246/Luna-Grabber/assets/169272938/99077c6e-a4f2-451c-9de6-c7237829b9ac)
![image](https://github.com/Smug246/Luna-Grabber/assets/169272938/b48c5435-44b4-4f4f-80ef-77a521ee170f)
Yes it works but this then?
![image](https://github.com/Smug246/Luna-Grabber/assets/169272938/5294d1db-9ad8-436c-8e48-f27b461b6f13)

**Comment by Smug246** [comment]
did u rebuild it or is that the same error from the other python version?

**Comment by Smug246** [comment]
rebuild it then if its a different python version?

**Comment by Luna122342** [comment]
how do i rebuild?

**Comment by Luna122342** [comment]
Yes i did that and i used this 
![image](https://github.com/Smug246/Luna-Grabber/assets/169272938/2e30ff89-ad10-479b-a7fe-a23567d82a38)

And when i executed it it said this Unable to find the order number 380 in the DLL file 
![image](https://github.com/Smug246/Luna-Grabber/assets/169272938/090d9e6e-b384-43b4-adf1-0d4a5d8accc3)

**Comment by Smug246** [comment]
can you record the console when its building so i can see if anything fails at all along the way.
