### ISSUE TITLE
Quest: Help me

### ISSUE THREAD

**Issue by Luna122342** [Smug246/Luna-Grabber#739]
### What Did You Expect To Happen?

How do i change this png i want to have another error 

### What Happened?

nothing i just want to change

### Add Screenshots

![image](https://github.com/Smug246/Luna-Grabber/assets/169272938/574047ad-8400-4b6f-aaf8-73857b86078e)

### Which Options Did You Select?

Fake Error

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Serpensin** [comment]
That's not an image. Look in luna.py for the definition of this.
