### ISSUE TITLE
Bug: Error when people try to open the file

### ISSUE THREAD

**Issue by darkeyxyz** [Smug246/Luna-Grabber#741]
### What Did You Expect To Happen?

To grab someone??

### What Happened?

They get an error "unhandled exception in script"

### Add Screenshots

![error](https://github.com/Smug246/Luna-Grabber/assets/169495106/da9ab30d-8089-43e2-92df-3687d43e4f40)

### Which Options Did You Select?

Discord Info, Fake Error, Kill Protector, Wifi Info, Ping, Minecraft Info, System Info, 2FA Codes, Browser Info, Roblox Info, Anti Spam, File Pumper, Clipboard

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Serpensin** [comment]
I guess, you didn't start the builder with the setup.bat? If you would've, it's not really possible, for this error to appear.

**Comment by darkeyxyz** [comment]
![image](https://github.com/Smug246/Luna-Grabber/assets/169495106/7074d3b8-dc77-403a-899f-c22396fa18c7)

when i open the setup.bat  this message pops up. what do i put there? i dont want to use Nuitka

**Comment by Smug246** [comment]
just type 1 and press enter
