### ISSUE TITLE
Bug: Can't choose a version of python

### ISSUE THREAD

**Issue by og420haze** [Smug246/Luna-Grabber#742]
### What Did You Expect To Happen?

gui to open

### What Happened?

If you want to use Nuitka, you need to select a version 3.4.X - 3.11.X
Enter the number of the desired Python version from the list above:

### Add Screenshots

![image](https://github.com/Smug246/Luna-Grabber/assets/169499393/cf567ef2-11e0-432b-814f-aaf57a58f4a4)

### Which Options Did You Select?

Discord Info

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by HyperBeamsX** [comment]
what was the solution? IM having the same issue
