### ISSUE TITLE
Bug: I put in the version and "invalid selection existing..." appears.

### ISSUE THREAD

**Issue by techbrainzx** [Smug246/Luna-Grabber#743]
### What Did You Expect To Happen?

put the version and open luna 

### What Happened?

when I open setup.bat and put in the python version (in this case 3.11.9) I get this message "invalid selection", is this a bug or am I doing something wrong?

### Add Screenshots

![image](https://github.com/Smug246/Luna-Grabber/assets/145053264/31500234-8694-4483-a57d-aea1a305c33e)

### Which Options Did You Select?

Add To Startup

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Smug246** [comment]
type 1 and press enter. it's asking which python version would you like to use from the list above. as there's only 1 python version found there's only 1 on the list. hope that makes sense

**Comment by Serpensin** [comment]
HEy @Smug246, can you please add my smurf (piko.piko.no.mi) on discord? My main is restricted atm.
