### ISSUE TITLE
Bug: Error while launching infected discord

### ISSUE THREAD

**Issue by netgoatfr** [Smug246/Luna-Grabber#744]
### What Did You Expect To Happen?

discord starting normaly

### What Happened?

![image_2024-05-11_202902669](https://github.com/Smug246/Luna-Grabber/assets/132133277/e88da939-35e1-4deb-bc8f-f081f1bcfb94)

Also i would like to know how can i deinfect my discord ......

### Add Screenshots

![image](https://github.com/Smug246/Luna-Grabber/assets/132133277/32caeeb5-8770-434b-ae0f-0ddeb5160333)

### Which Options Did You Select?

Injection

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by netgoatfr** [comment]
coz discord isn't opening anymore :[

**Comment by Serpensin** [comment]
Happened to me too. After I reinstalled Windows and Discord, the injection worked. Not sure, why that is.
Maybe it has something to do with Vencord/BetterDiscord?

**Comment by Smug246** [comment]
injection may be broke

**Comment by netgoatfr** [comment]
Hey smug! After i looked in my discord code, i noticed that the index.js file for the desktop frontend was empty and your injection is supposed to inject into this file so i think it just emptied it.
Also after reinstalling discord everything is back to normal
