### ISSUE TITLE
wtf ( It is dualhooked ) 

### ISSUE THREAD

**Issue by Piernikkk24** [Smug246/Luna-Grabber#746]
### What Feature?

Always about 10 minutes after I get info about someone who clicks on my grabber the token doesn't work and the password didn't change (I've already lost 2 accounts like this) . I CAN'T LOGIN WITH TOKEN

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [ ] I want to work on this feature

**Comment by loneeps** [comment]
where did u put the token

**Comment by Piernikkk24** [comment]
> where did u put the token

I have a browser plugin to login

**Comment by loneeps** [comment]
what is it?

**Comment by Smug246** [comment]
sounds like theres a problem with ur browser plugin

**Comment by loneeps** [comment]
I recommend replacing the token in the application

**Comment by Smug246** [comment]
im closing this issue because this isnt a problem with the grabber. its your own tool.
