### ISSUE TITLE
Question: How do I use the information provided in the "minecraft" folder?

### ISSUE THREAD

**Issue by TheBoss112233** [Smug246/Luna-Grabber#749]
### What Did You Expect To Happen?

I thought it was going to just list the accounts but it gives me a json file called accounts.json with a lot of access tokens to all of my accounts I have but I still do not know how to actually use it.

### What Happened?

So how do I actually login with it?

### Add Screenshots

![image](https://github.com/Smug246/Luna-Grabber/assets/33167203/6fa0f376-a55e-4322-822e-3e377f64a5e8)
![image](https://github.com/Smug246/Luna-Grabber/assets/33167203/a43a11bc-a0f8-46c5-94cb-63b81c6e7abc)

### Which Options Did You Select?

Minecraft Info

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Smug246** [comment]
look it up. i'm not gonna help with something that isn't actually a bug
