### ISSUE TITLE
Nuitka? 

### ISSUE THREAD

**Issue by HyperBeamsX** [Smug246/Luna-Grabber#750]
### What Did You Expect To Happen?

I expected this to work properly

### What Happened?

when i clicked the setup button it just shows this: "If you want to use Nuitka, you need to select a version 3.4.X-3.11.X
Enter the left number of the desired Python version from the list above

### Add Screenshots

![image](https://github.com/Smug246/Luna-Grabber/assets/169954931/59b0a7d1-aa77-4b35-bca4-8bd5eae9dd7c)

### Which Options Did You Select?

Add To Startup

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Smug246** [comment]
#743

**Comment by Hege333** [comment]
what do you mean @Smug246 ?

**Comment by Hege333** [comment]
this is also the issue for me

**Comment by Smug246** [comment]
use your eyes and read #743
