### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by HyperBeamsX** [Smug246/Luna-Grabber#751]
### What Did You Expect To Happen?

Expected to get all my info when testing

### What Happened?

Got zero

### Add Screenshots

nothing

### Which Options Did You Select?

Add To Startup, Disable Defender, Discord Info, Fake Error, 2FA Codes

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Smug246** [comment]
did u receive any error in the building process. check the end of the luna.log file

**Comment by HyperBeamsX** [comment]
well now the issue is even worse, i tried uninstalling everything and reinstall but now i cant even open anything. When i try to open the setup it just crashes, everything crashes

**Comment by HyperBeamsX** [comment]
got it to start up again, wdym luna.log

**Comment by HyperBeamsX** [comment]
i cant find luna.log

**Comment by Smug246** [comment]
closing as you have created a new issue
