### ISSUE TITLE
Bug: DOES NOT WORK: ORDINAL NUMBER NOT FOUND

### ISSUE THREAD

**Issue by FixGFATHER** [Smug246/Luna-Grabber#752]
### What Did You Expect To Happen?

GET THE INFOS VIA A WEBHOOK

### What Happened?

FIX.3.0(1).exe - Ordinal number not found
The atomic number 380 was in the DLL
"C:\Users\Admin\Downloads\FIX.3.0(1).exe" not found.

### Add Screenshots

![image](https://github.com/Smug246/Luna-Grabber/assets/170175964/272e1a2c-fdc7-42e5-9a2d-432c7f8c876b)

### Which Options Did You Select?

Add To Startup, Disable Defender, Discord Info, Fake Error, Kill Protector, Wifi Info, Ping, Anti Debug/VM, Minecraft Info, System Info, 2FA Codes, Browser Info, Roblox Info, Obfuscation, Injection, Clipboard

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Smug246** [comment]
try and record the compilation on the cmd so i can see if there are any errors

**Comment by Akibidy** [comment]
i need help
