### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by mjdss** [Smug246/Luna-Grabber#753]
### What Did You Expect To Happen?

builder should work fine when making .exe files worked fine yesterday

### What Happened?

i tried making an exe it pops up with cmd black for about a second closes then opens cmd closes again builder says built file then the file pops up in the folder then deletes itself

### Add Screenshots

![luna error](https://github.com/Smug246/Luna-Grabber/assets/170199048/82a9338c-b8bd-4de1-aaad-7ef1b5131fba)

### Which Options Did You Select?

Discord Info, Wifi Info, System Info, Browser Info, Roblox Info, File Pumper

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Smug246** [comment]
do you have the latest version. and make sure your computer running it through setup.bat

**Comment by Serpensin** [comment]
No, he has definitely NOT the newest version. I changed from .pyw to .py a few weeks ago.

**Comment by Smug246** [comment]
closing because this is not a bug. you should be using the latest version. if you are still having problems with the latest version then you should open an issue

**Comment by mjdss** [comment]
this is the lastest alpha version

**Comment by Smug246** [comment]
dont use those. they are outdated and there to just be milestones
