### ISSUE TITLE
Not getting any info

### ISSUE THREAD

**Issue by HyperBeamsX** [Smug246/Luna-Grabber#755]
### What Did You Expect To Happen?

Expected to get all the info that i selected in my discord webhook. Please take a look at the luna.log file. there was no message that it worked or anything

### What Happened?

Got nothing

### Add Screenshots

<img width="1038" alt="Screenshot 2024-05-19 at 5 56 40 PM" src="https://github.com/Smug246/Luna-Grabber/assets/169954931/37b601a3-9af4-4633-8508-b0d047be11c4">

### Which Options Did You Select?

Discord Info, Fake Error, Ping, Roblox Info

### How Did You Build The File?

Standard Python

### Did You Bind The File?

No

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by HyperBeamsX** [comment]
ye thats the entire point,m on #751 u told me to check the luna.log file to see any errors, which there were none as shown in the screenshot above, meaning there is a bug in ur grabber

**Comment by Smug246** [comment]
ye it seems discord changed some paths to steal from. this will be fixed soon. i'll notify you when there's an update

**Comment by HyperBeamsX** [comment]
alr thanks 👍

**Comment by HyperBeamsX** [comment]
Fixed yet? I see people who get this to work except for me.

**Comment by LunnaSmug246** [comment]
addme on Discord : Smug246
