### ISSUE TITLE
2 features

### ISSUE THREAD

**Issue by lcrn36** [Smug246/Luna-Grabber#756]
### What Feature?

make it so you can use this in a vm or try to at least and make it so you can control there pc if you can thanks.

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I want to work on this feature

**Comment by Serpensin** [comment]
Bruh. You can already use this in a VM. We also probably will never add the ability to control a PC, since this is a Grabber and NOT a RAT.
