### ISSUE TITLE
HELP ME

### ISSUE THREAD

**Issue by lake123454** [Smug246/Luna-Grabber#758]
### What Did You Expect To Happen?

![image](https://github.com/Smug246/Luna-Grabber/assets/128163333/8392c4a9-677e-48fe-8420-edd275522b1b)

### What Happened?

when ever i click setup this pops up and idk what to put there please help me

### Add Screenshots

![image](https://github.com/Smug246/Luna-Grabber/assets/128163333/9f46ffa3-a1f0-4897-8614-d9400fd9c1af)

### Which Options Did You Select?

Disable Defender

### How Did You Build The File?

Standard Python

### Did You Bind The File?

Yes (Execute on Startup)

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by mjdss** [comment]
happened to me too

**Comment by Serpensin** [comment]
> can you guys not read. pick the option from the list above

If you think, you made it idiot proof, they make a better idiot.

**Comment by mjdss** [comment]
> > can you guys not read. pick the option from the list above
> 
> If you think, you made it idiot proof, they make a better idiot.

theres no need to be toxic its just making it confusing for people who are new to this

**Comment by Serpensin** [comment]
Yo

> > > can you guys not read. pick the option from the list above
> > 
> > 
> > If you think, you made it idiot proof, they make a better idiot.
> 
> theres no need to be toxic its just making it confusing for people who are new to this

Skidds get dumber every day. XD

**Comment by Smug246** [comment]
this isn't being toxic this is you not being able to read. because you checked the option that says "I have checked the existing issues". when you clearly haven't as there are about 10 other issues of people asking the same question.
