### ISSUE TITLE
Bug: le build marche pas

### ISSUE THREAD

**Issue by WITCHO12** [Smug246/Luna-Grabber#759]
### What Did You Expect To Happen?

quand je build le virus il n'apparait pas dans le fichier luna main

### What Happened?

quand je build le virus il n'apparait pas dans le fichier luna main

### Add Screenshots

![image](https://github.com/Smug246/Luna-Grabber/assets/128751389/6624ea37-5fbb-41fe-92b1-e5918baddb3f)

### Which Options Did You Select?

Discord Info

### How Did You Build The File?

Pyinstaller

### Did You Bind The File?

Yes (Execute on Startup)

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Smug246** [comment]
can you please translate to english

**Comment by WITCHO12** [comment]
when I build the virus it does not appear in my luna grabber main folder

**Comment by LunnaSmug246** [comment]
addme on Discord : Smug246

**Comment by Smug246** [comment]
have you disabled antivirus because it will detect it and delete it
