### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by AncientPunishers** [Smug246/Luna-Grabber#760]
### What Did You Expect To Happen?

fix

### What Happened?

built the file then run it this error came up

### Add Screenshots

![image](https://github.com/Smug246/Luna-Grabber/assets/122560099/63b4f089-016c-4b67-a495-d07e1079a628)

### Which Options Did You Select?

Discord Info, Fake Error, Games, Wifi Info, System Info, Common Files, Browser Info, Roblox Info, Obfuscation, Injection, Clipboard, Webcam, Wallets

### How Did You Build The File?

Pyinstaller

### Did You Bind The File?

No

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Smug246** [comment]
this should be fixed in latest update

**Comment by Smug246** [comment]
> @Smug246 why is my python installation not detected? I ran setup file it still says not found

have u installed it from the official website and added it to your path

**Comment by LongYears9** [comment]
@Smug246 Yeah

**Comment by Smug246** [comment]
> @Smug246 Yeah

you must've done something wrong then because it will appear if done correctly. try deleting all python versions so none interfere.  then install the python version you want

**Comment by LongYears9** [comment]
okay i'll try and post an update. Thanks!
