### ISSUE TITLE
Bug: Error code  

### ISSUE THREAD

**Issue by darkeyxyz** [Smug246/Luna-Grabber#761]
### What Did You Expect To Happen?

What even is this question. I expect it to work??

### What Happened?

getting code "Traceback (most recent call last):
  File "zoomer.py", line 12, in <module>
ModuleNotFoundError: No module named 'pyperclip'"

### Add Screenshots

.

### Which Options Did You Select?

Disable Defender, Discord Info, Fake Error, Games, Wifi Info, Ping, System Info, Common Files, Browser Info, Roblox Info, Obfuscation, Injection, Anti Spam, File Pumper, Clipboard, Webcam, Wallets

### How Did You Build The File?

Pyinstaller

### Did You Bind The File?

No

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by darkeyxyz** [comment]
![image](https://github.com/Smug246/Luna-Grabber/assets/169495106/8e5eebc6-bf6c-46a8-80cc-b8e7d5062093)

this comes when someone tries to open the file

**Comment by Smug246** [comment]
make sure your using the latest version of this grabber

**Comment by darkeyxyz** [comment]
I am using the latest version

**Comment by Smug246** [comment]
if you've installed pyperclip correctly it should work fine. try "pip install pyperclip"

**Comment by LongYears9** [comment]
the module is not there in yours

**Comment by HyperBeamsX** [comment]
how do we find latest version of luna grabber?

**Comment by Smug246** [comment]
run setup.bat and it will tell you
