### ISSUE TITLE
FATAL: Error, failed to locate module 'browser-cookie3' you asked to include.

### ISSUE THREAD

**Issue by moxze14** [Smug246/Luna-Grabber#762]
### What Did You Expect To Happen?

This is the error I get when I try to build can someone help me fix this please ?

### What Happened?

When I tried to build I got this error FATAL: Error, failed to locate module 'browser-cookie3' you asked to include.

### Add Screenshots

![image_2024-05-21_122448640](https://github.com/Smug246/Luna-Grabber/assets/170332178/8dbae52d-b138-4e48-b446-97e7b094e30a)

### Which Options Did You Select?

Discord Info, Fake Error, Games, Wifi Info, System Info, Common Files, Browser Info, Roblox Info

### How Did You Build The File?

Nuitka

### Did You Bind The File?

No

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by ImiFadedxD** [comment]
same error

**Comment by Shinobitemper** [comment]
dont fully know if this would fix it yet but  check out the requirements note file and download those aka 
These-

# Logger
cryptography
opencv-python
psutil
pycountry
pyperclip
pypiwin32
requests
requests-toolbelt
wmi
pyaesm
browser-cookie3
# Builder
colorama
customtkinter
nuitka
packaging
pillow
pycryptodomex
pyinstaller

**Comment by Kempeter** [comment]
Go to the project dir and type "py -m pip install -r requirements.txt"
