### ISSUE TITLE
 Bug: it keeps saying choose between python versions

### ISSUE THREAD

**Issue by asdasdsad213** [Smug246/Luna-Grabber#765]
### What Did You Expect To Happen?

help

### What Happened?

it keeps saying choose between versions but what i type its always wrong

### Add Screenshots

![image](https://github.com/Smug246/Luna-Grabber/assets/170471440/62b37813-80fd-4b16-9220-5426d3b99f0b)

### Which Options Did You Select?

Discord Info

### How Did You Build The File?

Standard Python

### Did You Bind The File?

Yes (Execute on Startup)

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by KanteV2** [comment]
All you have to do is type the number 1 into the **console** and press _enter_. (I found this from #750)
