### ISSUE TITLE
Bug: Luna grabber doesnt work

### ISSUE THREAD

**Issue by Furkankkrturk** [Smug246/Luna-Grabber#767]
### What Did You Expect To Happen?

i was waiting for luna grabber setup to work but it asks for a python password or something its scatie

### What Happened?

/

### Add Screenshots

/

### Which Options Did You Select?

Injection, File Pumper

### How Did You Build The File?

Nuitka

### Did You Bind The File?

Yes (Don't execute on startup)

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by mohazab96** [comment]
addme on Discord : Smug246

**Comment by Smug246** [comment]
can you ss where it asks for a password

**Comment by Furkankkrturk** [comment]
Yes just wait I’m in school now

**Comment by Furkankkrturk** [comment]
here it is @Smug246 
![image](https://github.com/Smug246/Luna-Grabber/assets/170673542/120004a0-3099-4d87-bcff-08eded40c11e)

**Comment by Kempeter** [comment]
Download this python version: [Python 11.x](https://www.python.org/downloads/release/python-3119/)

**Comment by Furkankkrturk** [comment]
still nothing

**Comment by Kempeter** [comment]
Can you take a screenshot?

**Comment by Furkankkrturk** [comment]
alraedy did and snd it

**Comment by Furkankkrturk** [comment]
![Desktop Screenshot 2024 05 24 - 13 28 34 93](https://github.com/Smug246/Luna-Grabber/assets/170673542/9e2a7fc6-a802-46d3-9616-64daade08f91)

**Comment by Furkankkrturk** [comment]
![Desktop Screenshot 2024 05 24 - 13 28 46 22](https://github.com/Smug246/Luna-Grabber/assets/170673542/31d9ed41-8d1c-4cb7-a32d-af22f2f2fe55)

**Comment by Smug246** [comment]
omg are you guys illiterate or something. read what it says slowly. all you need to do is press number 1 then enter

**Comment by Furkankkrturk** [comment]
cant press anything or it closses

**Comment by Smug246** [comment]
> here it is @Smug246 
> 
> ![image](https://github.com/Smug246/Luna-Grabber/assets/170673542/120004a0-3099-4d87-bcff-08eded40c11e)
> 
> 
> 
> 

your supposed to press 1 here. why is it saying you don't have python anymore. did you install it and add it to path

**Comment by Furkankkrturk** [comment]
yah

**Comment by Furkankkrturk** [comment]
But how do i add to path?

**Comment by Kempeter** [comment]
[Add python to path](https://realpython.com/add-python-to-path/)

**Comment by Furkankkrturk** [comment]
Still nothing

**Comment by Smug246** [comment]
so stupid. press 1 and then press enter
