### ISSUE TITLE
Bug: build doesnt work

### ISSUE THREAD

**Issue by WITCHO12** [Smug246/Luna-Grabber#768]
### What Did You Expect To Happen?

when I build the virus it does not appear in my luna grabber main folder

### What Happened?

when I build the virus it does not appear in my luna grabber main folder

### Add Screenshots

![333651604-7a8225ce-b9c4-4bc3-ad7b-bc988948ea24](https://github.com/Smug246/Luna-Grabber/assets/128751389/f1200aef-e16f-4b17-8c43-0585ae9c57ea)

### Which Options Did You Select?

Add To Startup

### How Did You Build The File?

Pyinstaller

### Did You Bind The File?

Yes (Execute on Startup)

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Smug246** [comment]
download the latest version
