### ISSUE TITLE
Bug: How to open Nuitka

### ISSUE THREAD

**Issue by 3leczka** [Smug246/Luna-Grabber#769]
### What Did You Expect To Happen?

How I can use Nuitka?

### What Happened?

ss

### Add Screenshots

ss

### Which Options Did You Select?

Anti Debug/VM, Clipboard

### How Did You Build The File?

Nuitka

### Did You Bind The File?

Yes (Execute on Startup)

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Smug246** [comment]
read the instructions on setup.bat
