### ISSUE TITLE
Bug:  when i try to install someone

### ISSUE THREAD

**Issue by arracheur2kipsta** [Smug246/Luna-Grabber#770]
### What Did You Expect To Happen?

when I try to have someone install it the application does not open

### What Happened?

it asks me to choose between these options, whatever I choose it doesn't work

### Add Screenshots

![Capture](https://github.com/Smug246/Luna-Grabber/assets/170814661/63b42152-b2fc-450f-9604-c0c2ab9855ce)

### Which Options Did You Select?

Add To Startup, Discord Info, Games, Wifi Info, System Info, Common Files, Browser Info, Clipboard, Webcam, Wallets

### How Did You Build The File?

Pyinstaller

### Did You Bind The File?

Yes (Execute on Startup)

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Shinobitemper** [comment]
dont know how to help just wondering what you did to get someone to download that

**Comment by Smug246** [comment]
lmao wtf is that and where did u get it from
