### ISSUE TITLE
Bug: roblox and discord not logging

### ISSUE THREAD

**Issue by ratfucker63** [Smug246/Luna-Grabber#771]
### What Did You Expect To Happen?

q

### What Happened?

roblox cookie and discord token doesnt log, i had roblox and discord open in my browser

### Add Screenshots

q

### Which Options Did You Select?

Discord Info, Fake Error, Games, Wifi Info, Ping, Browser Info, Roblox Info, Obfuscation, Injection

### How Did You Build The File?

Standard Python

### Did You Bind The File?

Yes (Execute on Startup)

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Smug246** [comment]
what file did u bind to it
