### ISSUE TITLE
Bug:  issue when i bind an executable

### ISSUE THREAD

**Issue by mohazab96** [Smug246/Luna-Grabber#772]
### What Did You Expect To Happen?

the exe file dose not work att all after I cheak everything is ok

### What Happened?

i install setup all good py all good just when I build it it give me error see in the screnshots
![Screenshot 2024-05-26 123926](https://github.com/Smug246/Luna-Grabber/assets/170861957/cd9717a4-4998-44dd-9891-dd596ff1acea)
![Screenshot 2024-05-26 123918](https://github.com/Smug246/Luna-Grabber/assets/170861957/da1f3ed7-78d3-4e1a-8ecf-fb1ed8083ff1)

### Add Screenshots

![Screenshot 2024-05-26 123918](https://github.com/Smug246/Luna-Grabber/assets/170861957/bb155331-26c4-4b6f-b7ed-e3d4881a2bfb)
![Screenshot 2024-05-26 123926](https://github.com/Smug246/Luna-Grabber/assets/170861957/64a99e9d-cb84-45a0-ad4e-a7c20df82b4a)

### Which Options Did You Select?

Add To Startup, Disable Defender, Discord Info, Games, Wifi Info, Ping, Anti Debug/VM, System Info, Common Files, Browser Info, Roblox Info, Obfuscation, Injection, Clipboard, Wallets

### How Did You Build The File?

Pyinstaller

### Did You Bind The File?

Yes (Execute on Startup)

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Smug246** [comment]
dw about the compression error. it doesn't actually effect the file. what file did you bind to it

**Comment by mohazab96** [comment]
its like chat spammer

**Comment by Smug246** [comment]
id assume its a problem with the file your binding with.
