### ISSUE TITLE
Bug: Not detecting python, even though it is installed 

### ISSUE THREAD

**Issue by LongYears9** [Smug246/Luna-Grabber#773]
### What Did You Expect To Happen?

load lol

### What Happened?

Not detecting python, even though it is installed 

### Add Screenshots

![Screenshot 2024-05-26 213206](https://github.com/Smug246/Luna-Grabber/assets/112838308/aa430864-708d-4093-b194-bb4e8892d7c7)

### Which Options Did You Select?

Add To Startup

### How Did You Build The File?

Standard Python

### Did You Bind The File?

No

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by mohazab96** [comment]
uninstall py and reinstall it on start instaliotn setup chose add to setup or send your discord to show you how

**Comment by LongYears9** [comment]
main:  pangod9
alt:      onlyanna.695
