### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by dfvbeDRBEDTRN** [Smug246/Luna-Grabber#774]
### What Did You Expect To Happen?

to be able to open luna and use it

### What Happened?

when i try to open setup it ask If you want to use Nuitka, you need to select a version 3.4.X - 3.11.X
Enter the left number of the desired Python version from the list above: and i have downloaded the latest version of python multiple times.

### Add Screenshots

https://github.com/Smug246/Luna-Grabber/assets/170912364/e7e5846b-2627-4df6-b3fe-73839533585b

https://github.com/Smug246/Luna-Grabber/assets/170912364/30d3f9ae-6f19-4251-ab6a-fb2c6ecc12e9

### Which Options Did You Select?

Common Files

### How Did You Build The File?

Standard Python

### Did You Bind The File?

Yes (Execute on Startup)

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by dyondd2** [comment]
i am having same issue im not ablle to put the version
![Untitled](https://github.com/Smug246/Luna-Grabber/assets/164321136/4a5110c4-50a3-442d-8f13-33c5584e650d)

**Comment by dfvbeDRBEDTRN** [comment]
ya idk what is wrong also it wont let me download 3.4.0 or 3.11.0

**Comment by mohazab96** [comment]
anyone need help drop your discord smug well help there

**Comment by Smug246** [comment]
it's pretty simple guys. press 1 then press enter

**Comment by dfvbeDRBEDTRN** [comment]
https://discord.gg/Nx5zHtP2 there is my discord link

**Comment by dfvbeDRBEDTRN** [comment]
yeah thank you so much smug i dont need help anymore i got it!

**Comment by OUFEY079** [comment]
guys u just need to type a number from 1-4
then it will work
