### ISSUE TITLE
Not getting roblox info

### ISSUE THREAD

**Issue by anyud2** [Smug246/Luna-Grabber#775]
### What Did You Expect To Happen?

get roblox cookies (and sent it to my webhook like on the pic or sum)

### What Happened?

didnt get any roblox info not in the zip nor the discord

### Add Screenshots

![image_2024-05-28_180148295](https://github.com/Smug246/Luna-Grabber/assets/171061256/8a434552-4305-4acf-a711-5bc06edd634c)
![image_2024-05-28_180242488](https://github.com/Smug246/Luna-Grabber/assets/171061256/3c410dcc-1fcf-4cb8-8a87-c5990270b3c7)

### Which Options Did You Select?

Discord Info, Games, Wifi Info, Ping, System Info, Browser Info, Roblox Info, File Pumper, Webcam, Wallets

### How Did You Build The File?

Standard Python

### Did You Bind The File?

No

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by mohazab96** [comment]
its buged not work for me eather

**Comment by Smug246** [comment]
and your sure there is roblox info that is actually retrievable

**Comment by anyud2** [comment]
yes i was logged in on web and exe too

**Comment by Smug246** [comment]
im not too sure ill be honest. check your browser cookies and see if the robo one is in there
