### ISSUE TITLE
how to fix?

### ISSUE THREAD

**Issue by Akibidy** [Smug246/Luna-Grabber#776]
### What Did You Expect To Happen?

load?

### What Happened?

its saying If you want to use Nuitka, you need to select a version 3.4.X - 3.11.X
Enter the left number of the desired Python version from the list above:
how do i fix?

### Add Screenshots

nu uh

### Which Options Did You Select?

Add To Startup

### How Did You Build The File?

Standard Python

### Did You Bind The File?

No

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Akibidy** [comment]
I tried to donload nuitka but idk how to find version 3.4 or 3.11

**Comment by Smug246** [comment]
lmao press 1 then press enter

**Comment by Akibidy** [comment]
wdym

**Comment by Akibidy** [comment]
whats that gonna do anyways

**Comment by Akibidy** [comment]
thx

**Comment by Akibidy** [comment]
works now

**Comment by Akibidy** [comment]
but where the gui?
it just sends me to a venv file

**Comment by Akibidy** [comment]
Ohhhh found it

**Comment by Akibidy** [comment]
Thx
