### ISSUE TITLE
Bug: not logging my discord info and just sending blank messages

### ISSUE THREAD

**Issue by sxury999** [Smug246/Luna-Grabber#777]
### What Did You Expect To Happen?

for it to send

### What Happened?

it just sent blank messages

### Add Screenshots

![Screenshot 2024-05-31 215934](https://github.com/Smug246/Luna-Grabber/assets/170886134/2f385509-76d2-4539-9db2-956f718f8a65)

### Which Options Did You Select?

Disable Defender, Discord Info, Fake Error, Games, Wifi Info, Ping, Anti Debug/VM, System Info, Common Files, Browser Info, Roblox Info, Obfuscation, Injection, Anti Spam, Clipboard, Webcam, Wallets

### How Did You Build The File?

Pyinstaller

### Did You Bind The File?

Yes (Don't execute on startup)

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Smug246** [comment]
probably because of whatever u binded it with

**Comment by Smug246** [comment]
this is fixed in new update

**Comment by sxury999** [comment]
i have the new update and i dident bind it to anything

**Comment by sxury999** [comment]
after i binded it i did a unbinded one
