### ISSUE TITLE
bug: everytime i open stup or builder it justr close real quick nothing is working

### ISSUE THREAD

**Issue by mrcox224** [Smug246/Luna-Grabber#779]
### What Did You Expect To Happen?

everytime i open stup or builder it justr close real quick nothing is working

### What Happened?

everytime i open stup or builder it justr close real quick nothing is working

### Add Screenshots

everytime i open stup or builder it justr close real quick nothing is working

### Which Options Did You Select?

Disable Defender

### How Did You Build The File?

Standard Python

### Did You Bind The File?

Yes (Execute on Startup)

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Smug246** [comment]
could you show a recording of you trying to open setup.bat?

**Comment by jamiekarvans** [comment]
same problem it just pops up really quick with no logs showing and closes in less than 1 second

**Comment by mrcox224** [comment]
alr ill record

**Comment by mrcox224** [comment]
https://github.com/Smug246/Luna-Grabber/assets/171459342/115dac94-dc1c-432c-8449-74ea0e77bee6

**Comment by mrcox224** [comment]
here is the video even after i redownload it it does the same

**Comment by Smug246** [comment]
run it through cmd and it will show you the error
