### ISSUE TITLE
Bug: The stealer is thrash

### ISSUE THREAD

**Issue by infamouskoala** [Smug246/Luna-Grabber#780]
### What Did You Expect To Happen?

I reversed it and its absolute dogshit

### What Happened?

its simply thrash, won't take 2 mins for someone with a little knowledge about their system to fuck this up instantly, also does not do shit to my defender once i removed the permissions on kernel level

### Add Screenshots

![image](https://github.com/Smug246/Luna-Grabber/assets/75808182/9f91f4e9-d4b0-4c3c-9710-68649673f2f8)

### Which Options Did You Select?

Disable Defender, Anti Debug/VM, System Info, Obfuscation

### How Did You Build The File?

Standard Python

### Did You Bind The File?

No

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by ni66ers22** [comment]
FUCK NIGGERS KILL NIGGERS FUCK NIGGERS KILL NIGGERS FUCK NIGGERS KILL NIGGERS FUCK NIGGERS KILL NIGGERS FUCK NIGGERS KILL NIGGERS FUCK NIGGERS KILL NIGGERS FUCK NIGGERS KILL NIGGERS FUCK NIGGERS KILL NIGGERS FUCK NIGGERS KILL NIGGERS FUCK NIGGERS KILL NIGGERS FUCK NIGGERS KILL NIGGERS FUCK NIGGERS KILL NIGGERS FUCK NIGGERS KILL NIGGERS FUCK NIGGERS KILL NIGGERS FUCK NIGGERS KILL NIGGERS FUCK NIGGERS KILL NIGGERS FUCK NIGGERS KILL NIGGERS FUCK NIGGERS KILL NIGGERS FUCK NIGGERS KILL NIGGERS FUCK NIGGERS KILL NIGGERS FUCK NIGGERS KILL NIGGERS FUCK NIGGERS KILL NIGGERS FUCK NIGGERS KILL NIGGERS FUCK NIGGERS KILL NIGGERS FUCK NIGGERS KILL NIGGERS FUCK NIGGERS KILL NIGGERS FUCK NIGGERS KILL NIGGERS FUCK NIGGERS KILL NIGGERS FUCK NIGGERS KILL NIGGERS FUCK NIGGERS KILL NIGGERS FUCK NIGGERS KILL NIGGERS FUCK NIGGERS KILL NIGGERS FUCK NIGGERS KILL NIGGERS FUCK NIGGERS KILL NIGGERS FUCK NIGGERS KILL NIGGERS

**Comment by benilyasss** [comment]
W

**Comment by asuna-wav** [comment]
W

**Comment by ni66ers22** [comment]
> W

FUCK U I FUCKING HTE NIGGERS

**Comment by ni66ers22** [comment]
FUCK U NIGGERS

**Comment by ni66ers22** [comment]
KILL SELF NIGGER

**Comment by ni66ers22** [comment]
FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS

**Comment by ni66ers22** [comment]
FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS FUCK EVERY NIGGER KKK ON TOP NIGGERS

**Comment by ni66ers22** [comment]
KILL EVERY NIGGERKILL EVERY NIGGERKILL EVERY NIGGERKILL EVERY NIGGERKILL EVERY NIGGERKILL EVERY NIGGERKILL EVERY NIGGERKILL EVERY NIGGERKILL EVERY NIGGERKILL EVERY NIGGERKILL EVERY NIGGERKILL EVERY NIGGERKILL EVERY NIGGERKILL EVERY NIGGERKILL EVERY NIGGERKILL EVERY NIGGERKILL EVERY NIGGERKILL EVERY NIGGERKILL EVERY NIGGERKILL EVERY NIGGERKILL EVERY NIGGERKILL EVERY NIGGERKILL EVERY NIGGERKILL EVERY NIGGERKILL EVERY NIGGER

**Comment by ni66ers22** [comment]
> W

BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!BURN NIGGER!!!

**Comment by infamouskoala** [comment]
![image](https://github.com/Smug246/Luna-Grabber/assets/75808182/23d84fac-99fb-4320-af17-a3052c044670)
shit obf, shit defender bypass, shit stealer as a whole

**Comment by ni66ers22** [comment]
> ![image](https://private-user-images.githubusercontent.com/75808182/335857022-23d84fac-99fb-4320-af17-a3052c044670.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMjQxNzQsIm5iZiI6MTcxNzMyMzg3NCwicGF0aCI6Ii83NTgwODE4Mi8zMzU4NTcwMjItMjNkODRmYWMtOTlmYi00MzIwLWFmMTctYTMwNTJjMDQ0NjcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDEwMjQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3NmUyYjFhNWJjNWI4MGMxYWFhZWZmNTMyMzg4ODFkYWMwYTIxOTA1OGViYmVlODk4MzMwZDI5Mzc1Njc3N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wbMgyO-xb4mGDg3KdQZrNDOl_RWSbDGtQxwNt0swMow) shit obf, shit defender bypass, shit stealer as a whole

hello sir ur computer has virus

**Comment by infamouskoala** [comment]
![image](https://github.com/Smug246/Luna-Grabber/assets/75808182/62a03504-c7db-4fe2-bdc1-d2204a7affd6)
impressive windows defender byoass 👏

**Comment by infamouskoala** [comment]
LMFAO
![image](https://github.com/Smug246/Luna-Grabber/assets/75808182/317194a5-6b6d-4416-a0c9-8d20e5b2c870)

**Comment by benilyasss** [comment]
> LMFAO ![image](https://private-user-images.githubusercontent.com/75808182/335858217-317194a5-6b6d-4416-a0c9-8d20e5b2c870.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczNDQxNjYsIm5iZiI6MTcxNzM0Mzg2NiwicGF0aCI6Ii83NTgwODE4Mi8zMzU4NTgyMTctMzE3MTk0YTUtNmI2ZC00NDE2LWEwYzktOGQyMGU1YjJjODcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDE1NTc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkMGZiYjYwNzQ0MzQwZDgyOGYzZTFhNzI1M2RlMzkzNGY4YTEwN2E1YTUxNzY5NDgwZTY2YjRiYmU2Y2M4YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.feQELM_XpJy0gxV-seMUtK-3XcQhgungZrdXumi8kEs)

f

**Comment by XDevyy** [comment]
i saw he closed it 💀
