### ISSUE TITLE
Bug: Built files aren't showing up in the Luna grabber main folder

### ISSUE THREAD

**Issue by throwaway5761** [Smug246/Luna-Grabber#781]
### What Did You Expect To Happen?

When i build the file (.py) i expected it to appear in an easily accessible folder such as the luna grabber main folder

### What Happened?

The file i built is nowhere to be found on my device even after repeatedly tinkering w/ settings and looking in different places. at times i did attempt to bind the file but that did nothing.

### Add Screenshots

[https://media.discordapp.net/attachments/1214690374262456423/1247348328942014534/image_2024-06-03_203653529.png?ex=665fb328&is=665e61a8&hm=2e9838a6f539f7b45fc2525d3ce96ef02bbe31d28cd6c46f9c56176276f0291c&=&format=webp&quality=lossless&width=692&height=389](url)

### Which Options Did You Select?

Discord Info, Anti Debug/VM, Roblox Info

### How Did You Build The File?

Standard Python

### Did You Bind The File?

No

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Smug246** [comment]
that screenshot shows me nothing

**Comment by throwaway5761** [comment]
idrk what i can show u cuz theres no file coming up when i create one w/ builder even when the criteria to build it is met

**Comment by throwaway5761** [comment]
to add onto that, when i build .exe it appears but i cant do anything w/ it
