### ISSUE TITLE
Bug: when opening the .exe nothing sends in the webhook.

### ISSUE THREAD

**Issue by cursed2goated** [Smug246/Luna-Grabber#782]
### What Did You Expect To Happen?

Info to be sent in the server

### What Happened?

Building takes ages (about 30 minutes) and in the end the .exe file doesn't send any info to the webhook

### Add Screenshots

![image](https://github.com/Smug246/Luna-Grabber/assets/131124939/1b1e9dd8-3ffa-4f4f-b3da-278438d5a7b3)
![image](https://github.com/Smug246/Luna-Grabber/assets/131124939/ef2018ea-3846-48dc-907c-2d876c80f304)
![image](https://github.com/Smug246/Luna-Grabber/assets/131124939/42b33df6-5a01-44b1-864b-dfcdcd52e806)
![image](https://github.com/Smug246/Luna-Grabber/assets/131124939/60c1a1ea-369e-4e46-a026-feac2a5b30b1)

### Which Options Did You Select?

Add To Startup, Disable Defender, Discord Info, Games, Wifi Info, Ping, Anti Debug/VM, System Info, Common Files, Browser Info, Roblox Info, Obfuscation, Injection, Anti Spam, Webcam, Wallets

### How Did You Build The File?

Nuitka

### Did You Bind The File?

Yes (Don't execute on startup)

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [x] I have attempted to resolve my problem by myself

**Comment by CatIsTruck** [comment]
Same issue

**Comment by Smug246** [comment]
turn the obfuscation off and try

**Comment by cursed2goated** [comment]
> turn the obfuscation off and try

i will get nuked instantly if i turn off obfuscation
