### ISSUE TITLE
Bug: The file created by builder is launched with an error

### ISSUE THREAD

**Issue by JennTays** [Smug246/Luna-Grabber#783]
### What Did You Expect To Happen?

See how the functions work

### What Happened?

When launching an exe file, an error appears related to some option in the file loader-o.py, which as I understand appears during the file building. I tried turning on and off different options, building through pyinstaller and nuitka, but almost nothing changed, except for the option name in error

### Add Screenshots

![photo_2024-06-07_19-35-08](https://github.com/Smug246/Luna-Grabber/assets/172068322/6aa47df1-6a35-4689-8eec-2a078ba39b9f)

### Which Options Did You Select?

Add To Startup, Disable Defender, Discord Info, Fake Error, Games, Ping, Anti Debug/VM, System Info, Common Files, Browser Info, Injection, File Pumper, Wallets

### How Did You Build The File?

Pyinstaller

### Did You Bind The File?

No

### Check the following before submitting (If Applicable)

- [x] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Smug246** [comment]
turn fake error off and see if it works

**Comment by JennTays** [comment]
> turn fake error off and see if it works

I've already tried and not only with this feature. As I said the same error starts popping up, only because of another function, if you disable it too, you will get another function.

**Comment by JennTays** [comment]
> turn fake error off and see if it works

![w](https://github.com/Smug246/Luna-Grabber/assets/172068322/5a3b1e67-3c6f-413e-aab6-4f3f72f76221)

**Comment by JennTays** [comment]
> turn fake error off and see if it works

Are there any options for solving this problem?

**Comment by Smug246** [comment]
im not sure tbh. it works fine for me. what python version do you use?
