### ISSUE TITLE
Bug: Setup

### ISSUE THREAD

**Issue by Mik5671155** [Smug246/Luna-Grabber#784]
### What Did You Expect To Happen?

.

### What Happened?

when I press the setup.bat file it tells me to select a Python version and I don't know what to select.
Here is what it says: Found Python version 3.11.9
If you want to use Nuitka you need to select a version 3.4.X - 3.11.X
Enter the left number of the desired python version from the list above

can someone tell me what to put

### Add Screenshots

.

### Which Options Did You Select?

Fake Error

### How Did You Build The File?

Pyinstaller

### Did You Bind The File?

Yes (Execute on Startup)

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by dizzzzzzystore** [comment]
put 1 or 2 lmao it legit says what to do, the number on the very left of the python version for exampl
1) x.x.x
2) x.x.x
