### ISSUE TITLE
Bug:  doesnt open and i have done everything on the issues and followed 100 tutorials

### ISSUE THREAD

**Issue by sigmamsdka** [Smug246/Luna-Grabber#785]
### What Did You Expect To Happen?

the .bat to work like it did on my old pc

### What Happened?

it didnt so i tried doing the cmd thingy and it says unexpected

### Add Screenshots

![image](https://github.com/Smug246/Luna-Grabber/assets/172088270/2beb6745-e4d4-46d1-bbec-8b8bd95dc149)

### Which Options Did You Select?

Discord Info

### How Did You Build The File?

Standard Python

### Did You Bind The File?

No

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Tomdinchaina** [comment]
I have the same problem
