### ISSUE TITLE
Bug: "no such file or directory as loader.py"

### ISSUE THREAD

**Issue by dizzzzzzystore** [Smug246/Luna-Grabber#786]
### What Did You Expect To Happen?

it to work

### What Happened?

When pressing build it says "no such file or directory as loader.py"

### Add Screenshots

![image_2024-06-08_184955232](https://github.com/Smug246/Luna-Grabber/assets/169458832/4a3d9f2c-1048-448a-b011-0e026dc25737)

### Which Options Did You Select?

Add To Startup, Discord Info, Fake Error, Games, Wifi Info, Ping, Anti Debug/VM, System Info, Common Files, Browser Info, Roblox Info, Obfuscation, Injection, Anti Spam, Clipboard, Webcam, Wallets

### How Did You Build The File?

Nuitka

### Did You Bind The File?

Yes (Execute on Startup)

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Tomdinchaina** [comment]
same problem, did you fix it?

**Comment by Smug246** [comment]
download the latest version again. i dont why but your missing files. maybe your antivirus deleted it or you did by mistake
