### ISSUE TITLE
Bug: error after building

### ISSUE THREAD

**Issue by DrumiNNn** [Smug246/Luna-Grabber#787]
### What Did You Expect To Happen?

build

### What Happened?

error

### Add Screenshots

![image](https://github.com/Smug246/Luna-Grabber/assets/164747900/e7acc937-17c8-4c4e-bf06-e4fe5f0266f5)
![image](https://github.com/Smug246/Luna-Grabber/assets/164747900/e7acc937-17c8-4c4e-bf06-e4fe5f0266f5)

### Which Options Did You Select?

Add To Startup

### How Did You Build The File?

Pyinstaller

### Did You Bind The File?

No

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Tomdinchaina** [comment]
same problem, did you fix it?

**Comment by Smug246** [comment]
can you give me the steps you took to recreate that so i can see if that happens for me

**Comment by Smug246** [comment]
nvm latest version i fixed this
