### ISSUE TITLE
Bug: setup failed

### ISSUE THREAD

**Issue by nrgs1ke** [Smug246/Luna-Grabber#788]
### What Did You Expect To Happen?

work

### What Happened?

i ran the setup and at the end it said setup failed

### Add Screenshots

![Screenshot 2024-06-09 211128](https://github.com/Smug246/Luna-Grabber/assets/172208934/b73d4ddd-24be-4593-9904-0f6f30d21ab1)
![Screenshot 2024-06-09 211134](https://github.com/Smug246/Luna-Grabber/assets/172208934/b375a9fc-f21a-4507-a44f-a434a61f004f)

### Which Options Did You Select?

Add To Startup

### How Did You Build The File?

Standard Python

### Did You Bind The File?

Yes (Execute on Startup)

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Smug246** [comment]
what python version are you using

**Comment by Smug246** [comment]
closing as as stale because you havnt responded
