### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by weegeer** [Smug246/Luna-Grabber#789]
### What Did You Expect To Happen?

i expected it to build it

### What Happened?

idk how to get past this screen, i selected discord info here bc there was no build error thing

### Add Screenshots

![image](https://github.com/Smug246/Luna-Grabber/assets/137427565/103002ea-506d-45d0-abe5-74d0260f0919)

### Which Options Did You Select?

Discord Info

### How Did You Build The File?

Standard Python

### Did You Bind The File?

Yes (Execute on Startup)

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Tomdinchaina** [comment]
you just need to enter 1 or 2. It said "Found python version"
