### ISSUE TITLE
Bug: Its not sending any info to my webhook

### ISSUE THREAD

**Issue by CatIsTruck** [Smug246/Luna-Grabber#791]
### What Did You Expect To Happen?

To get my computer info to test Luna builder

### What Happened?

I build a .py and open it and nothing is sent to my webhook

### Add Screenshots

There is nothing to show

### Which Options Did You Select?

Discord Info, Browser Info, Roblox Info

### How Did You Build The File?

Standard Python

### Did You Bind The File?

No

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by BiggBenjo** [comment]
Hi! this is because of an error occurring from the actual py. file, I had this issue and fixed it! All I had to do was make a zip and add things such as txt files, then it will create a file folder. Then all of the data of the install (KB) will appear! Yw.

**Comment by Smug246** [comment]
@BiggBenjo could you ellaborate on what the actualy problem is and how did your solution fix that?

**Comment by 123stops123** [comment]
I have the same problem i , the webook dpnt send me the infos
