### ISSUE TITLE
feature: Just a little question

### ISSUE THREAD

**Issue by Soogrim** [Smug246/Luna-Grabber#793]
### What Feature?

I created my file, when I launch it, Luna bot only sends me my information, is it possible to use it to retrieve the information that I check for other discord users

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [ ] I want to work on this feature

**Comment by Smug246** [comment]
this doesnt even deserve an answer lmao
