### ISSUE TITLE
roblox cookie not working

### ISSUE THREAD

**Issue by OVER010** [Smug246/Luna-Grabber#795]
### What Did You Expect To Happen?

roblox to work

### What Happened?

roblox cookie not working

### Add Screenshots

..

### Which Options Did You Select?

Disable Defender, Discord Info, Fake Error, Games, Wifi Info, Ping, System Info, Common Files, Browser Info, Roblox Info, Injection, Clipboard, Webcam, Wallets

### How Did You Build The File?

Pyinstaller

### Did You Bind The File?

No

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by OVER010** [comment]
@Smug246 when I paste the cookie it loges me off the account (not working cookie)

**Comment by Zenx-s** [comment]
im pretty sure this is because roblox had resleased a feature that prevents you from logging into someones account with a cookie. it does this by checking ur location then kicking you out if the person didnt recieve email confirmation and you are in a different country.

**Comment by Smug246** [comment]
compare the two cookies and see whats different

**Comment by qprr** [comment]
having same prob
