### ISSUE TITLE
Inject payload

### ISSUE THREAD

**Issue by pontiggia** [Smug246/Luna-Grabber#796]
### What Feature?

Hey, I wonder if theres a chance to inject some kink of payload to at least grab the token or do more maybe, inside of an img, gif, etc. Other than just the exe or py file. Im not sure but I know that its possible to inject shell commands into image for example.

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [ ] I want to work on this feature

**Comment by Smug246** [comment]
if your talking about an image logger it's not possible
