### ISSUE TITLE
Bug: setup failed

### ISSUE THREAD

**Issue by marcibro** [Smug246/Luna-Grabber#798]
### What Did You Expect To Happen?

to run succesfully

### What Happened?

[notice] A new release of pip is available: 23.2.1 -> 24.1
[notice] To update, run: C:\Users\Desktop\Luna-Grabber-main\.venv_3.13.0a1\Scripts\python.exe -m pip install --upgrade pip
Even once i uprade pip it still says the same thing

### Add Screenshots

w

### Which Options Did You Select?

Add To Startup

### How Did You Build The File?

Standard Python

### Did You Bind The File?

Yes (Execute on Startup)

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Smug246** [comment]
that isnt an error thats just saying you should upgrade pip. if theres an error it should be above or below that
