### ISSUE TITLE
Error With Compiling File

### ISSUE THREAD

**Issue by KEZZY13374** [Smug246/Luna-Grabber#800]
### What Did You Expect To Happen?

I expected the file to be created after clicking, but there are bugs

### What Happened?

When I was building a file Pyinstaller.exe I got an error (Error with compiling file: [Errno 2] No such file or directory: 'loader.py') anyone know how to fix it>

### Add Screenshots

![Screenshot 2024-06-26 123416](https://github.com/Smug246/Luna-Grabber/assets/173900512/14f4bc37-8d72-4758-a7da-0ef04822ef65)

### Which Options Did You Select?

Discord Info, Fake Error, Games, Wifi Info, Ping, Anti Debug/VM, System Info, Common Files, Browser Info, Roblox Info, Obfuscation, Injection, Anti Spam, Clipboard, Webcam, Wallets

### How Did You Build The File?

Pyinstaller

### Did You Bind The File?

No

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by KEZZY13374** [comment]
@Smug246

**Comment by Smug246** [comment]
redownload it. you must have accidentally deleted the loader.py file
