### ISSUE TITLE
set up not opening

### ISSUE THREAD

**Issue by dfvbeDRBEDTRN** [Smug246/Luna-Grabber#801]
### What Did You Expect To Happen?

for setup to open

### What Happened?

i tried to open setup and it opened cmd for a second then closed

### Add Screenshots

https://github.com/Smug246/Luna-Grabber/assets/170912364/eb9d7fbf-5c5b-4de1-9eb1-29d65f194a0d

### Which Options Did You Select?

Ping

### How Did You Build The File?

Standard Python

### Did You Bind The File?

No

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Smug246** [comment]
i've no idea. cant really see what's going on there.

**Comment by dfvbeDRBEDTRN** [comment]
damn
