### ISSUE TITLE
feature: Vesktop Support

### ISSUE THREAD

**Issue by justDarian** [Smug246/Luna-Grabber#803]
### What Feature?

Support the `Vencord/Vesktop` client

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [ ] I want to work on this feature

**Comment by Smug246** [comment]
what exactly would i be supporting. adding that client to the paths to extract tokens?

**Comment by redactedontop** [comment]
Yah, I think that's what he wants.

**Comment by Smug246** [comment]
in the latest version vesktop is now supported
