### ISSUE TITLE
feature: commands

### ISSUE THREAD

**Issue by tamasko51** [Smug246/Luna-Grabber#804]
### What Feature?

to upload files in the victims pc, and can execute files.
and to show processes, and give a number each process, and can kill process by .kill <process number>
and to screen shot, by command .ss

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I want to work on this feature

**Comment by Smug246** [comment]
that's a rat. which isn't what this is
