### ISSUE TITLE
Bug: python was not found run without arguments to install from the microsoft store

### ISSUE THREAD

**Issue by yuviydiscord** [Smug246/Luna-Grabber#805]
### What Did You Expect To Happen?

for the setup to do its thing duh

### What Happened?

whenever i downloaded the release i extracted it then i ran the setup (i have the python stuff installed) then when it opens it says 3.11 python not installed so then it says installing then it says python was not found run without arguments to install from the microsoft store before i googled how to fix i did the steps and when i did the setup wont open i ran as admin to

### Add Screenshots

dont have

### Which Options Did You Select?

System Info

### How Did You Build The File?

Standard Python

### Did You Bind The File?

No

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by yuviydiscord** [comment]
i ran it in cmd and this is what it says 
![image](https://github.com/Smug246/Luna-Grabber/assets/158117551/c8dab54e-a058-4209-bf1c-3ec3d4ff3bda)

**Comment by Smug246** [comment]
download python from the website not the microsoft store

**Comment by yuviydiscord** [comment]
i did lol
