### ISSUE TITLE
How to remove it from system?

### ISSUE THREAD

**Issue by HahaAshley** [Smug246/Luna-Grabber#806]
### What Feature?

I was being a dumbass and installed a exe file from my "friend", now it's on my system, how do i stop all of it?

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I want to work on this feature

**Comment by Semireq** [comment]
cant LOL

**Comment by Smug246** [comment]
remove it from startup delete discord and reinstall. should be good. get a better antivirus too
