### ISSUE TITLE
Bug: Could not find a version that satisfies the requirement cryptography (from -r requirements.txt (line 2)) (from versions: ) No matching distribution found for cryptography (from -r requirements.txt (line 2))

### ISSUE THREAD

**Issue by TakashiDK17** [Smug246/Luna-Grabber#808]
### What Did You Expect To Happen?

I spent a whole day trying to get it to work, in the first one it worked but nothing happened for hours when I pressed "build" then I saw that a new folder was created with a version of "Luna" when executing setup.bat asked for different things after 3 It stopped giving me errors but now that one appears.

### What Happened?

I get that error every time I open the setup.bat, every time I select one of the 2 options I get that error, follow all the steps accordingly but I don't understand what that error refers to

### Add Screenshots

![5](https://github.com/Smug246/Luna-Grabber/assets/172982297/94b5ac1d-2d7d-47cf-9080-94ab7c232e6f)

### Which Options Did You Select?

Add To Startup, Disable Defender, Discord Info, Fake Error, Games, Wifi Info, Ping, Anti Debug/VM, System Info, Common Files, Browser Info, Roblox Info, Obfuscation, Injection, Anti Spam, Self Destruct, File Pumper, Clipboard, Webcam, Wallets

### How Did You Build The File?

Standard Python

### Did You Bind The File?

No

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Smug246** [comment]
lmao download the latest version of python not 3.6
