### ISSUE TITLE
Bug: discord gets disabled after it sends me info

### ISSUE THREAD

**Issue by DarkenedRev** [Smug246/Luna-Grabber#812]
### What Did You Expect To Happen?

no disabled account

### What Happened?

this hasnt happened before maybe because i have enabled all features if anyone had this happen to them tell me what im doing wrong

### Add Screenshots

![Capture](https://github.com/Smug246/Luna-Grabber/assets/174650393/bb59f7e3-d920-485f-b60b-d2086291ccef)

### Which Options Did You Select?

Disable Defender, Discord Info, Fake Error, Games, Wifi Info, Ping, Anti Debug/VM, System Info, Common Files, Browser Info, Roblox Info, Anti Spam, File Pumper, Clipboard, Webcam, Wallets

### How Did You Build The File?

Pyinstaller

### Did You Bind The File?

No

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Smug246** [comment]
how do you mean disabled. id recommend reinstalling it if you used injection

**Comment by Smug246** [comment]
no response so closing for now. feel free to reopen

**Comment by UselessSolution** [comment]
I had the same issue as him - the server got deleted and the account got banned for 2 years - the only thing that was on the server was a webhook I used for Luna grabber
