### ISSUE TITLE
feature:Telegram info option

### ISSUE THREAD

**Issue by GasmiAbdou** [Smug246/Luna-Grabber#815]
### What Feature?

Make the user choose to get the grabbed info from discord webhook or telegeram !! bcs sometimes randoms can access the webhook from .exe file somehow 

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [ ] I want to work on this feature

**Comment by Smug246** [comment]
this has already been asked so closing
