### ISSUE TITLE
Bug: issue

### ISSUE THREAD

**Issue by ZakaOsam** [Smug246/Luna-Grabber#817]
### What Did You Expect To Happen?

i cant uninstall phyton to install another version.

### What Happened?

.

### Add Screenshots

![image](https://github.com/Smug246/Luna-Grabber/assets/175038051/8a1452c0-71db-4700-a09c-3325a098a109)

### Which Options Did You Select?

Discord Info

### How Did You Build The File?

Standard Python

### Did You Bind The File?

Yes (Execute on Startup)

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Smug246** [comment]
this isnt an issue with this tool this is an issue with python and your machine so I can't help you. have a look at this:
https://discuss.python.org/t/unable-to-install-python-on-my-computer/30657
