### ISSUE TITLE
Please help how do i fix this issue?

### ISSUE THREAD

**Issue by NOXXTO** [Smug246/Luna-Grabber#821]
### What Did You Expect To Happen?

it expected it run smoothly because I had all the requirements.

### What Happened?

i was trying to make a .exe file but it keeps showing me errors please help me.

### Add Screenshots

![image](https://github.com/user-attachments/assets/3b6eb132-c3af-4808-8eb2-cefb0ad6e68a)

### Which Options Did You Select?

Games

### How Did You Build The File?

Nuitka

### Did You Bind The File?

Yes (Execute on Startup)

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by SickoHQ** [comment]
DM me on discord I believe I may have a solution for you but need the files if you still have them 
s.i.c.k.o.b.o.i
