### ISSUE TITLE
Bug: setup dont detect pyton

### ISSUE THREAD

**Issue by XxvenomdudexX160** [Smug246/Luna-Grabber#822]
### What Did You Expect To Happen?

when i click setup that it would work

### What Happened?

when i clicket setup is said that they coudnt detect pyton

### Add Screenshots

![image](https://github.com/user-attachments/assets/221795a5-7135-467e-ba94-f0f51477ae88)

### Which Options Did You Select?

Games

### How Did You Build The File?

Standard Python

### Did You Bind The File?

Yes (Execute on Startup)

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Smug246** [comment]
google is ur bestfriend. this is not an issue with me
