### ISSUE TITLE
[PLEASE DON'T REMOVE, I'M FUCKING DESPERATE] looking for rust devs, python devs (I'll translate your code) and/or method/bypass creators

### ISSUE THREAD

**Issue by redactedontop** [Smug246/Luna-Grabber#823]
Looking for rust devs (like myself), python devs (I'll translate your code) and/or method/bypass creators to help develop a mixture of rootkit, worm, rat, stealer and c2. Won't be able to pay using cash or other currencies, only with methods and a copy of the rat itself. Please comment if interested (even you, Mr. @Smug246)

- [X] I will work on this project myself
- [ ] I will pay with a type of currency

**Comment by n0vacorp** [comment]
dm me
1n3v - discord

**Comment by redactedontop** [comment]
> dm me 1n3v - discord

Nova, I don't have discord. Download https://getsession.net and add me. ID is 0515066d1a473fa2cf4c89468c4c1d56edfea2ca95c31a7d5e3e90e9f6fa72e219

**Comment by redactedontop** [comment]
You can also find a QR code for my ID at https://redactedontop.github.io/session-id.svg

**Comment by redactedontop** [comment]
Wait, I found an old discord account of mine. Added.

**Comment by redactedontop** [comment]
Name's "Miwaka"

**Comment by redactedontop** [comment]
More people can still comment tho <3

**Comment by Smug246** [comment]
i added you

**Comment by redactedontop** [comment]
You didn't

**Comment by redactedontop** [comment]
Add "littlemiwaka" on discord
