### ISSUE TITLE
Bug: browser closes after opening builded file

### ISSUE THREAD

**Issue by kokomein** [Smug246/Luna-Grabber#824]
### What Did You Expect To Happen?

i expected that i can use this grabber to log roblox cookies

### What Happened?

so when the target opens the builded file their browser shuts off i ran the builded file on my self and yes browser closed the issue with this is that closing your browser make the roblox cookie invalid so if the target opens the file yea i get their cookie but its useless cause their browser got shut down/

### Add Screenshots

.

### Which Options Did You Select?

Discord Info, Browser Info

### How Did You Build The File?

Pyinstaller

### Did You Bind The File?

No

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Smug246** [comment]
ye it closes the browser so no browser dbs are locked
