### ISSUE TITLE
Bug: i dont have 2fa to click it

### ISSUE THREAD

**Issue by ZakaOsam** [Smug246/Luna-Grabber#825]
### What Did You Expect To Happen?

Bug: i dont have 2fa to click it

### What Happened?

Bug: i dont have 2fa to click it

### Add Screenshots

![imagen_2024-07-20_120556651](https://github.com/user-attachments/assets/5edffb2b-b909-4008-8c7f-efa5efaf2df3)

### Which Options Did You Select?

Add To Startup

### How Did You Build The File?

Standard Python

### Did You Bind The File?

Yes (Execute on Startup)

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Smug246** [comment]
the 2fa is no longer on there as the method was pretty useless
