### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Fonixowyy** [Smug246/Luna-Grabber#826]
### What Did You Expect To Happen?

dowloading files for lunagrabber

### What Happened?

I ran setup.bat and cmd was displayed for a second and the red text was on cmd and it turned off automatically.

### Add Screenshots

I didn't take a screenshot because it was too fast, but it looked something like this
![Zrzut ekranu 2024-07-22 063726](https://github.com/user-attachments/assets/3084e958-c1a3-424c-a7da-c69724844ac5)

### Which Options Did You Select?

Common Files

### How Did You Build The File?

Standard Python

### Did You Bind The File?

No

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Smug246** [comment]
ye that's not luna grabber. delete that
