### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by ororor69** [Smug246/Luna-Grabber#830]
### What Did You Expect To Happen?

attach

### What Happened?

dosent detect python

### Add Screenshots

![bilde](https://github.com/user-attachments/assets/70208cd3-0414-484d-b538-c9c776e65840)

### Which Options Did You Select?

Add To Startup

### How Did You Build The File?

Standard Python

### Did You Bind The File?

Yes (Execute on Startup)

### Check the following before submitting (If Applicable)

- [ ] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by HealthyPepper55** [comment]
![image](https://github.com/user-attachments/assets/428240b2-fac4-4fdf-9baf-983e83135dc9)
Uninstall python once, then run the python installer and put CHECK in the image here.

**Comment by ororor69** [comment]
![bilde](https://github.com/user-attachments/assets/2e90a690-8764-4293-8e45-a639c67bfbe1)

**Comment by Deadshotv21** [comment]
> ![bilde](https://private-user-images.githubusercontent.com/174837201/352330961-2e90a690-8764-4293-8e45-a639c67bfbe1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMDE2NzQsIm5iZiI6MTcyMjMwMTM3NCwicGF0aCI6Ii8xNzQ4MzcyMDEvMzUyMzMwOTYxLTJlOTBhNjkwLTg3NjQtNDI5My04ZTQ1LWE2MzljNjdiZmJlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMFQwMTAyNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMDhhMmQyMjJlMmI3MDExYzFiMzAwYjQxODZhMzgxYjA1MWM2NTdkOTA5MDg2OTRmM2RlYjg0NTViNTc5MzAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dCFsdFe5MaSFlQcuyAhVZgbC9k7rlFai6XJK1Bs4iXk)

python 3.12 doesn't work, use 3.11 instead

**Comment by NFS11** [comment]
@Deadshotv21 it doesnt work with nuitka, but pyinstaller works just fine and even so, nuitka doesnt work for some reason?
