### ISSUE TITLE
Bug: What to do after creating the webhook?

### ISSUE THREAD

**Issue by SimpleGamer29** [Smug246/Luna-Grabber#836]
### What Did You Expect To Happen?

i dont know exactly what was suppoed to happen using it first time! maybe you just make a totourial for this ( discord grabber )

### What Happened?

i can understand what to to after it says build completed like nothing happens after that, how am i suppost to grab tokens ? how is it ment to send msgs in the discord server

### Add Screenshots

![image](https://github.com/user-attachments/assets/8f7fc7e9-aff4-481b-adfa-91b536c846d7)

### Which Options Did You Select?

Discord Info

### How Did You Build The File?

Pyinstaller

### Did You Bind The File?

Yes (Execute on Startup)

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by SimpleGamer29** [comment]
sorry i did not bind the file!

**Comment by NFS11** [comment]
copy the webhook link, then put it in luna grabber builder. then you can make a file

**Comment by NFS11** [comment]
and then you send that file to someone and get them to open it, in your server a message will be sent with their details and a zipped file if you selected browser info, webcams and all that.

**Comment by NFS11** [comment]
the file will be found in the luna grabber folder on whatever name you wanted it to be
