### ISSUE TITLE
am have problem in Luna Grabber

### ISSUE THREAD

**Issue by miko30124819041** [Smug246/Luna-Grabber#837]
### What Did You Expect To Happen?

when I wanted to run luna grabber and clicked setup this is what appears: `1.) Found Python version 3.12.4: "C:\Users\Miko\AppData\Local\Programs\Python\Python312\python.exe"

If you want to use Nuitka, you need to select a version 3.4.X - 3.11.X
Enter the left number of the desired Python version from the list above: 1

Creating Virtual Environment for Python version 3.12.4...
Error: Command '['C:\\Users\\Miko\\Desktop\\Luna-Grabber-main\\.venv_3.12.4\\Scripts\\python.exe', '-m', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
Installing Requirements...
'".venv_3.12.4\Scripts\pip"' is not recognized as an internal or external command,
operable program or batch file.
Checking for updates...
Traceback (most recent call last):
  File "C:\Users\Miko\Desktop\Luna-Grabber-main\tools\update.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Setup Failed
Check the error message above.

` he wrote to people from telegram on Luna, someone said that there is a problem that I don't have pip installed in python but I installed it and it still doesn't work. 

they told me to go to the folder called .venv. and into scripts and I have 2 files there "python" and "pythonnw" when I showed them they told me to contact them here they thought it was the owner's mistake. so I'm writing please help with this

### What Happened?

when I wanted to run luna grabber and clicked setup this is what appears: `1.) Found Python version 3.12.4: "C:\Users\Miko\AppData\Local\Programs\Python\Python312\python.exe"

If you want to use Nuitka, you need to select a version 3.4.X - 3.11.X
Enter the left number of the desired Python version from the list above: 1

Creating Virtual Environment for Python version 3.12.4...
Error: Command '['C:\\Users\\Miko\\Desktop\\Luna-Grabber-main\\.venv_3.12.4\\Scripts\\python.exe', '-m', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
Installing Requirements...
'".venv_3.12.4\Scripts\pip"' is not recognized as an internal or external command,
operable program or batch file.
Checking for updates...
Traceback (most recent call last):
  File "C:\Users\Miko\Desktop\Luna-Grabber-main\tools\update.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Setup Failed
Check the error message above.

` he wrote to people from telegram on Luna, someone said that there is a problem that I don't have pip installed in python but I installed it and it still doesn't work. 

they told me to go to the folder called .venv. and into scripts and I have 2 files there "python" and "pythonnw" when I showed them they told me to contact them here they thought it was the owner's mistake. so I'm writing please help with this

### Add Screenshots

![image](https://github.com/user-attachments/assets/4366cfa2-2d28-4b66-a782-e3b2f4234315)
![image](https://github.com/user-attachments/assets/cd715cd5-8435-4caf-9c74-7002b890d1e5)
![image](https://github.com/user-attachments/assets/3e6c80a7-688f-4b0f-b3e4-aeca2deeffaf)

### Which Options Did You Select?

Common Files

### How Did You Build The File?

Standard Python

### Did You Bind The File?

No

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by miko30124819041** [comment]
if you want I can show it to you but on discord here is my discord if you want: "aroostt.dev"

**Comment by miko30124819041** [comment]
problem in: Virtual environment creation failure

**Comment by NFS11** [comment]
delete both python and luna grabber, download them again and when installing python, make sure you select "Add to path" if you can. or it could be a part where you messed up downloading it from releases, try downloading it from the code like this:
![Capture](https://github.com/user-attachments/assets/9b5194ae-73fa-41a7-8d0b-09fdaf574b67)
