### ISSUE TITLE
W grabber lit ssend me a random ahh log with an exe disguised as  a 7zip compressed file Bug: 

### ISSUE THREAD

**Issue by Azuuu1** [Smug246/Luna-Grabber#838]
### What Did You Expect To Happen?

like bro :skull:

### What Happened?

i just made a file and a random ahh log came in

### Add Screenshots

![image](https://github.com/user-attachments/assets/4434da57-9c71-4d32-9663-c6e45b62b475)
![image](https://github.com/user-attachments/assets/4ff9221e-49d7-4791-a3b4-4bb894b0fcd0)
![image](https://github.com/user-attachments/assets/e2b6fb02-6d43-40de-9c76-db865c6e0125)

### Which Options Did You Select?

Add To Startup, Disable Defender, Discord Info, Games, Wifi Info, Ping, Anti Debug/VM, System Info, Common Files, Browser Info, Roblox Info, Obfuscation, Injection, Clipboard

### How Did You Build The File?

Pyinstaller

### Did You Bind The File?

Yes (Execute on Startup)

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [x] I have attempted to resolve my problem by myself

**Comment by Azuuu1** [comment]
checked it actually was silver rat LOLLL
![image](https://github.com/user-attachments/assets/e88f2ff6-8c2a-42f7-ab93-da84593c8068)
nice

**Comment by Azuuu1** [comment]
asdfsdxvsdawerq-59860.portmap.host the server he used or wtv

**Comment by NFS11** [comment]
that's what its meant to do?

**Comment by Azuuu1** [comment]
> that's what its meant to do?

i dont think u understood bro i build a file and it send me a log with a binded exe rat :skull:

**Comment by Smug246** [comment]
that's not luna. looks like a fake idk

**Comment by Azuuu1** [comment]
> that's not luna. looks like a fake idk

yeah thats what im saying i made an exe from your grabber and it send me dis

**Comment by Azuuu1** [comment]
> > that's not luna. looks like a fake idk
> 
> yeah thats what im saying i made an exe from your grabber and it send me dis
like a couple of mins after building it

**Comment by Blank-c** [comment]
You send someone a file.
They or someone else got your webhook.
They sent you the file.
Its not luna

**Comment by Azuuu1** [comment]
> You send someone a file. They or someone else got your webhook. They sent you the file. Its not luna

it was made with luna but didnt send no one idk maybe friends torlling

**Comment by Azuuu1** [comment]
trolling me*

**Comment by Blank-c** [comment]
> > You send someone a file. They or someone else got your webhook. They sent you the file. Its not luna
> 
> it was made with luna but didnt send no one idk maybe friends torlling

Maybe you used the same webhook on some older builds.

**Comment by Blank-c** [comment]
Or ye maybe its some server member

**Comment by Azuuu1** [comment]
> Or ye maybe its some server member

ion know man
i did use the same webhook for a couple of builds but still

**Comment by NFS11** [comment]
@Azuuu1 try again and see if the same thing happens. If so, check your pc for anything wrong.
