### ISSUE TITLE
Bug: 1.) Found Python version 3.12.1: "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python312\python.exe"  If you want to use Nuitka, you need to select a version 3.4.X - 3.11.X Enter the left number of the desired Python version from the list above:

### ISSUE THREAD

**Issue by Zaydoxdev** [Smug246/Luna-Grabber#899]
### What Did You Expect To Happen?

1.) Found Python version 3.12.1: "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python312\python.exe"

If you want to use Nuitka, you need to select a version 3.4.X - 3.11.X
Enter the left number of the desired Python version from the list above:

WHEN i write 3.11 IT's exiting

### What Happened?

1.) Found Python version 3.12.1: "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python312\python.exe"

If you want to use Nuitka, you need to select a version 3.4.X - 3.11.X
Enter the left number of the desired Python version from the list above:

WHEN i write 3.11 IT's exiting

### Add Screenshots

![image](https://github.com/user-attachments/assets/609316bb-2b2c-4992-98b1-8ae87073ab63)

### Which Options Did You Select?

Add To Startup

### How Did You Build The File?

Standard Python

### Did You Bind The File?

Yes (Execute on Startup)

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by MootjeD** [comment]
press 1, its enough.

**Comment by Lolmax962** [comment]
press 1 dumb ahh
