### ISSUE TITLE
Bug: error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by coel351** [Smug246/Luna-Grabber#922]
### What Did You Expect To Happen?

dependencies to install

### What Happened?

cmd crashes to desktop during dependency install step
note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for cx_Logging
      Failed to build cx_Logging
      ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (cx_Logging)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

### Add Screenshots

Collecting cx-Freeze (from -r requirements.txt (line 11))
  Using cached cx_freeze-7.2.3.tar.gz (3.0 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Collecting setuptools<75,>=70.1
        Using cached setuptools-74.1.3-py3-none-any.whl.metadata (6.7 kB)
      Collecting cx_Logging>=3.1
        Using cached cx_Logging-3.2.0.tar.gz (26 kB)
        Installing build dependencies: started
        Installing build dependencies: still running...
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Using cached setuptools-74.1.3-py3-none-any.whl (1.3 MB)
      Building wheels for collected packages: cx_Logging
        Building wheel for cx_Logging (pyproject.toml): started
        Building wheel for cx_Logging (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        Building wheel for cx_Logging (pyproject.toml) did not run successfully.
        exit code: 1

        [6 lines of output]
        running bdist_wheel
        running build
        running build_ext
        creating build\implib.win-amd64-cpython-313
        building 'cx_Logging' extension
        error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for cx_Logging
      Failed to build cx_Logging
      ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (cx_Logging)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Checking for updates...
Traceback (most recent call last):
  File "C:\Users\Gamer\Desktop\token\Luna-Grabber-1.5.5-alpha\Luna-Grabber-1.5.5-alpha\tools\update.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

### Which Options Did You Select?

Add To Startup

### How Did You Build The File?

Standard Python

### Did You Bind The File?

No

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by coel351** [comment]
was running wrong version of python.

**Comment by coel351** [comment]
was running wrong version of python.

**Comment by AleixPeix12** [comment]
> was running wrong version of python.

And what i need to do to fix?
