### ISSUE TITLE
Bug: Error with install

### ISSUE THREAD

**Issue by AleixPeix12** [Smug246/Luna-Grabber#924]
### What Did You Expect To Happen?

Don't go

### What Happened?

 Building wheel for nuitka (pyproject.toml) ... done
  Created wheel for nuitka: filename=Nuitka-2.4.8-cp313-cp313-win_amd64.whl size=3402097 sha256=aaabf8755bf906805e2dd14de827c6ef59d36d937d0a40a9d5f4800fa59a9d4a
  Stored in directory: c:\users\aleix\appdata\local\pip\cache\wheels\a2\ec\8e\8d3333cd6b929215be8e50284f146e6d78d35df0c72e5d94e9
  Building wheel for lz4 (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for lz4 (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      C:\Users\Aleix\AppData\Local\Temp\pip-build-env-k9p46u1l\overlay\Lib\site-packages\setuptools\_distutils\dist.py:261: UserWarning: Unknown distribution option: 'tests_require'
        warnings.warn(msg)
      running bdist_wheel
      running build
      running build_py
      creating build\lib.win-amd64-cpython-313\lz4
      copying lz4\version.py -> build\lib.win-amd64-cpython-313\lz4
      copying lz4\__init__.py -> build\lib.win-amd64-cpython-313\lz4
      creating build\lib.win-amd64-cpython-313\lz4\block
      copying lz4\block\__init__.py -> build\lib.win-amd64-cpython-313\lz4\block
      creating build\lib.win-amd64-cpython-313\lz4\frame
      copying lz4\frame\__init__.py -> build\lib.win-amd64-cpython-313\lz4\frame
      running build_ext
      building 'lz4._version' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lz4
Successfully built pyperclip nuitka
Failed to build lz4
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (lz4)
Checking for updates...
Traceback (most recent call last):
  File "C:\Users\Aleix\Desktop\Luna-Grabber-main\tools\update.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Setup Failed
Check the error message above.

### Add Screenshots

![image](https://github.com/user-attachments/assets/23a61d0f-5dac-42af-ac63-57af3d2650ef)

### Which Options Did You Select?

Add To Startup

### How Did You Build The File?

Standard Python

### Did You Bind The File?

Yes (Execute on Startup)

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by rohanraj-aipro** [comment]
Hello.
I'm getting the same problem. How did you solve it?

**Comment by rohanraj-aipro** [comment]
Solved it Use a different version of Python.

I faced the error when i was using 3.13.1
I installed and used 3.12.x
It worked

**Comment by Humble-da-ops** [comment]
> Solved it Use a different version of Python.
> 
> I faced the error when i was using 3.13.1 I installed and used 3.12.x It worked

THATS why it wasnt working for me ok im going to download the 3.12.x version tysm bro lill respond back if it works
